# frozen_string_literal: true

# +blazen+ — Ruby bindings for the Blazen LLM-orchestration framework.
#
# The native surface is exposed via Mozilla UniFFI: a shared library
# (+libblazen_uniffi.<so|dylib|dll>+) plus an autogenerated Ruby FFI loader
# at +lib/uniffi/blazen/blazen.rb+. This file (the gem entrypoint) requires
# the loader and then layers idiomatic helpers on top:
#
# * {Blazen::Providers} — keyword-arg factories for every backend
# * {Blazen::Llm} — convenience builders for {Blazen::ChatMessage} etc.
# * {Blazen::WorkflowHelpers} / {Blazen.workflow} — workflow construction
# * {Blazen::PipelineHelpers} / {Blazen.pipeline} — pipeline construction
# * {Blazen::Batch}, {Blazen::Streaming}, {Blazen::Compute}, {Blazen::Persist},
#   {Blazen::Telemetry}, {Blazen::Peer}, {Blazen::Agents}
# * {Blazen::Error} and its subclasses — idiomatic Ruby exception hierarchy
#
# The UniFFI-generated module is *also* named +Blazen+, so the helpers here
# are added to the same namespace rather than wrapping it.
#
# @example
#   require "blazen"
#
#   Blazen.init
#   begin
#     model = Blazen::Providers.openai(api_key: ENV.fetch("OPENAI_API_KEY"))
#     req = Blazen::Llm.completion_request(
#       messages: [Blazen::Llm.user("Say hi.")],
#       max_tokens: 64,
#     )
#     resp = model.complete_blocking(req)
#     puts resp.content
#   ensure
#     Blazen.shutdown
#   end

require "rbconfig"
require "ffi"

require_relative "blazen/ffi"

require_relative "blazen/version"
require_relative "blazen/errors"
require_relative "blazen/llm"
require_relative "blazen/providers"
require_relative "blazen/workflow"
require_relative "blazen/pipeline"
require_relative "blazen/batch"
require_relative "blazen/streaming"
require_relative "blazen/agent"
require_relative "blazen/compute"
require_relative "blazen/persist"
require_relative "blazen/telemetry"
require_relative "blazen/peer"

module Blazen
  class << self
    # Shuts down telemetry exporters, flushing any buffered spans/metrics.
    #
    # Alias for {Blazen.shutdown_telemetry}.
    #
    # @return [void]
    alias_method :shutdown, :shutdown_telemetry
  end
end
