// auto-generated by scripts/post-build.mjs from blazen.wasi-browser.js
// DO NOT EDIT -- regenerated every `napi build`.
//
// The `blazen/workers` subpath entry for Cloudflare Workers (workerd) and
// any other edge runtime that supports wrangler-style static .wasm imports.
// Consumers do `import { ... } from 'blazen/workers'` instead of
// `from 'blazen'`; they must also install
// `@blazen-dev/blazen-wasm32-wasi` directly (an optional peerDependency on
// the parent `blazen` package).
//
// Loads the wasm via wrangler's static `import wasm from '@scope/pkg/foo.wasm'`
// form, which both wrangler >=3.15 and `@cloudflare/vite-plugin` resolve to
// a real WebAssembly.Module at bundle time. No `import.meta.url`, no fetch,
// no top-level await, no per-platform require() chain.

import {
  getDefaultContext as __emnapiGetDefaultContext,
  instantiateNapiModuleSync as __emnapiInstantiateNapiModuleSync,
  WASI as __WASI,
} from '@napi-rs/wasm-runtime'

// Subpath import on the wasm32-wasi subpackage. The subpackage's package.json
// exposes `./blazen.wasm32-wasi.wasm` in its exports map (added by the
// release pipeline and by `stage-local-blazen.sh` for dev).
import __wasmModule from '@blazen-dev/blazen-wasm32-wasi/blazen.wasm32-wasi.wasm'

// Cloudflare Workers / workerd disallows dynamic code generation
// (`new Function`, `eval`, `napi_run_script`). Blazen's WASI async
// dispatcher (`crates/blazen-node/src/wasi_async.rs`) needs a microtask
// scheduler and a setTimeout-based sleeper, normally built via
// `env.run_script`. We predefine them here as globals so the Rust
// `install()` function can read them via `globalThis` instead of
// invoking the JS engine's eval, which workerd blocks.
globalThis.__blazenScheduler = () => {
  Promise.resolve().then(() => globalThis.__blazenDrainAsyncQueue())
}
globalThis.__blazenSleeper = (ms) =>
  new Promise((r) => globalThis.setTimeout(r, ms))

const __wasi = new __WASI({ version: 'preview1' })
const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

const {
  instance: __napiInstance,
  module: __wasiModule,
  napiModule: __napiModule,
} = __emnapiInstantiateNapiModuleSync(__wasmModule, {
  context: __emnapiContext,
  asyncWorkPoolSize: 0, // workerd has no Worker class
  wasi: __wasi,
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})

export default __napiModule.exports
export const ActiveWorkflowSnapshot = __napiModule.exports.ActiveWorkflowSnapshot
export const JsActiveWorkflowSnapshot = __napiModule.exports.JsActiveWorkflowSnapshot
export const AgentResult = __napiModule.exports.AgentResult
export const JsAgentResult = __napiModule.exports.JsAgentResult
export const AnthropicProvider = __napiModule.exports.AnthropicProvider
export const JsAnthropicProvider = __napiModule.exports.JsAnthropicProvider
export const ApiProtocol = __napiModule.exports.ApiProtocol
export const JsApiProtocol = __napiModule.exports.JsApiProtocol
export const AudioMusicProviderDefaults = __napiModule.exports.AudioMusicProviderDefaults
export const JsAudioMusicProviderDefaults = __napiModule.exports.JsAudioMusicProviderDefaults
export const AudioSpeechProviderDefaults = __napiModule.exports.AudioSpeechProviderDefaults
export const JsAudioSpeechProviderDefaults = __napiModule.exports.JsAudioSpeechProviderDefaults
export const AzureOpenAiProvider = __napiModule.exports.AzureOpenAiProvider
export const JsAzureOpenAiProvider = __napiModule.exports.JsAzureOpenAiProvider
export const BackgroundRemovalProvider = __napiModule.exports.BackgroundRemovalProvider
export const JsBackgroundRemovalProvider = __napiModule.exports.JsBackgroundRemovalProvider
export const BackgroundRemovalProviderDefaults = __napiModule.exports.BackgroundRemovalProviderDefaults
export const JsBackgroundRemovalProviderDefaults = __napiModule.exports.JsBackgroundRemovalProviderDefaults
export const BaseProvider = __napiModule.exports.BaseProvider
export const JsBaseProvider = __napiModule.exports.JsBaseProvider
export const BaseProviderDefaults = __napiModule.exports.BaseProviderDefaults
export const JsBaseProviderDefaults = __napiModule.exports.JsBaseProviderDefaults
export const BatchConfig = __napiModule.exports.BatchConfig
export const JsBatchConfig = __napiModule.exports.JsBatchConfig
export const BatchResult = __napiModule.exports.BatchResult
export const JsBatchResult = __napiModule.exports.JsBatchResult
export const BedrockProvider = __napiModule.exports.BedrockProvider
export const JsBedrockProvider = __napiModule.exports.JsBedrockProvider
export const BlazenPeerClient = __napiModule.exports.BlazenPeerClient
export const JsBlazenPeerClient = __napiModule.exports.JsBlazenPeerClient
export const BlazenPeerServer = __napiModule.exports.BlazenPeerServer
export const JsBlazenPeerServer = __napiModule.exports.JsBlazenPeerServer
export const BytesWrapper = __napiModule.exports.BytesWrapper
export const JsBytesWrapper = __napiModule.exports.JsBytesWrapper
export const CachedCompletionModel = __napiModule.exports.CachedCompletionModel
export const JsCachedCompletionModel = __napiModule.exports.JsCachedCompletionModel
export const CacheMiddleware = __napiModule.exports.CacheMiddleware
export const JsCacheMiddleware = __napiModule.exports.JsCacheMiddleware
export const CandleEmbedProvider = __napiModule.exports.CandleEmbedProvider
export const JsCandleEmbedProvider = __napiModule.exports.JsCandleEmbedProvider
export const CandleInferenceResult = __napiModule.exports.CandleInferenceResult
export const JsCandleInferenceResult = __napiModule.exports.JsCandleInferenceResult
export const CandleLlmProvider = __napiModule.exports.CandleLlmProvider
export const JsCandleLlmProvider = __napiModule.exports.JsCandleLlmProvider
export const ChatMessage = __napiModule.exports.ChatMessage
export const JsChatMessage = __napiModule.exports.JsChatMessage
export const ChatMessageInput = __napiModule.exports.ChatMessageInput
export const JsChatMessageInput = __napiModule.exports.JsChatMessageInput
export const ChatWindow = __napiModule.exports.ChatWindow
export const JsChatWindow = __napiModule.exports.JsChatWindow
export const CheckpointStore = __napiModule.exports.CheckpointStore
export const JsCheckpointStore = __napiModule.exports.JsCheckpointStore
export const Citation = __napiModule.exports.Citation
export const JsCitationClass = __napiModule.exports.JsCitationClass
export const CohereProvider = __napiModule.exports.CohereProvider
export const JsCohereProvider = __napiModule.exports.JsCohereProvider
export const CompletionModel = __napiModule.exports.CompletionModel
export const JsCompletionModel = __napiModule.exports.JsCompletionModel
export const CompletionProviderDefaults = __napiModule.exports.CompletionProviderDefaults
export const JsCompletionProviderDefaults = __napiModule.exports.JsCompletionProviderDefaults
export const ContentStore = __napiModule.exports.ContentStore
export const JsContentStore = __napiModule.exports.JsContentStore
export const Context = __napiModule.exports.Context
export const JsContext = __napiModule.exports.JsContext
export const CustomProvider = __napiModule.exports.CustomProvider
export const JsCustomProvider = __napiModule.exports.JsCustomProvider
export const DeepSeekProvider = __napiModule.exports.DeepSeekProvider
export const JsDeepSeekProvider = __napiModule.exports.JsDeepSeekProvider
export const DiffusionProvider = __napiModule.exports.DiffusionProvider
export const JsDiffusionProvider = __napiModule.exports.JsDiffusionProvider
export const DynamicEvent = __napiModule.exports.DynamicEvent
export const JsDynamicEvent = __napiModule.exports.JsDynamicEvent
export const EmbeddingModel = __napiModule.exports.EmbeddingModel
export const JsEmbeddingModel = __napiModule.exports.JsEmbeddingModel
export const EmbeddingProviderDefaults = __napiModule.exports.EmbeddingProviderDefaults
export const JsEmbeddingProviderDefaults = __napiModule.exports.JsEmbeddingProviderDefaults
export const EmbedProvider = __napiModule.exports.EmbedProvider
export const JsEmbedProvider = __napiModule.exports.JsEmbedProvider
export const EstimateCounter = __napiModule.exports.EstimateCounter
export const JsEstimateCounter = __napiModule.exports.JsEstimateCounter
export const FalEmbeddingModel = __napiModule.exports.FalEmbeddingModel
export const JsFalEmbeddingModel = __napiModule.exports.JsFalEmbeddingModel
export const FallbackModel = __napiModule.exports.FallbackModel
export const JsFallbackModel = __napiModule.exports.JsFallbackModel
export const FalProvider = __napiModule.exports.FalProvider
export const JsFalProvider = __napiModule.exports.JsFalProvider
export const FastEmbedModel = __napiModule.exports.FastEmbedModel
export const JsFastEmbedModel = __napiModule.exports.JsFastEmbedModel
export const FireworksProvider = __napiModule.exports.FireworksProvider
export const JsFireworksProvider = __napiModule.exports.JsFireworksProvider
export const GeminiProvider = __napiModule.exports.GeminiProvider
export const JsGeminiProvider = __napiModule.exports.JsGeminiProvider
export const GroqProvider = __napiModule.exports.GroqProvider
export const JsGroqProvider = __napiModule.exports.JsGroqProvider
export const HistoryEventKind = __napiModule.exports.HistoryEventKind
export const JsHistoryEventKind = __napiModule.exports.JsHistoryEventKind
export const HttpClient = __napiModule.exports.HttpClient
export const JsHttpClient = __napiModule.exports.JsHttpClient
export const HttpPeerClient = __napiModule.exports.HttpPeerClient
export const JsHttpPeerClient = __napiModule.exports.JsHttpPeerClient
export const ImageGenerationProviderDefaults = __napiModule.exports.ImageGenerationProviderDefaults
export const JsImageGenerationProviderDefaults = __napiModule.exports.JsImageGenerationProviderDefaults
export const ImageModel = __napiModule.exports.ImageModel
export const JsImageModel = __napiModule.exports.JsImageModel
export const ImageProvider = __napiModule.exports.ImageProvider
export const JsImageProvider = __napiModule.exports.JsImageProvider
export const ImageUpscaleProviderDefaults = __napiModule.exports.ImageUpscaleProviderDefaults
export const JsImageUpscaleProviderDefaults = __napiModule.exports.JsImageUpscaleProviderDefaults
export const InferenceChunk = __napiModule.exports.InferenceChunk
export const JsInferenceChunk = __napiModule.exports.JsInferenceChunk
export const InferenceChunkStream = __napiModule.exports.InferenceChunkStream
export const JsInferenceChunkStream = __napiModule.exports.JsInferenceChunkStream
export const InferenceImage = __napiModule.exports.InferenceImage
export const JsInferenceImage = __napiModule.exports.JsInferenceImage
export const InferenceImageSource = __napiModule.exports.InferenceImageSource
export const JsInferenceImageSource = __napiModule.exports.JsInferenceImageSource
export const InferenceResult = __napiModule.exports.InferenceResult
export const JsInferenceResult = __napiModule.exports.JsInferenceResult
export const InferenceToolCall = __napiModule.exports.InferenceToolCall
export const JsInferenceToolCall = __napiModule.exports.JsInferenceToolCall
export const InferenceUsage = __napiModule.exports.InferenceUsage
export const JsInferenceUsage = __napiModule.exports.JsInferenceUsage
export const InMemoryBackend = __napiModule.exports.InMemoryBackend
export const JsInMemoryBackend = __napiModule.exports.JsInMemoryBackend
export const JobHandle = __napiModule.exports.JobHandle
export const JsJobHandleClass = __napiModule.exports.JsJobHandleClass
export const JsonlBackend = __napiModule.exports.JsonlBackend
export const JsJsonlBackend = __napiModule.exports.JsJsonlBackend
export const LangfuseConfig = __napiModule.exports.LangfuseConfig
export const JsLangfuseConfig = __napiModule.exports.JsLangfuseConfig
export const LlamaCppChatMessageInput = __napiModule.exports.LlamaCppChatMessageInput
export const JsLlamaCppChatMessageInput = __napiModule.exports.JsLlamaCppChatMessageInput
export const LlamaCppInferenceChunk = __napiModule.exports.LlamaCppInferenceChunk
export const JsLlamaCppInferenceChunk = __napiModule.exports.JsLlamaCppInferenceChunk
export const LlamaCppInferenceChunkStream = __napiModule.exports.LlamaCppInferenceChunkStream
export const JsLlamaCppInferenceChunkStream = __napiModule.exports.JsLlamaCppInferenceChunkStream
export const LlamaCppInferenceResult = __napiModule.exports.LlamaCppInferenceResult
export const JsLlamaCppInferenceResult = __napiModule.exports.JsLlamaCppInferenceResult
export const LlamaCppInferenceUsage = __napiModule.exports.LlamaCppInferenceUsage
export const JsLlamaCppInferenceUsage = __napiModule.exports.JsLlamaCppInferenceUsage
export const LlamaCppProvider = __napiModule.exports.LlamaCppProvider
export const JsLlamaCppProvider = __napiModule.exports.JsLlamaCppProvider
export const LocalModel = __napiModule.exports.LocalModel
export const JsLocalModel = __napiModule.exports.JsLocalModel
export const Memory = __napiModule.exports.Memory
export const JsMemory = __napiModule.exports.JsMemory
export const MemoryBackend = __napiModule.exports.MemoryBackend
export const JsMemoryBackend = __napiModule.exports.JsMemoryBackend
export const MemoryStore = __napiModule.exports.MemoryStore
export const JsMemoryStore = __napiModule.exports.JsMemoryStore
export const Middleware = __napiModule.exports.Middleware
export const JsMiddleware = __napiModule.exports.JsMiddleware
export const MiddlewareStack = __napiModule.exports.MiddlewareStack
export const JsMiddlewareStack = __napiModule.exports.JsMiddlewareStack
export const MistralProvider = __napiModule.exports.MistralProvider
export const JsMistralProvider = __napiModule.exports.JsMistralProvider
export const MistralRsProvider = __napiModule.exports.MistralRsProvider
export const JsMistralRsProvider = __napiModule.exports.JsMistralRsProvider
export const ModelCache = __napiModule.exports.ModelCache
export const JsModelCache = __napiModule.exports.JsModelCache
export const ModelManager = __napiModule.exports.ModelManager
export const JsModelManager = __napiModule.exports.JsModelManager
export const ModelRegistry = __napiModule.exports.ModelRegistry
export const JsModelRegistry = __napiModule.exports.JsModelRegistry
export const MusicProvider = __napiModule.exports.MusicProvider
export const JsMusicProvider = __napiModule.exports.JsMusicProvider
export const NoopUsageEmitter = __napiModule.exports.NoopUsageEmitter
export const JsNoopUsageEmitter = __napiModule.exports.JsNoopUsageEmitter
export const OpenAiCompatEmbeddingModel = __napiModule.exports.OpenAiCompatEmbeddingModel
export const JsOpenAiCompatEmbeddingModel = __napiModule.exports.JsOpenAiCompatEmbeddingModel
export const OpenAiCompatProvider = __napiModule.exports.OpenAiCompatProvider
export const JsOpenAiCompatProvider = __napiModule.exports.JsOpenAiCompatProvider
export const OpenAiEmbeddingModel = __napiModule.exports.OpenAiEmbeddingModel
export const JsOpenAiEmbeddingModel = __napiModule.exports.JsOpenAiEmbeddingModel
export const OpenAiProvider = __napiModule.exports.OpenAiProvider
export const JsOpenAiProvider = __napiModule.exports.JsOpenAiProvider
export const OpenRouterProvider = __napiModule.exports.OpenRouterProvider
export const JsOpenRouterProvider = __napiModule.exports.JsOpenRouterProvider
export const ParallelStage = __napiModule.exports.ParallelStage
export const JsParallelStage = __napiModule.exports.JsParallelStage
export const ParallelSubWorkflowsStep = __napiModule.exports.ParallelSubWorkflowsStep
export const JsParallelSubWorkflowsStep = __napiModule.exports.JsParallelSubWorkflowsStep
export const PeerClient = __napiModule.exports.PeerClient
export const JsPeerClient = __napiModule.exports.JsPeerClient
export const PerplexityProvider = __napiModule.exports.PerplexityProvider
export const JsPerplexityProvider = __napiModule.exports.JsPerplexityProvider
export const Pipeline = __napiModule.exports.Pipeline
export const JsPipeline = __napiModule.exports.JsPipeline
export const PipelineBuilder = __napiModule.exports.PipelineBuilder
export const JsPipelineBuilder = __napiModule.exports.JsPipelineBuilder
export const PipelineEvent = __napiModule.exports.PipelineEvent
export const JsPipelineEvent = __napiModule.exports.JsPipelineEvent
export const PipelineHandler = __napiModule.exports.PipelineHandler
export const JsPipelineHandler = __napiModule.exports.JsPipelineHandler
export const PipelineResult = __napiModule.exports.PipelineResult
export const JsPipelineResult = __napiModule.exports.JsPipelineResult
export const PipelineSnapshot = __napiModule.exports.PipelineSnapshot
export const JsPipelineSnapshot = __napiModule.exports.JsPipelineSnapshot
export const PiperProvider = __napiModule.exports.PiperProvider
export const JsPiperProvider = __napiModule.exports.JsPiperProvider
export const ProgressCallback = __napiModule.exports.ProgressCallback
export const JsProgressCallback = __napiModule.exports.JsProgressCallback
export const PromptFile = __napiModule.exports.PromptFile
export const JsPromptFile = __napiModule.exports.JsPromptFile
export const PromptRegistry = __napiModule.exports.PromptRegistry
export const JsPromptRegistry = __napiModule.exports.JsPromptRegistry
export const PromptTemplate = __napiModule.exports.PromptTemplate
export const JsPromptTemplate = __napiModule.exports.JsPromptTemplate
export const ReasoningTrace = __napiModule.exports.ReasoningTrace
export const JsReasoningTraceClass = __napiModule.exports.JsReasoningTraceClass
export const RedbCheckpointStore = __napiModule.exports.RedbCheckpointStore
export const JsRedbCheckpointStore = __napiModule.exports.JsRedbCheckpointStore
export const RegistryKey = __napiModule.exports.RegistryKey
export const JsRegistryKey = __napiModule.exports.JsRegistryKey
export const RequestTiming = __napiModule.exports.RequestTiming
export const JsRequestTimingClass = __napiModule.exports.JsRequestTimingClass
export const RetryCompletionModel = __napiModule.exports.RetryCompletionModel
export const JsRetryCompletionModel = __napiModule.exports.JsRetryCompletionModel
export const RetryMemoryBackend = __napiModule.exports.RetryMemoryBackend
export const JsRetryMemoryBackend = __napiModule.exports.JsRetryMemoryBackend
export const RetryMiddleware = __napiModule.exports.RetryMiddleware
export const JsRetryMiddleware = __napiModule.exports.JsRetryMiddleware
export const SessionNamespace = __napiModule.exports.SessionNamespace
export const JsSessionNamespace = __napiModule.exports.JsSessionNamespace
export const SessionRefRegistry = __napiModule.exports.SessionRefRegistry
export const JsSessionRefRegistry = __napiModule.exports.JsSessionRefRegistry
export const Stage = __napiModule.exports.Stage
export const JsStage = __napiModule.exports.JsStage
export const StageResult = __napiModule.exports.StageResult
export const JsStageResult = __napiModule.exports.JsStageResult
export const StartEvent = __napiModule.exports.StartEvent
export const JsStartEventClass = __napiModule.exports.JsStartEventClass
export const StateNamespace = __napiModule.exports.StateNamespace
export const JsStateNamespace = __napiModule.exports.JsStateNamespace
export const StateValue = __napiModule.exports.StateValue
export const JsStateValue = __napiModule.exports.JsStateValue
export const StepDeserializerRegistry = __napiModule.exports.StepDeserializerRegistry
export const JsStepDeserializerRegistry = __napiModule.exports.JsStepDeserializerRegistry
export const StepOutput = __napiModule.exports.StepOutput
export const JsStepOutput = __napiModule.exports.JsStepOutput
export const StepRegistration = __napiModule.exports.StepRegistration
export const JsStepRegistration = __napiModule.exports.JsStepRegistration
export const StopEvent = __napiModule.exports.StopEvent
export const JsStopEventClass = __napiModule.exports.JsStopEventClass
export const StructuredOutput = __napiModule.exports.StructuredOutput
export const JsStructuredOutput = __napiModule.exports.JsStructuredOutput
export const SubWorkflowStep = __napiModule.exports.SubWorkflowStep
export const JsSubWorkflowStep = __napiModule.exports.JsSubWorkflowStep
export const ThreeDProvider = __napiModule.exports.ThreeDProvider
export const JsThreeDProvider = __napiModule.exports.JsThreeDProvider
export const ThreeDProviderDefaults = __napiModule.exports.ThreeDProviderDefaults
export const JsThreeDProviderDefaults = __napiModule.exports.JsThreeDProviderDefaults
export const TiktokenCounter = __napiModule.exports.TiktokenCounter
export const JsTiktokenCounter = __napiModule.exports.JsTiktokenCounter
export const TogetherProvider = __napiModule.exports.TogetherProvider
export const JsTogetherProvider = __napiModule.exports.JsTogetherProvider
export const TokenCounter = __napiModule.exports.TokenCounter
export const JsTokenCounter = __napiModule.exports.JsTokenCounter
export const TokenUsage = __napiModule.exports.TokenUsage
export const JsTokenUsageClass = __napiModule.exports.JsTokenUsageClass
export const Tool = __napiModule.exports.Tool
export const JsTool = __napiModule.exports.JsTool
export const ToolCall = __napiModule.exports.ToolCall
export const JsToolCallClass = __napiModule.exports.JsToolCallClass
export const ToolDefinition = __napiModule.exports.ToolDefinition
export const JsToolDefinitionClass = __napiModule.exports.JsToolDefinitionClass
export const TractEmbedModel = __napiModule.exports.TractEmbedModel
export const JsTractEmbedModel = __napiModule.exports.JsTractEmbedModel
export const Transcription = __napiModule.exports.Transcription
export const JsTranscription = __napiModule.exports.JsTranscription
export const TranscriptionProviderDefaults = __napiModule.exports.TranscriptionProviderDefaults
export const JsTranscriptionProviderDefaults = __napiModule.exports.JsTranscriptionProviderDefaults
export const TTSProvider = __napiModule.exports.TTSProvider
export const JsTTSProvider = __napiModule.exports.JsTTSProvider
export const TypedTool = __napiModule.exports.TypedTool
export const JsTypedTool = __napiModule.exports.JsTypedTool
export const UpstashBackend = __napiModule.exports.UpstashBackend
export const JsUpstashBackend = __napiModule.exports.JsUpstashBackend
export const UsageEmitter = __napiModule.exports.UsageEmitter
export const JsUsageEmitter = __napiModule.exports.JsUsageEmitter
export const UsageRecordingCompletionModel = __napiModule.exports.UsageRecordingCompletionModel
export const JsUsageRecordingCompletionModel = __napiModule.exports.JsUsageRecordingCompletionModel
export const UsageRecordingEmbeddingModel = __napiModule.exports.UsageRecordingEmbeddingModel
export const JsUsageRecordingEmbeddingModel = __napiModule.exports.JsUsageRecordingEmbeddingModel
export const ValkeyBackend = __napiModule.exports.ValkeyBackend
export const JsValkeyBackend = __napiModule.exports.JsValkeyBackend
export const ValkeyCheckpointStore = __napiModule.exports.ValkeyCheckpointStore
export const JsValkeyCheckpointStore = __napiModule.exports.JsValkeyCheckpointStore
export const VideoProvider = __napiModule.exports.VideoProvider
export const JsVideoProvider = __napiModule.exports.JsVideoProvider
export const VideoProviderDefaults = __napiModule.exports.VideoProviderDefaults
export const JsVideoProviderDefaults = __napiModule.exports.JsVideoProviderDefaults
export const VoiceCloningProviderDefaults = __napiModule.exports.VoiceCloningProviderDefaults
export const JsVoiceCloningProviderDefaults = __napiModule.exports.JsVoiceCloningProviderDefaults
export const VoiceProvider = __napiModule.exports.VoiceProvider
export const JsVoiceProvider = __napiModule.exports.JsVoiceProvider
export const WhisperCppProvider = __napiModule.exports.WhisperCppProvider
export const JsWhisperCppProvider = __napiModule.exports.JsWhisperCppProvider
export const Workflow = __napiModule.exports.Workflow
export const JsWorkflow = __napiModule.exports.JsWorkflow
export const WorkflowBuilder = __napiModule.exports.WorkflowBuilder
export const JsWorkflowBuilder = __napiModule.exports.JsWorkflowBuilder
export const WorkflowCheckpoint = __napiModule.exports.WorkflowCheckpoint
export const JsWorkflowCheckpoint = __napiModule.exports.JsWorkflowCheckpoint
export const WorkflowHandler = __napiModule.exports.WorkflowHandler
export const JsWorkflowHandler = __napiModule.exports.JsWorkflowHandler
export const WorkflowHistory = __napiModule.exports.WorkflowHistory
export const JsWorkflowHistory = __napiModule.exports.JsWorkflowHistory
export const WorkflowSnapshot = __napiModule.exports.WorkflowSnapshot
export const JsWorkflowSnapshot = __napiModule.exports.JsWorkflowSnapshot
export const XaiProvider = __napiModule.exports.XaiProvider
export const JsXaiProvider = __napiModule.exports.JsXaiProvider
export const addUsageToTokenUsage = __napiModule.exports.addUsageToTokenUsage
export const audioInput = __napiModule.exports.audioInput
export const cadInput = __napiModule.exports.cadInput
export const ChatRole = __napiModule.exports.ChatRole
export const JsChatRole = __napiModule.exports.JsChatRole
export const completeBatch = __napiModule.exports.completeBatch
export const completeBatchConfig = __napiModule.exports.completeBatchConfig
export const computeAudioCost = __napiModule.exports.computeAudioCost
export const computeElidSimilarity = __napiModule.exports.computeElidSimilarity
export const computeEmbeddingSimhashSimilarity = __napiModule.exports.computeEmbeddingSimhashSimilarity
export const computeImageCost = __napiModule.exports.computeImageCost
export const computeTextSimhashSimilarity = __napiModule.exports.computeTextSimhashSimilarity
export const computeVideoCost = __napiModule.exports.computeVideoCost
export const countMessageTokens = __napiModule.exports.countMessageTokens
export const DEFAULT_MODEL_PRICING_URL_BASE = __napiModule.exports.DEFAULT_MODEL_PRICING_URL_BASE
export const DEFAULT_PRICING_URL = __napiModule.exports.DEFAULT_PRICING_URL
export const defaultHttpClientConfig = __napiModule.exports.defaultHttpClientConfig
export const envVarForProvider = __napiModule.exports.envVarForProvider
export const estimateTokens = __napiModule.exports.estimateTokens
export const extractInlineArtifacts = __napiModule.exports.extractInlineArtifacts
export const fetchOneDefault = __napiModule.exports.fetchOneDefault
export const fetchOneDefaultWithUrlBase = __napiModule.exports.fetchOneDefaultWithUrlBase
export const fileInput = __napiModule.exports.fileInput
export const FINISH_WORKFLOW_TOOL_NAME = __napiModule.exports.FINISH_WORKFLOW_TOOL_NAME
export const finishWorkflowTool = __napiModule.exports.finishWorkflowTool
export const finishWorkflowToolDef = __napiModule.exports.finishWorkflowToolDef
export const formatProviderHttpTail = __napiModule.exports.formatProviderHttpTail
export const getContextWindow = __napiModule.exports.getContextWindow
export const HistoryEventKindTag = __napiModule.exports.HistoryEventKindTag
export const JsHistoryEventKindTag = __napiModule.exports.JsHistoryEventKindTag
export const imageInput = __napiModule.exports.imageInput
export const initLangfuse = __napiModule.exports.initLangfuse
export const initOtlp = __napiModule.exports.initOtlp
export const initPrometheus = __napiModule.exports.initPrometheus
export const internEventType = __napiModule.exports.internEventType
export const JoinStrategy = __napiModule.exports.JoinStrategy
export const JsJoinStrategy = __napiModule.exports.JsJoinStrategy
export const JsAuthMethod = __napiModule.exports.JsAuthMethod
export const JsCacheStrategy = __napiModule.exports.JsCacheStrategy
export const JsContentKind = __napiModule.exports.JsContentKind
export const JsDiffusionScheduler = __napiModule.exports.JsDiffusionScheduler
export const JsFalLlmEndpointKind = __napiModule.exports.JsFalLlmEndpointKind
export const JsJobStatus = __napiModule.exports.JsJobStatus
export const JsRole = __napiModule.exports.JsRole
export const JsWhisperModel = __napiModule.exports.JsWhisperModel
export const LlamaCppChatRole = __napiModule.exports.LlamaCppChatRole
export const JsLlamaCppChatRole = __napiModule.exports.JsLlamaCppChatRole
export const loadClientTls = __napiModule.exports.loadClientTls
export const loadServerTls = __napiModule.exports.loadServerTls
export const lookupPricing = __napiModule.exports.lookupPricing
export const lookupStepBuilder = __napiModule.exports.lookupStepBuilder
export const Modality = __napiModule.exports.Modality
export const JsModality = __napiModule.exports.JsModality
export const newRetryStack = __napiModule.exports.newRetryStack
export const newUsageEvent = __napiModule.exports.newUsageEvent
export const PauseReason = __napiModule.exports.PauseReason
export const JsPauseReason = __napiModule.exports.JsPauseReason
export const peerEnvelopeVersion = __napiModule.exports.peerEnvelopeVersion
export const peerTokenEnv = __napiModule.exports.peerTokenEnv
export const ProgressKind = __napiModule.exports.ProgressKind
export const JsProgressKind = __napiModule.exports.JsProgressKind
export const providerEnvVars = __napiModule.exports.providerEnvVars
export const ProviderId = __napiModule.exports.ProviderId
export const JsProviderId = __napiModule.exports.JsProviderId
export const RefLifetime = __napiModule.exports.RefLifetime
export const JsRefLifetime = __napiModule.exports.JsRefLifetime
export const refreshDefault = __napiModule.exports.refreshDefault
export const refreshDefaultWithUrl = __napiModule.exports.refreshDefaultWithUrl
export const refreshPricing = __napiModule.exports.refreshPricing
export const registeredStepIds = __napiModule.exports.registeredStepIds
export const registerEventDeserializer = __napiModule.exports.registerEventDeserializer
export const registerFromModelInfo = __napiModule.exports.registerFromModelInfo
export const registerPricing = __napiModule.exports.registerPricing
export const registerStepBuilder = __napiModule.exports.registerStepBuilder
export const resolveApiKey = __napiModule.exports.resolveApiKey
export const resolvePeerToken = __napiModule.exports.resolvePeerToken
export const resolveRetryStack = __napiModule.exports.resolveRetryStack
export const runAgent = __napiModule.exports.runAgent
export const runAgentWithCallback = __napiModule.exports.runAgentWithCallback
export const SessionPausePolicy = __napiModule.exports.SessionPausePolicy
export const JsSessionPausePolicy = __napiModule.exports.JsSessionPausePolicy
export const simhashFromHex = __napiModule.exports.simhashFromHex
export const simhashToHex = __napiModule.exports.simhashToHex
export const StateValueKind = __napiModule.exports.StateValueKind
export const JsStateValueKind = __napiModule.exports.JsStateValueKind
export const StepOutputKind = __napiModule.exports.StepOutputKind
export const JsStepOutputKind = __napiModule.exports.JsStepOutputKind
export const TemplateRole = __napiModule.exports.TemplateRole
export const JsTemplateRole = __napiModule.exports.JsTemplateRole
export const threeDInput = __napiModule.exports.threeDInput
export const tryDeserializeEvent = __napiModule.exports.tryDeserializeEvent
export const typedToolSimple = __napiModule.exports.typedToolSimple
export const unlimitedHttpClientConfig = __napiModule.exports.unlimitedHttpClientConfig
export const version = __napiModule.exports.version
export const videoInput = __napiModule.exports.videoInput
