/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'blazen.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'blazen.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = require.resolve('@blazen-dev/blazen-wasm32-wasi/blazen.wasm32-wasi.wasm')
  } catch {
    throw new Error('Cannot find blazen.wasm32-wasi.wasm file, and @blazen-dev/blazen-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.ActiveWorkflowSnapshot = __napiModule.exports.ActiveWorkflowSnapshot
module.exports.JsActiveWorkflowSnapshot = __napiModule.exports.JsActiveWorkflowSnapshot
module.exports.AgentResult = __napiModule.exports.AgentResult
module.exports.JsAgentResult = __napiModule.exports.JsAgentResult
module.exports.AnthropicProvider = __napiModule.exports.AnthropicProvider
module.exports.JsAnthropicProvider = __napiModule.exports.JsAnthropicProvider
module.exports.AzureOpenAiProvider = __napiModule.exports.AzureOpenAiProvider
module.exports.JsAzureOpenAiProvider = __napiModule.exports.JsAzureOpenAiProvider
module.exports.BackgroundRemovalProvider = __napiModule.exports.BackgroundRemovalProvider
module.exports.JsBackgroundRemovalProvider = __napiModule.exports.JsBackgroundRemovalProvider
module.exports.BatchConfig = __napiModule.exports.BatchConfig
module.exports.JsBatchConfig = __napiModule.exports.JsBatchConfig
module.exports.BatchResult = __napiModule.exports.BatchResult
module.exports.JsBatchResult = __napiModule.exports.JsBatchResult
module.exports.BedrockProvider = __napiModule.exports.BedrockProvider
module.exports.JsBedrockProvider = __napiModule.exports.JsBedrockProvider
module.exports.BlazenPeerClient = __napiModule.exports.BlazenPeerClient
module.exports.JsBlazenPeerClient = __napiModule.exports.JsBlazenPeerClient
module.exports.BlazenPeerServer = __napiModule.exports.BlazenPeerServer
module.exports.JsBlazenPeerServer = __napiModule.exports.JsBlazenPeerServer
module.exports.BytesWrapper = __napiModule.exports.BytesWrapper
module.exports.JsBytesWrapper = __napiModule.exports.JsBytesWrapper
module.exports.CachedCompletionModel = __napiModule.exports.CachedCompletionModel
module.exports.JsCachedCompletionModel = __napiModule.exports.JsCachedCompletionModel
module.exports.CacheMiddleware = __napiModule.exports.CacheMiddleware
module.exports.JsCacheMiddleware = __napiModule.exports.JsCacheMiddleware
module.exports.CandleEmbedProvider = __napiModule.exports.CandleEmbedProvider
module.exports.JsCandleEmbedProvider = __napiModule.exports.JsCandleEmbedProvider
module.exports.CandleInferenceResult = __napiModule.exports.CandleInferenceResult
module.exports.JsCandleInferenceResult = __napiModule.exports.JsCandleInferenceResult
module.exports.CandleLlmProvider = __napiModule.exports.CandleLlmProvider
module.exports.JsCandleLlmProvider = __napiModule.exports.JsCandleLlmProvider
module.exports.ChatMessage = __napiModule.exports.ChatMessage
module.exports.JsChatMessage = __napiModule.exports.JsChatMessage
module.exports.ChatMessageInput = __napiModule.exports.ChatMessageInput
module.exports.JsChatMessageInput = __napiModule.exports.JsChatMessageInput
module.exports.ChatWindow = __napiModule.exports.ChatWindow
module.exports.JsChatWindow = __napiModule.exports.JsChatWindow
module.exports.CheckpointStore = __napiModule.exports.CheckpointStore
module.exports.JsCheckpointStore = __napiModule.exports.JsCheckpointStore
module.exports.Citation = __napiModule.exports.Citation
module.exports.JsCitationClass = __napiModule.exports.JsCitationClass
module.exports.CohereProvider = __napiModule.exports.CohereProvider
module.exports.JsCohereProvider = __napiModule.exports.JsCohereProvider
module.exports.CompletionModel = __napiModule.exports.CompletionModel
module.exports.JsCompletionModel = __napiModule.exports.JsCompletionModel
module.exports.ContentStore = __napiModule.exports.ContentStore
module.exports.JsContentStore = __napiModule.exports.JsContentStore
module.exports.Context = __napiModule.exports.Context
module.exports.JsContext = __napiModule.exports.JsContext
module.exports.CustomProvider = __napiModule.exports.CustomProvider
module.exports.JsCustomProvider = __napiModule.exports.JsCustomProvider
module.exports.DeepSeekProvider = __napiModule.exports.DeepSeekProvider
module.exports.JsDeepSeekProvider = __napiModule.exports.JsDeepSeekProvider
module.exports.DiffusionProvider = __napiModule.exports.DiffusionProvider
module.exports.JsDiffusionProvider = __napiModule.exports.JsDiffusionProvider
module.exports.DynamicEvent = __napiModule.exports.DynamicEvent
module.exports.JsDynamicEvent = __napiModule.exports.JsDynamicEvent
module.exports.EmbeddingModel = __napiModule.exports.EmbeddingModel
module.exports.JsEmbeddingModel = __napiModule.exports.JsEmbeddingModel
module.exports.EmbedProvider = __napiModule.exports.EmbedProvider
module.exports.JsEmbedProvider = __napiModule.exports.JsEmbedProvider
module.exports.EstimateCounter = __napiModule.exports.EstimateCounter
module.exports.JsEstimateCounter = __napiModule.exports.JsEstimateCounter
module.exports.FalEmbeddingModel = __napiModule.exports.FalEmbeddingModel
module.exports.JsFalEmbeddingModel = __napiModule.exports.JsFalEmbeddingModel
module.exports.FallbackModel = __napiModule.exports.FallbackModel
module.exports.JsFallbackModel = __napiModule.exports.JsFallbackModel
module.exports.FalProvider = __napiModule.exports.FalProvider
module.exports.JsFalProvider = __napiModule.exports.JsFalProvider
module.exports.FastEmbedModel = __napiModule.exports.FastEmbedModel
module.exports.JsFastEmbedModel = __napiModule.exports.JsFastEmbedModel
module.exports.FireworksProvider = __napiModule.exports.FireworksProvider
module.exports.JsFireworksProvider = __napiModule.exports.JsFireworksProvider
module.exports.GeminiProvider = __napiModule.exports.GeminiProvider
module.exports.JsGeminiProvider = __napiModule.exports.JsGeminiProvider
module.exports.GroqProvider = __napiModule.exports.GroqProvider
module.exports.JsGroqProvider = __napiModule.exports.JsGroqProvider
module.exports.HistoryEventKind = __napiModule.exports.HistoryEventKind
module.exports.JsHistoryEventKind = __napiModule.exports.JsHistoryEventKind
module.exports.HostDispatch = __napiModule.exports.HostDispatch
module.exports.JsHostDispatch = __napiModule.exports.JsHostDispatch
module.exports.HttpClient = __napiModule.exports.HttpClient
module.exports.JsHttpClient = __napiModule.exports.JsHttpClient
module.exports.HttpPeerClient = __napiModule.exports.HttpPeerClient
module.exports.JsHttpPeerClient = __napiModule.exports.JsHttpPeerClient
module.exports.ImageModel = __napiModule.exports.ImageModel
module.exports.JsImageModel = __napiModule.exports.JsImageModel
module.exports.ImageProvider = __napiModule.exports.ImageProvider
module.exports.JsImageProvider = __napiModule.exports.JsImageProvider
module.exports.InferenceChunk = __napiModule.exports.InferenceChunk
module.exports.JsInferenceChunk = __napiModule.exports.JsInferenceChunk
module.exports.InferenceChunkStream = __napiModule.exports.InferenceChunkStream
module.exports.JsInferenceChunkStream = __napiModule.exports.JsInferenceChunkStream
module.exports.InferenceImage = __napiModule.exports.InferenceImage
module.exports.JsInferenceImage = __napiModule.exports.JsInferenceImage
module.exports.InferenceImageSource = __napiModule.exports.InferenceImageSource
module.exports.JsInferenceImageSource = __napiModule.exports.JsInferenceImageSource
module.exports.InferenceResult = __napiModule.exports.InferenceResult
module.exports.JsInferenceResult = __napiModule.exports.JsInferenceResult
module.exports.InferenceToolCall = __napiModule.exports.InferenceToolCall
module.exports.JsInferenceToolCall = __napiModule.exports.JsInferenceToolCall
module.exports.InferenceUsage = __napiModule.exports.InferenceUsage
module.exports.JsInferenceUsage = __napiModule.exports.JsInferenceUsage
module.exports.InMemoryBackend = __napiModule.exports.InMemoryBackend
module.exports.JsInMemoryBackend = __napiModule.exports.JsInMemoryBackend
module.exports.JobHandle = __napiModule.exports.JobHandle
module.exports.JsJobHandleClass = __napiModule.exports.JsJobHandleClass
module.exports.JsonlBackend = __napiModule.exports.JsonlBackend
module.exports.JsJsonlBackend = __napiModule.exports.JsJsonlBackend
module.exports.LangfuseConfig = __napiModule.exports.LangfuseConfig
module.exports.JsLangfuseConfig = __napiModule.exports.JsLangfuseConfig
module.exports.LlamaCppChatMessageInput = __napiModule.exports.LlamaCppChatMessageInput
module.exports.JsLlamaCppChatMessageInput = __napiModule.exports.JsLlamaCppChatMessageInput
module.exports.LlamaCppInferenceChunk = __napiModule.exports.LlamaCppInferenceChunk
module.exports.JsLlamaCppInferenceChunk = __napiModule.exports.JsLlamaCppInferenceChunk
module.exports.LlamaCppInferenceChunkStream = __napiModule.exports.LlamaCppInferenceChunkStream
module.exports.JsLlamaCppInferenceChunkStream = __napiModule.exports.JsLlamaCppInferenceChunkStream
module.exports.LlamaCppInferenceResult = __napiModule.exports.LlamaCppInferenceResult
module.exports.JsLlamaCppInferenceResult = __napiModule.exports.JsLlamaCppInferenceResult
module.exports.LlamaCppInferenceUsage = __napiModule.exports.LlamaCppInferenceUsage
module.exports.JsLlamaCppInferenceUsage = __napiModule.exports.JsLlamaCppInferenceUsage
module.exports.LlamaCppProvider = __napiModule.exports.LlamaCppProvider
module.exports.JsLlamaCppProvider = __napiModule.exports.JsLlamaCppProvider
module.exports.LocalModel = __napiModule.exports.LocalModel
module.exports.JsLocalModel = __napiModule.exports.JsLocalModel
module.exports.Memory = __napiModule.exports.Memory
module.exports.JsMemory = __napiModule.exports.JsMemory
module.exports.MemoryBackend = __napiModule.exports.MemoryBackend
module.exports.JsMemoryBackend = __napiModule.exports.JsMemoryBackend
module.exports.MemoryStore = __napiModule.exports.MemoryStore
module.exports.JsMemoryStore = __napiModule.exports.JsMemoryStore
module.exports.Middleware = __napiModule.exports.Middleware
module.exports.JsMiddleware = __napiModule.exports.JsMiddleware
module.exports.MiddlewareStack = __napiModule.exports.MiddlewareStack
module.exports.JsMiddlewareStack = __napiModule.exports.JsMiddlewareStack
module.exports.MistralProvider = __napiModule.exports.MistralProvider
module.exports.JsMistralProvider = __napiModule.exports.JsMistralProvider
module.exports.MistralRsProvider = __napiModule.exports.MistralRsProvider
module.exports.JsMistralRsProvider = __napiModule.exports.JsMistralRsProvider
module.exports.ModelCache = __napiModule.exports.ModelCache
module.exports.JsModelCache = __napiModule.exports.JsModelCache
module.exports.ModelManager = __napiModule.exports.ModelManager
module.exports.JsModelManager = __napiModule.exports.JsModelManager
module.exports.ModelRegistry = __napiModule.exports.ModelRegistry
module.exports.JsModelRegistry = __napiModule.exports.JsModelRegistry
module.exports.MusicProvider = __napiModule.exports.MusicProvider
module.exports.JsMusicProvider = __napiModule.exports.JsMusicProvider
module.exports.NoopUsageEmitter = __napiModule.exports.NoopUsageEmitter
module.exports.JsNoopUsageEmitter = __napiModule.exports.JsNoopUsageEmitter
module.exports.OpenAiCompatEmbeddingModel = __napiModule.exports.OpenAiCompatEmbeddingModel
module.exports.JsOpenAiCompatEmbeddingModel = __napiModule.exports.JsOpenAiCompatEmbeddingModel
module.exports.OpenAiCompatProvider = __napiModule.exports.OpenAiCompatProvider
module.exports.JsOpenAiCompatProvider = __napiModule.exports.JsOpenAiCompatProvider
module.exports.OpenAiEmbeddingModel = __napiModule.exports.OpenAiEmbeddingModel
module.exports.JsOpenAiEmbeddingModel = __napiModule.exports.JsOpenAiEmbeddingModel
module.exports.OpenAiProvider = __napiModule.exports.OpenAiProvider
module.exports.JsOpenAiProvider = __napiModule.exports.JsOpenAiProvider
module.exports.OpenRouterProvider = __napiModule.exports.OpenRouterProvider
module.exports.JsOpenRouterProvider = __napiModule.exports.JsOpenRouterProvider
module.exports.ParallelStage = __napiModule.exports.ParallelStage
module.exports.JsParallelStage = __napiModule.exports.JsParallelStage
module.exports.ParallelSubWorkflowsStep = __napiModule.exports.ParallelSubWorkflowsStep
module.exports.JsParallelSubWorkflowsStep = __napiModule.exports.JsParallelSubWorkflowsStep
module.exports.PeerClient = __napiModule.exports.PeerClient
module.exports.JsPeerClient = __napiModule.exports.JsPeerClient
module.exports.PerplexityProvider = __napiModule.exports.PerplexityProvider
module.exports.JsPerplexityProvider = __napiModule.exports.JsPerplexityProvider
module.exports.Pipeline = __napiModule.exports.Pipeline
module.exports.JsPipeline = __napiModule.exports.JsPipeline
module.exports.PipelineBuilder = __napiModule.exports.PipelineBuilder
module.exports.JsPipelineBuilder = __napiModule.exports.JsPipelineBuilder
module.exports.PipelineEvent = __napiModule.exports.PipelineEvent
module.exports.JsPipelineEvent = __napiModule.exports.JsPipelineEvent
module.exports.PipelineHandler = __napiModule.exports.PipelineHandler
module.exports.JsPipelineHandler = __napiModule.exports.JsPipelineHandler
module.exports.PipelineResult = __napiModule.exports.PipelineResult
module.exports.JsPipelineResult = __napiModule.exports.JsPipelineResult
module.exports.PipelineSnapshot = __napiModule.exports.PipelineSnapshot
module.exports.JsPipelineSnapshot = __napiModule.exports.JsPipelineSnapshot
module.exports.PiperProvider = __napiModule.exports.PiperProvider
module.exports.JsPiperProvider = __napiModule.exports.JsPiperProvider
module.exports.ProgressCallback = __napiModule.exports.ProgressCallback
module.exports.JsProgressCallback = __napiModule.exports.JsProgressCallback
module.exports.PromptFile = __napiModule.exports.PromptFile
module.exports.JsPromptFile = __napiModule.exports.JsPromptFile
module.exports.PromptRegistry = __napiModule.exports.PromptRegistry
module.exports.JsPromptRegistry = __napiModule.exports.JsPromptRegistry
module.exports.PromptTemplate = __napiModule.exports.PromptTemplate
module.exports.JsPromptTemplate = __napiModule.exports.JsPromptTemplate
module.exports.ReasoningTrace = __napiModule.exports.ReasoningTrace
module.exports.JsReasoningTraceClass = __napiModule.exports.JsReasoningTraceClass
module.exports.RedbCheckpointStore = __napiModule.exports.RedbCheckpointStore
module.exports.JsRedbCheckpointStore = __napiModule.exports.JsRedbCheckpointStore
module.exports.RegistryKey = __napiModule.exports.RegistryKey
module.exports.JsRegistryKey = __napiModule.exports.JsRegistryKey
module.exports.RequestTiming = __napiModule.exports.RequestTiming
module.exports.JsRequestTimingClass = __napiModule.exports.JsRequestTimingClass
module.exports.RetryCompletionModel = __napiModule.exports.RetryCompletionModel
module.exports.JsRetryCompletionModel = __napiModule.exports.JsRetryCompletionModel
module.exports.RetryMemoryBackend = __napiModule.exports.RetryMemoryBackend
module.exports.JsRetryMemoryBackend = __napiModule.exports.JsRetryMemoryBackend
module.exports.RetryMiddleware = __napiModule.exports.RetryMiddleware
module.exports.JsRetryMiddleware = __napiModule.exports.JsRetryMiddleware
module.exports.SessionNamespace = __napiModule.exports.SessionNamespace
module.exports.JsSessionNamespace = __napiModule.exports.JsSessionNamespace
module.exports.SessionRefRegistry = __napiModule.exports.SessionRefRegistry
module.exports.JsSessionRefRegistry = __napiModule.exports.JsSessionRefRegistry
module.exports.Stage = __napiModule.exports.Stage
module.exports.JsStage = __napiModule.exports.JsStage
module.exports.StageResult = __napiModule.exports.StageResult
module.exports.JsStageResult = __napiModule.exports.JsStageResult
module.exports.StartEvent = __napiModule.exports.StartEvent
module.exports.JsStartEventClass = __napiModule.exports.JsStartEventClass
module.exports.StateNamespace = __napiModule.exports.StateNamespace
module.exports.JsStateNamespace = __napiModule.exports.JsStateNamespace
module.exports.StateValue = __napiModule.exports.StateValue
module.exports.JsStateValue = __napiModule.exports.JsStateValue
module.exports.StepDeserializerRegistry = __napiModule.exports.StepDeserializerRegistry
module.exports.JsStepDeserializerRegistry = __napiModule.exports.JsStepDeserializerRegistry
module.exports.StepOutput = __napiModule.exports.StepOutput
module.exports.JsStepOutput = __napiModule.exports.JsStepOutput
module.exports.StepRegistration = __napiModule.exports.StepRegistration
module.exports.JsStepRegistration = __napiModule.exports.JsStepRegistration
module.exports.StopEvent = __napiModule.exports.StopEvent
module.exports.JsStopEventClass = __napiModule.exports.JsStopEventClass
module.exports.StructuredOutput = __napiModule.exports.StructuredOutput
module.exports.JsStructuredOutput = __napiModule.exports.JsStructuredOutput
module.exports.SubWorkflowStep = __napiModule.exports.SubWorkflowStep
module.exports.JsSubWorkflowStep = __napiModule.exports.JsSubWorkflowStep
module.exports.ThreeDProvider = __napiModule.exports.ThreeDProvider
module.exports.JsThreeDProvider = __napiModule.exports.JsThreeDProvider
module.exports.TiktokenCounter = __napiModule.exports.TiktokenCounter
module.exports.JsTiktokenCounter = __napiModule.exports.JsTiktokenCounter
module.exports.TogetherProvider = __napiModule.exports.TogetherProvider
module.exports.JsTogetherProvider = __napiModule.exports.JsTogetherProvider
module.exports.TokenCounter = __napiModule.exports.TokenCounter
module.exports.JsTokenCounter = __napiModule.exports.JsTokenCounter
module.exports.TokenUsage = __napiModule.exports.TokenUsage
module.exports.JsTokenUsageClass = __napiModule.exports.JsTokenUsageClass
module.exports.Tool = __napiModule.exports.Tool
module.exports.JsTool = __napiModule.exports.JsTool
module.exports.ToolCall = __napiModule.exports.ToolCall
module.exports.JsToolCallClass = __napiModule.exports.JsToolCallClass
module.exports.ToolDefinition = __napiModule.exports.ToolDefinition
module.exports.JsToolDefinitionClass = __napiModule.exports.JsToolDefinitionClass
module.exports.TractEmbedModel = __napiModule.exports.TractEmbedModel
module.exports.JsTractEmbedModel = __napiModule.exports.JsTractEmbedModel
module.exports.Transcription = __napiModule.exports.Transcription
module.exports.JsTranscription = __napiModule.exports.JsTranscription
module.exports.TTSProvider = __napiModule.exports.TTSProvider
module.exports.JsTTSProvider = __napiModule.exports.JsTTSProvider
module.exports.TypedTool = __napiModule.exports.TypedTool
module.exports.JsTypedTool = __napiModule.exports.JsTypedTool
module.exports.UsageEmitter = __napiModule.exports.UsageEmitter
module.exports.JsUsageEmitter = __napiModule.exports.JsUsageEmitter
module.exports.UsageRecordingCompletionModel = __napiModule.exports.UsageRecordingCompletionModel
module.exports.JsUsageRecordingCompletionModel = __napiModule.exports.JsUsageRecordingCompletionModel
module.exports.UsageRecordingEmbeddingModel = __napiModule.exports.UsageRecordingEmbeddingModel
module.exports.JsUsageRecordingEmbeddingModel = __napiModule.exports.JsUsageRecordingEmbeddingModel
module.exports.ValkeyBackend = __napiModule.exports.ValkeyBackend
module.exports.JsValkeyBackend = __napiModule.exports.JsValkeyBackend
module.exports.ValkeyCheckpointStore = __napiModule.exports.ValkeyCheckpointStore
module.exports.JsValkeyCheckpointStore = __napiModule.exports.JsValkeyCheckpointStore
module.exports.VideoProvider = __napiModule.exports.VideoProvider
module.exports.JsVideoProvider = __napiModule.exports.JsVideoProvider
module.exports.VoiceProvider = __napiModule.exports.VoiceProvider
module.exports.JsVoiceProvider = __napiModule.exports.JsVoiceProvider
module.exports.WhisperCppProvider = __napiModule.exports.WhisperCppProvider
module.exports.JsWhisperCppProvider = __napiModule.exports.JsWhisperCppProvider
module.exports.Workflow = __napiModule.exports.Workflow
module.exports.JsWorkflow = __napiModule.exports.JsWorkflow
module.exports.WorkflowBuilder = __napiModule.exports.WorkflowBuilder
module.exports.JsWorkflowBuilder = __napiModule.exports.JsWorkflowBuilder
module.exports.WorkflowCheckpoint = __napiModule.exports.WorkflowCheckpoint
module.exports.JsWorkflowCheckpoint = __napiModule.exports.JsWorkflowCheckpoint
module.exports.WorkflowHandler = __napiModule.exports.WorkflowHandler
module.exports.JsWorkflowHandler = __napiModule.exports.JsWorkflowHandler
module.exports.WorkflowHistory = __napiModule.exports.WorkflowHistory
module.exports.JsWorkflowHistory = __napiModule.exports.JsWorkflowHistory
module.exports.WorkflowSnapshot = __napiModule.exports.WorkflowSnapshot
module.exports.JsWorkflowSnapshot = __napiModule.exports.JsWorkflowSnapshot
module.exports.XaiProvider = __napiModule.exports.XaiProvider
module.exports.JsXaiProvider = __napiModule.exports.JsXaiProvider
module.exports.addUsageToTokenUsage = __napiModule.exports.addUsageToTokenUsage
module.exports.audioInput = __napiModule.exports.audioInput
module.exports.cadInput = __napiModule.exports.cadInput
module.exports.ChatRole = __napiModule.exports.ChatRole
module.exports.JsChatRole = __napiModule.exports.JsChatRole
module.exports.completeBatch = __napiModule.exports.completeBatch
module.exports.completeBatchConfig = __napiModule.exports.completeBatchConfig
module.exports.computeAudioCost = __napiModule.exports.computeAudioCost
module.exports.computeElidSimilarity = __napiModule.exports.computeElidSimilarity
module.exports.computeEmbeddingSimhashSimilarity = __napiModule.exports.computeEmbeddingSimhashSimilarity
module.exports.computeImageCost = __napiModule.exports.computeImageCost
module.exports.computeTextSimhashSimilarity = __napiModule.exports.computeTextSimhashSimilarity
module.exports.computeVideoCost = __napiModule.exports.computeVideoCost
module.exports.countMessageTokens = __napiModule.exports.countMessageTokens
module.exports.defaultHttpClientConfig = __napiModule.exports.defaultHttpClientConfig
module.exports.envVarForProvider = __napiModule.exports.envVarForProvider
module.exports.estimateTokens = __napiModule.exports.estimateTokens
module.exports.extractInlineArtifacts = __napiModule.exports.extractInlineArtifacts
module.exports.fileInput = __napiModule.exports.fileInput
module.exports.FINISH_WORKFLOW_TOOL_NAME = __napiModule.exports.FINISH_WORKFLOW_TOOL_NAME
module.exports.finishWorkflowTool = __napiModule.exports.finishWorkflowTool
module.exports.finishWorkflowToolDef = __napiModule.exports.finishWorkflowToolDef
module.exports.formatProviderHttpTail = __napiModule.exports.formatProviderHttpTail
module.exports.getContextWindow = __napiModule.exports.getContextWindow
module.exports.HistoryEventKindTag = __napiModule.exports.HistoryEventKindTag
module.exports.JsHistoryEventKindTag = __napiModule.exports.JsHistoryEventKindTag
module.exports.imageInput = __napiModule.exports.imageInput
module.exports.initLangfuse = __napiModule.exports.initLangfuse
module.exports.initOtlp = __napiModule.exports.initOtlp
module.exports.initPrometheus = __napiModule.exports.initPrometheus
module.exports.internEventType = __napiModule.exports.internEventType
module.exports.JoinStrategy = __napiModule.exports.JoinStrategy
module.exports.JsJoinStrategy = __napiModule.exports.JsJoinStrategy
module.exports.JsAuthMethod = __napiModule.exports.JsAuthMethod
module.exports.JsCacheStrategy = __napiModule.exports.JsCacheStrategy
module.exports.JsContentKind = __napiModule.exports.JsContentKind
module.exports.JsDiffusionScheduler = __napiModule.exports.JsDiffusionScheduler
module.exports.JsFalLlmEndpointKind = __napiModule.exports.JsFalLlmEndpointKind
module.exports.JsJobStatus = __napiModule.exports.JsJobStatus
module.exports.JsRole = __napiModule.exports.JsRole
module.exports.JsWhisperModel = __napiModule.exports.JsWhisperModel
module.exports.LlamaCppChatRole = __napiModule.exports.LlamaCppChatRole
module.exports.JsLlamaCppChatRole = __napiModule.exports.JsLlamaCppChatRole
module.exports.loadClientTls = __napiModule.exports.loadClientTls
module.exports.loadServerTls = __napiModule.exports.loadServerTls
module.exports.lookupPricing = __napiModule.exports.lookupPricing
module.exports.lookupStepBuilder = __napiModule.exports.lookupStepBuilder
module.exports.Modality = __napiModule.exports.Modality
module.exports.JsModality = __napiModule.exports.JsModality
module.exports.newRetryStack = __napiModule.exports.newRetryStack
module.exports.newUsageEvent = __napiModule.exports.newUsageEvent
module.exports.PauseReason = __napiModule.exports.PauseReason
module.exports.JsPauseReason = __napiModule.exports.JsPauseReason
module.exports.peerEnvelopeVersion = __napiModule.exports.peerEnvelopeVersion
module.exports.peerTokenEnv = __napiModule.exports.peerTokenEnv
module.exports.ProgressKind = __napiModule.exports.ProgressKind
module.exports.JsProgressKind = __napiModule.exports.JsProgressKind
module.exports.providerEnvVars = __napiModule.exports.providerEnvVars
module.exports.ProviderId = __napiModule.exports.ProviderId
module.exports.JsProviderId = __napiModule.exports.JsProviderId
module.exports.RefLifetime = __napiModule.exports.RefLifetime
module.exports.JsRefLifetime = __napiModule.exports.JsRefLifetime
module.exports.registeredStepIds = __napiModule.exports.registeredStepIds
module.exports.registerEventDeserializer = __napiModule.exports.registerEventDeserializer
module.exports.registerFromModelInfo = __napiModule.exports.registerFromModelInfo
module.exports.registerPricing = __napiModule.exports.registerPricing
module.exports.registerStepBuilder = __napiModule.exports.registerStepBuilder
module.exports.resolveApiKey = __napiModule.exports.resolveApiKey
module.exports.resolveBeerToken = __napiModule.exports.resolveBeerToken
module.exports.resolveRetryStack = __napiModule.exports.resolveRetryStack
module.exports.runAgent = __napiModule.exports.runAgent
module.exports.runAgentWithCallback = __napiModule.exports.runAgentWithCallback
module.exports.SessionPausePolicy = __napiModule.exports.SessionPausePolicy
module.exports.JsSessionPausePolicy = __napiModule.exports.JsSessionPausePolicy
module.exports.simhashFromHex = __napiModule.exports.simhashFromHex
module.exports.simhashToHex = __napiModule.exports.simhashToHex
module.exports.StateValueKind = __napiModule.exports.StateValueKind
module.exports.JsStateValueKind = __napiModule.exports.JsStateValueKind
module.exports.StepOutputKind = __napiModule.exports.StepOutputKind
module.exports.JsStepOutputKind = __napiModule.exports.JsStepOutputKind
module.exports.TemplateRole = __napiModule.exports.TemplateRole
module.exports.JsTemplateRole = __napiModule.exports.JsTemplateRole
module.exports.threeDInput = __napiModule.exports.threeDInput
module.exports.tryDeserializeEvent = __napiModule.exports.tryDeserializeEvent
module.exports.typedToolSimple = __napiModule.exports.typedToolSimple
module.exports.unlimitedHttpClientConfig = __napiModule.exports.unlimitedHttpClientConfig
module.exports.version = __napiModule.exports.version
module.exports.videoInput = __napiModule.exports.videoInput
