// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./blazen.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-android-arm64')
        const bindingPackageVersion = require('@blazen-dev/blazen-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./blazen.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-android-arm-eabi')
        const bindingPackageVersion = require('@blazen-dev/blazen-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./blazen.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-win32-x64-gnu')
        const bindingPackageVersion = require('@blazen-dev/blazen-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./blazen.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-win32-x64-msvc')
        const bindingPackageVersion = require('@blazen-dev/blazen-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./blazen.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-win32-ia32-msvc')
        const bindingPackageVersion = require('@blazen-dev/blazen-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./blazen.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-win32-arm64-msvc')
        const bindingPackageVersion = require('@blazen-dev/blazen-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./blazen.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@blazen-dev/blazen-darwin-universal')
      const bindingPackageVersion = require('@blazen-dev/blazen-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./blazen.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-darwin-x64')
        const bindingPackageVersion = require('@blazen-dev/blazen-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./blazen.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-darwin-arm64')
        const bindingPackageVersion = require('@blazen-dev/blazen-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./blazen.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-freebsd-x64')
        const bindingPackageVersion = require('@blazen-dev/blazen-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./blazen.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-freebsd-arm64')
        const bindingPackageVersion = require('@blazen-dev/blazen-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./blazen.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-x64-musl')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./blazen.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-x64-gnu')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./blazen.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-arm64-musl')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./blazen.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-arm64-gnu')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./blazen.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-arm-musleabihf')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./blazen.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./blazen.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-loong64-musl')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./blazen.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-loong64-gnu')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./blazen.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-riscv64-musl')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./blazen.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@blazen-dev/blazen-linux-riscv64-gnu')
          const bindingPackageVersion = require('@blazen-dev/blazen-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./blazen.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-linux-ppc64-gnu')
        const bindingPackageVersion = require('@blazen-dev/blazen-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./blazen.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-linux-s390x-gnu')
        const bindingPackageVersion = require('@blazen-dev/blazen-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./blazen.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-openharmony-arm64')
        const bindingPackageVersion = require('@blazen-dev/blazen-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./blazen.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-openharmony-x64')
        const bindingPackageVersion = require('@blazen-dev/blazen-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./blazen.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@blazen-dev/blazen-openharmony-arm')
        const bindingPackageVersion = require('@blazen-dev/blazen-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./blazen.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@blazen-dev/blazen-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.ActiveWorkflowSnapshot = nativeBinding.ActiveWorkflowSnapshot
module.exports.JsActiveWorkflowSnapshot = nativeBinding.JsActiveWorkflowSnapshot
module.exports.AnthropicProvider = nativeBinding.AnthropicProvider
module.exports.JsAnthropicProvider = nativeBinding.JsAnthropicProvider
module.exports.AzureOpenAiProvider = nativeBinding.AzureOpenAiProvider
module.exports.JsAzureOpenAiProvider = nativeBinding.JsAzureOpenAiProvider
module.exports.BackgroundRemovalProvider = nativeBinding.BackgroundRemovalProvider
module.exports.JsBackgroundRemovalProvider = nativeBinding.JsBackgroundRemovalProvider
module.exports.BatchConfig = nativeBinding.BatchConfig
module.exports.JsBatchConfig = nativeBinding.JsBatchConfig
module.exports.BedrockProvider = nativeBinding.BedrockProvider
module.exports.JsBedrockProvider = nativeBinding.JsBedrockProvider
module.exports.BlazenPeerClient = nativeBinding.BlazenPeerClient
module.exports.JsBlazenPeerClient = nativeBinding.JsBlazenPeerClient
module.exports.BlazenPeerServer = nativeBinding.BlazenPeerServer
module.exports.JsBlazenPeerServer = nativeBinding.JsBlazenPeerServer
module.exports.BytesWrapper = nativeBinding.BytesWrapper
module.exports.JsBytesWrapper = nativeBinding.JsBytesWrapper
module.exports.CachedCompletionModel = nativeBinding.CachedCompletionModel
module.exports.JsCachedCompletionModel = nativeBinding.JsCachedCompletionModel
module.exports.CacheMiddleware = nativeBinding.CacheMiddleware
module.exports.JsCacheMiddleware = nativeBinding.JsCacheMiddleware
module.exports.CandleEmbedProvider = nativeBinding.CandleEmbedProvider
module.exports.JsCandleEmbedProvider = nativeBinding.JsCandleEmbedProvider
module.exports.CandleLlmProvider = nativeBinding.CandleLlmProvider
module.exports.JsCandleLlmProvider = nativeBinding.JsCandleLlmProvider
module.exports.ChatMessage = nativeBinding.ChatMessage
module.exports.JsChatMessage = nativeBinding.JsChatMessage
module.exports.ChatWindow = nativeBinding.ChatWindow
module.exports.JsChatWindow = nativeBinding.JsChatWindow
module.exports.CheckpointStore = nativeBinding.CheckpointStore
module.exports.JsCheckpointStore = nativeBinding.JsCheckpointStore
module.exports.Citation = nativeBinding.Citation
module.exports.JsCitationClass = nativeBinding.JsCitationClass
module.exports.CohereProvider = nativeBinding.CohereProvider
module.exports.JsCohereProvider = nativeBinding.JsCohereProvider
module.exports.CompletionModel = nativeBinding.CompletionModel
module.exports.JsCompletionModel = nativeBinding.JsCompletionModel
module.exports.Context = nativeBinding.Context
module.exports.JsContext = nativeBinding.JsContext
module.exports.CustomProvider = nativeBinding.CustomProvider
module.exports.JsCustomProvider = nativeBinding.JsCustomProvider
module.exports.DeepSeekProvider = nativeBinding.DeepSeekProvider
module.exports.JsDeepSeekProvider = nativeBinding.JsDeepSeekProvider
module.exports.DiffusionProvider = nativeBinding.DiffusionProvider
module.exports.JsDiffusionProvider = nativeBinding.JsDiffusionProvider
module.exports.DynamicEvent = nativeBinding.DynamicEvent
module.exports.JsDynamicEvent = nativeBinding.JsDynamicEvent
module.exports.EmbeddingModel = nativeBinding.EmbeddingModel
module.exports.JsEmbeddingModel = nativeBinding.JsEmbeddingModel
module.exports.EmbedProvider = nativeBinding.EmbedProvider
module.exports.JsEmbedProvider = nativeBinding.JsEmbedProvider
module.exports.EstimateCounter = nativeBinding.EstimateCounter
module.exports.JsEstimateCounter = nativeBinding.JsEstimateCounter
module.exports.FalEmbeddingModel = nativeBinding.FalEmbeddingModel
module.exports.JsFalEmbeddingModel = nativeBinding.JsFalEmbeddingModel
module.exports.FallbackModel = nativeBinding.FallbackModel
module.exports.JsFallbackModel = nativeBinding.JsFallbackModel
module.exports.FalProvider = nativeBinding.FalProvider
module.exports.JsFalProvider = nativeBinding.JsFalProvider
module.exports.FastEmbedModel = nativeBinding.FastEmbedModel
module.exports.JsFastEmbedModel = nativeBinding.JsFastEmbedModel
module.exports.FireworksProvider = nativeBinding.FireworksProvider
module.exports.JsFireworksProvider = nativeBinding.JsFireworksProvider
module.exports.GeminiProvider = nativeBinding.GeminiProvider
module.exports.JsGeminiProvider = nativeBinding.JsGeminiProvider
module.exports.GroqProvider = nativeBinding.GroqProvider
module.exports.JsGroqProvider = nativeBinding.JsGroqProvider
module.exports.HistoryEventKind = nativeBinding.HistoryEventKind
module.exports.JsHistoryEventKind = nativeBinding.JsHistoryEventKind
module.exports.HostDispatch = nativeBinding.HostDispatch
module.exports.JsHostDispatch = nativeBinding.JsHostDispatch
module.exports.HttpClient = nativeBinding.HttpClient
module.exports.JsHttpClient = nativeBinding.JsHttpClient
module.exports.ImageModel = nativeBinding.ImageModel
module.exports.JsImageModel = nativeBinding.JsImageModel
module.exports.ImageProvider = nativeBinding.ImageProvider
module.exports.JsImageProvider = nativeBinding.JsImageProvider
module.exports.InMemoryBackend = nativeBinding.InMemoryBackend
module.exports.JsInMemoryBackend = nativeBinding.JsInMemoryBackend
module.exports.JobHandle = nativeBinding.JobHandle
module.exports.JsJobHandleClass = nativeBinding.JsJobHandleClass
module.exports.JsonlBackend = nativeBinding.JsonlBackend
module.exports.JsJsonlBackend = nativeBinding.JsJsonlBackend
module.exports.LlamaCppProvider = nativeBinding.LlamaCppProvider
module.exports.JsLlamaCppProvider = nativeBinding.JsLlamaCppProvider
module.exports.LocalModel = nativeBinding.LocalModel
module.exports.JsLocalModel = nativeBinding.JsLocalModel
module.exports.Memory = nativeBinding.Memory
module.exports.JsMemory = nativeBinding.JsMemory
module.exports.MemoryBackend = nativeBinding.MemoryBackend
module.exports.JsMemoryBackend = nativeBinding.JsMemoryBackend
module.exports.MemoryStore = nativeBinding.MemoryStore
module.exports.JsMemoryStore = nativeBinding.JsMemoryStore
module.exports.Middleware = nativeBinding.Middleware
module.exports.JsMiddleware = nativeBinding.JsMiddleware
module.exports.MiddlewareStack = nativeBinding.MiddlewareStack
module.exports.JsMiddlewareStack = nativeBinding.JsMiddlewareStack
module.exports.MistralProvider = nativeBinding.MistralProvider
module.exports.JsMistralProvider = nativeBinding.JsMistralProvider
module.exports.MistralRsProvider = nativeBinding.MistralRsProvider
module.exports.JsMistralRsProvider = nativeBinding.JsMistralRsProvider
module.exports.ModelCache = nativeBinding.ModelCache
module.exports.JsModelCache = nativeBinding.JsModelCache
module.exports.ModelManager = nativeBinding.ModelManager
module.exports.JsModelManager = nativeBinding.JsModelManager
module.exports.ModelRegistry = nativeBinding.ModelRegistry
module.exports.JsModelRegistry = nativeBinding.JsModelRegistry
module.exports.MusicProvider = nativeBinding.MusicProvider
module.exports.JsMusicProvider = nativeBinding.JsMusicProvider
module.exports.OpenAiCompatEmbeddingModel = nativeBinding.OpenAiCompatEmbeddingModel
module.exports.JsOpenAiCompatEmbeddingModel = nativeBinding.JsOpenAiCompatEmbeddingModel
module.exports.OpenAiCompatProvider = nativeBinding.OpenAiCompatProvider
module.exports.JsOpenAiCompatProvider = nativeBinding.JsOpenAiCompatProvider
module.exports.OpenAiEmbeddingModel = nativeBinding.OpenAiEmbeddingModel
module.exports.JsOpenAiEmbeddingModel = nativeBinding.JsOpenAiEmbeddingModel
module.exports.OpenAiProvider = nativeBinding.OpenAiProvider
module.exports.JsOpenAiProvider = nativeBinding.JsOpenAiProvider
module.exports.OpenRouterProvider = nativeBinding.OpenRouterProvider
module.exports.JsOpenRouterProvider = nativeBinding.JsOpenRouterProvider
module.exports.ParallelStage = nativeBinding.ParallelStage
module.exports.JsParallelStage = nativeBinding.JsParallelStage
module.exports.PerplexityProvider = nativeBinding.PerplexityProvider
module.exports.JsPerplexityProvider = nativeBinding.JsPerplexityProvider
module.exports.Pipeline = nativeBinding.Pipeline
module.exports.JsPipeline = nativeBinding.JsPipeline
module.exports.PipelineBuilder = nativeBinding.PipelineBuilder
module.exports.JsPipelineBuilder = nativeBinding.JsPipelineBuilder
module.exports.PipelineEvent = nativeBinding.PipelineEvent
module.exports.JsPipelineEvent = nativeBinding.JsPipelineEvent
module.exports.PipelineHandler = nativeBinding.PipelineHandler
module.exports.JsPipelineHandler = nativeBinding.JsPipelineHandler
module.exports.PipelineResult = nativeBinding.PipelineResult
module.exports.JsPipelineResult = nativeBinding.JsPipelineResult
module.exports.PipelineSnapshot = nativeBinding.PipelineSnapshot
module.exports.JsPipelineSnapshot = nativeBinding.JsPipelineSnapshot
module.exports.PiperProvider = nativeBinding.PiperProvider
module.exports.JsPiperProvider = nativeBinding.JsPiperProvider
module.exports.PromptFile = nativeBinding.PromptFile
module.exports.JsPromptFile = nativeBinding.JsPromptFile
module.exports.PromptRegistry = nativeBinding.PromptRegistry
module.exports.JsPromptRegistry = nativeBinding.JsPromptRegistry
module.exports.PromptTemplate = nativeBinding.PromptTemplate
module.exports.JsPromptTemplate = nativeBinding.JsPromptTemplate
module.exports.ReasoningTrace = nativeBinding.ReasoningTrace
module.exports.JsReasoningTraceClass = nativeBinding.JsReasoningTraceClass
module.exports.RedbCheckpointStore = nativeBinding.RedbCheckpointStore
module.exports.JsRedbCheckpointStore = nativeBinding.JsRedbCheckpointStore
module.exports.RegistryKey = nativeBinding.RegistryKey
module.exports.JsRegistryKey = nativeBinding.JsRegistryKey
module.exports.RequestTiming = nativeBinding.RequestTiming
module.exports.JsRequestTimingClass = nativeBinding.JsRequestTimingClass
module.exports.RetryCompletionModel = nativeBinding.RetryCompletionModel
module.exports.JsRetryCompletionModel = nativeBinding.JsRetryCompletionModel
module.exports.RetryMiddleware = nativeBinding.RetryMiddleware
module.exports.JsRetryMiddleware = nativeBinding.JsRetryMiddleware
module.exports.SessionNamespace = nativeBinding.SessionNamespace
module.exports.JsSessionNamespace = nativeBinding.JsSessionNamespace
module.exports.SessionRefRegistry = nativeBinding.SessionRefRegistry
module.exports.JsSessionRefRegistry = nativeBinding.JsSessionRefRegistry
module.exports.Stage = nativeBinding.Stage
module.exports.JsStage = nativeBinding.JsStage
module.exports.StageResult = nativeBinding.StageResult
module.exports.JsStageResult = nativeBinding.JsStageResult
module.exports.StartEvent = nativeBinding.StartEvent
module.exports.JsStartEventClass = nativeBinding.JsStartEventClass
module.exports.StateNamespace = nativeBinding.StateNamespace
module.exports.JsStateNamespace = nativeBinding.JsStateNamespace
module.exports.StateValue = nativeBinding.StateValue
module.exports.JsStateValue = nativeBinding.JsStateValue
module.exports.StepDeserializerRegistry = nativeBinding.StepDeserializerRegistry
module.exports.JsStepDeserializerRegistry = nativeBinding.JsStepDeserializerRegistry
module.exports.StepOutput = nativeBinding.StepOutput
module.exports.JsStepOutput = nativeBinding.JsStepOutput
module.exports.StepRegistration = nativeBinding.StepRegistration
module.exports.JsStepRegistration = nativeBinding.JsStepRegistration
module.exports.StopEvent = nativeBinding.StopEvent
module.exports.JsStopEventClass = nativeBinding.JsStopEventClass
module.exports.StructuredOutput = nativeBinding.StructuredOutput
module.exports.JsStructuredOutput = nativeBinding.JsStructuredOutput
module.exports.ThreeDProvider = nativeBinding.ThreeDProvider
module.exports.JsThreeDProvider = nativeBinding.JsThreeDProvider
module.exports.TogetherProvider = nativeBinding.TogetherProvider
module.exports.JsTogetherProvider = nativeBinding.JsTogetherProvider
module.exports.TokenCounter = nativeBinding.TokenCounter
module.exports.JsTokenCounter = nativeBinding.JsTokenCounter
module.exports.TokenUsage = nativeBinding.TokenUsage
module.exports.JsTokenUsageClass = nativeBinding.JsTokenUsageClass
module.exports.Tool = nativeBinding.Tool
module.exports.JsTool = nativeBinding.JsTool
module.exports.ToolCall = nativeBinding.ToolCall
module.exports.JsToolCallClass = nativeBinding.JsToolCallClass
module.exports.ToolDefinition = nativeBinding.ToolDefinition
module.exports.JsToolDefinitionClass = nativeBinding.JsToolDefinitionClass
module.exports.TractEmbedModel = nativeBinding.TractEmbedModel
module.exports.JsTractEmbedModel = nativeBinding.JsTractEmbedModel
module.exports.Transcription = nativeBinding.Transcription
module.exports.JsTranscription = nativeBinding.JsTranscription
module.exports.TTSProvider = nativeBinding.TTSProvider
module.exports.JsTTSProvider = nativeBinding.JsTTSProvider
module.exports.TypedTool = nativeBinding.TypedTool
module.exports.JsTypedTool = nativeBinding.JsTypedTool
module.exports.ValkeyBackend = nativeBinding.ValkeyBackend
module.exports.JsValkeyBackend = nativeBinding.JsValkeyBackend
module.exports.ValkeyCheckpointStore = nativeBinding.ValkeyCheckpointStore
module.exports.JsValkeyCheckpointStore = nativeBinding.JsValkeyCheckpointStore
module.exports.VideoProvider = nativeBinding.VideoProvider
module.exports.JsVideoProvider = nativeBinding.JsVideoProvider
module.exports.VoiceProvider = nativeBinding.VoiceProvider
module.exports.JsVoiceProvider = nativeBinding.JsVoiceProvider
module.exports.WhisperCppProvider = nativeBinding.WhisperCppProvider
module.exports.JsWhisperCppProvider = nativeBinding.JsWhisperCppProvider
module.exports.Workflow = nativeBinding.Workflow
module.exports.JsWorkflow = nativeBinding.JsWorkflow
module.exports.WorkflowBuilder = nativeBinding.WorkflowBuilder
module.exports.JsWorkflowBuilder = nativeBinding.JsWorkflowBuilder
module.exports.WorkflowCheckpoint = nativeBinding.WorkflowCheckpoint
module.exports.JsWorkflowCheckpoint = nativeBinding.JsWorkflowCheckpoint
module.exports.WorkflowHandler = nativeBinding.WorkflowHandler
module.exports.JsWorkflowHandler = nativeBinding.JsWorkflowHandler
module.exports.WorkflowHistory = nativeBinding.WorkflowHistory
module.exports.JsWorkflowHistory = nativeBinding.JsWorkflowHistory
module.exports.WorkflowSnapshot = nativeBinding.WorkflowSnapshot
module.exports.JsWorkflowSnapshot = nativeBinding.JsWorkflowSnapshot
module.exports.XaiProvider = nativeBinding.XaiProvider
module.exports.JsXaiProvider = nativeBinding.JsXaiProvider
module.exports.completeBatch = nativeBinding.completeBatch
module.exports.completeBatchConfig = nativeBinding.completeBatchConfig
module.exports.computeElidSimilarity = nativeBinding.computeElidSimilarity
module.exports.computeEmbeddingSimhashSimilarity = nativeBinding.computeEmbeddingSimhashSimilarity
module.exports.computeTextSimhashSimilarity = nativeBinding.computeTextSimhashSimilarity
module.exports.countMessageTokens = nativeBinding.countMessageTokens
module.exports.envVarForProvider = nativeBinding.envVarForProvider
module.exports.estimateTokens = nativeBinding.estimateTokens
module.exports.extractInlineArtifacts = nativeBinding.extractInlineArtifacts
module.exports.formatProviderHttpTail = nativeBinding.formatProviderHttpTail
module.exports.getContextWindow = nativeBinding.getContextWindow
module.exports.HistoryEventKindTag = nativeBinding.HistoryEventKindTag
module.exports.JsHistoryEventKindTag = nativeBinding.JsHistoryEventKindTag
module.exports.internEventType = nativeBinding.internEventType
module.exports.JoinStrategy = nativeBinding.JoinStrategy
module.exports.JsJoinStrategy = nativeBinding.JsJoinStrategy
module.exports.JsAuthMethod = nativeBinding.JsAuthMethod
module.exports.JsCacheStrategy = nativeBinding.JsCacheStrategy
module.exports.JsDiffusionScheduler = nativeBinding.JsDiffusionScheduler
module.exports.JsFalLlmEndpointKind = nativeBinding.JsFalLlmEndpointKind
module.exports.JsJobStatus = nativeBinding.JsJobStatus
module.exports.JsRole = nativeBinding.JsRole
module.exports.JsWhisperModel = nativeBinding.JsWhisperModel
module.exports.loadClientTls = nativeBinding.loadClientTls
module.exports.loadServerTls = nativeBinding.loadServerTls
module.exports.lookupPricing = nativeBinding.lookupPricing
module.exports.lookupStepBuilder = nativeBinding.lookupStepBuilder
module.exports.PauseReason = nativeBinding.PauseReason
module.exports.JsPauseReason = nativeBinding.JsPauseReason
module.exports.peerEnvelopeVersion = nativeBinding.peerEnvelopeVersion
module.exports.peerTokenEnv = nativeBinding.peerTokenEnv
module.exports.providerEnvVars = nativeBinding.providerEnvVars
module.exports.ProviderId = nativeBinding.ProviderId
module.exports.JsProviderId = nativeBinding.JsProviderId
module.exports.RefLifetime = nativeBinding.RefLifetime
module.exports.JsRefLifetime = nativeBinding.JsRefLifetime
module.exports.registeredStepIds = nativeBinding.registeredStepIds
module.exports.registerEventDeserializer = nativeBinding.registerEventDeserializer
module.exports.registerFromModelInfo = nativeBinding.registerFromModelInfo
module.exports.registerPricing = nativeBinding.registerPricing
module.exports.registerStepBuilder = nativeBinding.registerStepBuilder
module.exports.resolveApiKey = nativeBinding.resolveApiKey
module.exports.resolveBeerToken = nativeBinding.resolveBeerToken
module.exports.runAgent = nativeBinding.runAgent
module.exports.runAgentWithCallback = nativeBinding.runAgentWithCallback
module.exports.SessionPausePolicy = nativeBinding.SessionPausePolicy
module.exports.JsSessionPausePolicy = nativeBinding.JsSessionPausePolicy
module.exports.simhashFromHex = nativeBinding.simhashFromHex
module.exports.simhashToHex = nativeBinding.simhashToHex
module.exports.StateValueKind = nativeBinding.StateValueKind
module.exports.JsStateValueKind = nativeBinding.JsStateValueKind
module.exports.StepOutputKind = nativeBinding.StepOutputKind
module.exports.JsStepOutputKind = nativeBinding.JsStepOutputKind
module.exports.TemplateRole = nativeBinding.TemplateRole
module.exports.JsTemplateRole = nativeBinding.JsTemplateRole
module.exports.tryDeserializeEvent = nativeBinding.tryDeserializeEvent
module.exports.typedToolSimple = nativeBinding.typedToolSimple
module.exports.version = nativeBinding.version
