/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A single message in a chat conversation. */
export declare class ChatMessage {
  /**
   * Create a new chat message from an options object.
   *
   * `role` defaults to `"user"` if not provided.
   * Supply either `content` (text) or `parts` (multimodal).
   */
  constructor(options: ChatMessageOptions)
  /** Create a system message. */
  static system(content: string): ChatMessage
  /** Create a user message. */
  static user(content: string): ChatMessage
  /** Create an assistant message. */
  static assistant(content: string): ChatMessage
  /** Create a tool result message. */
  static tool(content: string): ChatMessage
  /** Create a user message containing text and an image from a URL. */
  static userImageUrl(text: string, url: string, mediaType?: string | undefined | null): ChatMessage
  /** Create a user message containing text and a base64-encoded image. */
  static userImageBase64(text: string, data: string, mediaType: string): ChatMessage
  /** Create a user message containing text and an audio clip from a URL. */
  static userAudio(text: string, url: string): ChatMessage
  /** Create a user message containing text and base64-encoded audio data. */
  static userAudioBase64(text: string, data: string, mediaType: string): ChatMessage
  /** Create a user message containing text and a video clip from a URL. */
  static userVideo(text: string, url: string): ChatMessage
  /** Create a user message containing text and base64-encoded video data. */
  static userVideoBase64(text: string, data: string, mediaType: string): ChatMessage
  /** Create a user message from an explicit list of content parts. */
  static userParts(parts: Array<JsContentPart>): ChatMessage
  /** The role of the message author. */
  get role(): string
  /** The text content of the message, if any. */
  get content(): string | null
}
export type JsChatMessage = ChatMessage

/**
 * A chat completion model.
 *
 * Use the static factory methods to create an instance for your provider:
 *
 * ```javascript
 * const model = CompletionModel.openai("sk-...");
 * const response = await model.complete([
 *   ChatMessage.user("What is 2 + 2?")
 * ]);
 * ```
 */
export declare class CompletionModel {
  /** Create an `OpenAI` completion model. */
  static openai(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create an Anthropic completion model. */
  static anthropic(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a Google Gemini completion model. */
  static gemini(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create an Azure `OpenAI` completion model. */
  static azure(apiKey: string, resourceName: string, deploymentName: string): CompletionModel
  /**
   * Create a fal.ai completion model.
   *
   * `options` optionally configures the LLM model, endpoint family,
   * enterprise tier, and modality auto-routing. Defaults to the
   * OpenAI-compatible chat-completions endpoint.
   */
  static fal(apiKey: string, options?: JsFalOptions | undefined | null): CompletionModel
  /** Create an `OpenRouter` completion model. */
  static openrouter(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a Groq completion model. */
  static groq(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a Together AI completion model. */
  static together(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a Mistral AI completion model. */
  static mistral(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a `DeepSeek` completion model. */
  static deepseek(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a Fireworks AI completion model. */
  static fireworks(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a Perplexity completion model. */
  static perplexity(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create an xAI (Grok) completion model. */
  static xai(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create a Cohere completion model. */
  static cohere(apiKey: string, model?: string | undefined | null): CompletionModel
  /** Create an AWS Bedrock completion model. */
  static bedrock(apiKey: string, region: string, model?: string | undefined | null): CompletionModel
  /** Get the model ID. */
  get modelId(): string
  /**
   * Wrap this model with automatic retry on transient failures.
   *
   * ```javascript
   * const model = CompletionModel.openrouter(key);
   * const withRetry = model.withRetry({ maxRetries: 3, initialDelayMs: 1000 });
   * ```
   */
  withRetry(config?: JsRetryConfig | undefined | null): CompletionModel
  /**
   * Wrap this model with an in-memory response cache.
   *
   * Streaming requests are never cached and always delegate directly to the
   * underlying model.
   *
   * ```javascript
   * const cached = model.withCache({ ttlSeconds: 300, maxEntries: 1000 });
   * ```
   */
  withCache(config?: JsCacheConfig | undefined | null): CompletionModel
  /**
   * Create a fallback model that tries multiple providers in order.
   *
   * When the primary provider fails with a transient error (rate limit,
   * timeout, server error) the request is automatically forwarded to the
   * next provider. Non-retryable errors short-circuit immediately.
   *
   * ```javascript
   * const model = CompletionModel.withFallback([modelA, modelB]);
   * ```
   */
  static withFallback(models: Array<CompletionModel>): CompletionModel
  /**
   * Perform a chat completion.
   *
   * Messages should be an array of `ChatMessage` instances.
   *
   * Returns a typed response with `content`, `toolCalls`, `usage`, `model`,
   * and `finishReason` fields.
   */
  complete(messages: Array<JsChatMessage>): Promise<JsCompletionResponse>
  /**
   * Perform a chat completion with additional options.
   *
   * Options object may include:
   * - `temperature` (number): Sampling temperature (0.0 - 2.0)
   * - `maxTokens` (number): Maximum tokens to generate
   * - `topP` (number): Nucleus sampling parameter
   * - `model` (string): Override the default model
   * - `tools` (array): Tool definitions for function calling
   */
  completeWithOptions(messages: Array<JsChatMessage>, options: JsCompletionOptions): Promise<JsCompletionResponse>
  /**
   * Stream a chat completion.
   *
   * The `onChunk` callback receives each chunk as a typed `StreamChunk` with
   * `delta`, `finishReason`, and `toolCalls` fields.
   *
   * ```javascript
   * await model.stream(
   *   [ChatMessage.user("Tell me a story")],
   *   (chunk) => { if (chunk.delta) process.stdout.write(chunk.delta); }
   * );
   * ```
   */
  stream(messages: Array<JsChatMessage>, onChunk: StreamChunkCallbackTsfn): Promise<void>
  /**
   * Stream a chat completion with additional options.
   *
   * Options object may include:
   * - `temperature` (number): Sampling temperature (0.0 - 2.0)
   * - `maxTokens` (number): Maximum tokens to generate
   * - `topP` (number): Nucleus sampling parameter
   * - `model` (string): Override the default model
   * - `tools` (array): Tool definitions for function calling
   */
  streamWithOptions(messages: Array<JsChatMessage>, onChunk: StreamChunkCallbackTsfn, options: JsCompletionOptions): Promise<void>
}
export type JsCompletionModel = CompletionModel

/**
 * Shared workflow context accessible by all steps.
 *
 * Provides typed key/value storage, event emission, and stream publishing.
 * Use `set()` for JSON-serializable values, `setBytes()` for binary data.
 * `get()` returns the correct type for any stored value.
 */
export declare class Context {
  /**
   * Store a JSON-serializable value under the given key.
   *
   * For binary data (Buffer/Uint8Array), use `setBytes()` instead.
   */
  set(key: string, value: Exclude<StateValue, Buffer>): Promise<void>
  /**
   * Retrieve a value previously stored under the given key.
   *
   * Returns `Buffer` for binary data, the original JS value for JSON data,
   * or `null` if the key does not exist.
   */
  get(key: string): Promise<StateValue | null>
  /**
   * Emit an event into the internal routing queue.
   *
   * The event will be routed to any step whose `eventTypes` list includes
   * its event type. The event object must have a `type` field.
   */
  sendEvent(event: any): Promise<void>
  /**
   * Publish an event to the external broadcast stream.
   *
   * Consumers that subscribed via streaming will receive this event.
   * Unlike `sendEvent`, this does NOT route the event through the
   * internal step registry.
   */
  writeEventToStream(event: any): Promise<void>
  /**
   * Store raw binary data under the given key.
   *
   * Use this for Buffer/Uint8Array data that should be stored as binary
   * and returned as Buffer from `getBytes()`.
   */
  setBytes(key: string, data: Buffer): Promise<void>
  /**
   * Retrieve raw binary data previously stored under the given key.
   *
   * Returns `null` if the key does not exist or the stored value is
   * not binary data.
   */
  getBytes(key: string): Promise<Buffer | null>
  /** Get the workflow run ID. */
  runId(): Promise<string>
  /**
   * Persistable workflow state. Survives `pause()` / `resume()`,
   * checkpoints, and durable storage.
   *
   * ```javascript
   * await ctx.state.set("counter", 5);
   * const count = await ctx.state.get("counter");
   * ```
   */
  get state(): JsStateNamespace
  /**
   * In-process-only values. Excluded from snapshots — use this for
   * things that should not survive `pause()` / `resume()`.
   *
   * ```javascript
   * await ctx.session.set("reqId", 42);
   * const n = await ctx.session.get("reqId");
   * ```
   */
  get session(): JsSessionNamespace
}
export type JsContext = Context

/**
 * An embedding model that produces vector representations of text.
 *
 * Use the static factory methods to create an instance for your provider:
 *
 * ```javascript
 * const model = EmbeddingModel.openai("sk-...");
 * const response = await model.embed(["Hello", "World"]);
 * console.log(response.embeddings); // [[0.1, ...], [0.3, ...]]
 * ```
 */
export declare class EmbeddingModel {
  /**
   * Create an `OpenAI` embedding model.
   *
   * Defaults to `text-embedding-3-small` (1536 dimensions).
   */
  static openai(apiKey: string): EmbeddingModel
  /**
   * Create a Together AI embedding model.
   *
   * Defaults to `togethercomputer/m2-bert-80M-8k-retrieval` (768 dimensions).
   */
  static together(apiKey: string): EmbeddingModel
  /**
   * Create a Cohere embedding model.
   *
   * Defaults to `embed-v4.0` (1024 dimensions).
   */
  static cohere(apiKey: string): EmbeddingModel
  /**
   * Create a Fireworks AI embedding model.
   *
   * Defaults to `nomic-ai/nomic-embed-text-v1.5` (768 dimensions).
   */
  static fireworks(apiKey: string): EmbeddingModel
  /** The model identifier. */
  get modelId(): string
  /** The dimensionality of the embedding vectors produced by this model. */
  get dimensions(): number
  /** Embed one or more texts, returning one vector per input text. */
  embed(texts: Array<string>): Promise<JsEmbeddingResponse>
}
export type JsEmbeddingModel = EmbeddingModel

/**
 * A fal.ai embedding model.
 *
 * Wraps [`FalEmbeddingModel`] and exposes the
 * [`EmbeddingModel`](blazen_llm::EmbeddingModel) interface to JavaScript.
 * Constructed via [`JsFalProvider::embedding_model`].
 *
 * ```typescript
 * const fal = FalProvider.create("fal-key-...");
 * const em = fal.embeddingModel();
 * const vectors = await em.embed(["hello", "world"]);
 * console.log(vectors.length); // 2
 * ```
 */
export declare class FalEmbeddingModel {
  /** Get the underlying embedding model id. */
  get modelId(): string
  /** Get the dimensionality of the produced embedding vectors. */
  get dimensions(): number
  /**
   * Embed one or more texts.
   *
   * Returns a list of embedding vectors (one per input text).
   */
  embed(texts: Array<string>): Promise<Array<Array<number>>>
}
export type JsFalEmbeddingModel = FalEmbeddingModel

/**
 * A fal.ai compute platform provider with image, video, audio, transcription,
 * and LLM capabilities.
 *
 * ```typescript
 * const fal = FalProvider.create("fal-key-...");
 * const result = await fal.generateImage({ prompt: "a sunset" });
 * const response = await fal.complete([ChatMessage.user("Hi")]);
 * ```
 */
export declare class FalProvider {
  /**
   * Create a new fal.ai provider.
   *
   * `options` optionally configures the LLM model, endpoint family,
   * enterprise tier, and modality auto-routing. Defaults to the
   * OpenAI-compatible chat-completions endpoint (`OpenAiChat`).
   */
  static create(apiKey: string, options?: JsFalOptions | undefined | null): FalProvider
  /** Get the model ID. */
  get modelId(): string
  /** Generate images from a text prompt. */
  generateImage(request: JsImageRequest): Promise<any>
  /** Upscale an image. */
  upscaleImage(request: JsUpscaleRequest): Promise<any>
  /** Upscale an image via the aura-sr model. */
  upscaleImageAura(request: JsUpscaleRequest): Promise<any>
  /** Upscale an image via the clarity-upscaler model. */
  upscaleImageClarity(request: JsUpscaleRequest): Promise<any>
  /** Upscale an image via the creative-upscaler model. */
  upscaleImageCreative(request: JsUpscaleRequest): Promise<any>
  /**
   * Remove the background from an image.
   *
   * `imageUrl` is the URL of the source image. `model` optionally
   * overrides the model id.
   */
  removeBackground(imageUrl: string, model?: string | undefined | null): Promise<any>
  /** Generate a 3D model from a text prompt or source image. */
  generate3d(request: JsThreeDRequest): Promise<any>
  /**
   * Build a [`JsFalEmbeddingModel`] sharing this provider's HTTP client
   * and API key.
   */
  embeddingModel(): JsFalEmbeddingModel
  /** Generate a video from a text prompt. */
  textToVideo(request: JsVideoRequest): Promise<any>
  /** Generate a video from a source image and prompt. */
  imageToVideo(request: JsVideoRequest): Promise<any>
  /** Synthesize speech from text. */
  textToSpeech(request: JsSpeechRequest): Promise<any>
  /** Generate music from a prompt. */
  generateMusic(request: JsMusicRequest): Promise<any>
  /** Generate sound effects from a prompt. */
  generateSfx(request: JsMusicRequest): Promise<any>
  /** Transcribe audio to text. */
  transcribe(request: JsTranscriptionRequest): Promise<any>
  /** Run a model synchronously (submit + wait for result). */
  run(model: string, input: any): Promise<any>
  /** Submit a job to the queue and return a job handle. */
  submit(model: string, input: any): Promise<any>
  /** Get the status of a submitted job. */
  status(jobId: string, model: string): Promise<any>
  /** Cancel a submitted job. */
  cancel(jobId: string, model: string): Promise<void>
  /** Perform a chat completion via fal.ai's `any-llm` proxy. */
  complete(messages: Array<JsChatMessage>): Promise<JsCompletionResponse>
}
export type JsFalProvider = FalProvider

/**
 * An in-memory backend for the memory store.
 *
 * Data lives only as long as the process; nothing is persisted.
 *
 * ```javascript
 * const backend = new InMemoryBackend();
 * const memory = new Memory(embedder, backend);
 * ```
 */
export declare class InMemoryBackend {
  /** Create a new, empty in-memory backend. */
  constructor()
}
export type JsInMemoryBackend = InMemoryBackend

/**
 * A JSONL file-backed backend for the memory store.
 *
 * Loads entries from the file on creation, appends new entries, and rewrites
 * on updates/deletes.
 *
 * ```javascript
 * const backend = await JsonlBackend.create("./memory.jsonl");
 * const memory = new Memory(embedder, backend);
 * ```
 */
export declare class JsonlBackend {
  /**
   * Create a JSONL backend at the given file path.
   *
   * If the file exists, its contents are loaded. Otherwise an empty store
   * is created and the file is written on the first insert.
   */
  static create(path: string): Promise<JsonlBackend>
}
export type JsJsonlBackend = JsonlBackend

/**
 * A memory store that uses ELID for vector indexing and similarity search.
 *
 * Supports two modes:
 * - **Full mode** (`new Memory(embedder, backend)`): embedding-based search
 * - **Local mode** (`Memory.local(backend)`): text `SimHash` only, no embedder
 *
 * ```javascript
 * import { Memory, EmbeddingModel, InMemoryBackend } from 'blazen';
 *
 * const embedder = EmbeddingModel.openai(key);
 * const memory = new Memory(embedder, new InMemoryBackend());
 *
 * await memory.add("doc1", "Paris is the capital of France");
 * const results = await memory.search("What is France's capital?", 5);
 * console.log(results[0].text);
 * ```
 */
export declare class Memory {
  /**
   * Create a memory store with an embedding model for full ELID-based search.
   *
   * @param embedder - The embedding model to use for vectorisation.
   * @param backend  - An `InMemoryBackend` instance.
   */
  constructor(embedder: EmbeddingModel, backend: InMemoryBackend)
  /** Create a memory store with an embedding model and a `JsonlBackend`. */
  static withJsonl(embedder: EmbeddingModel, backend: JsonlBackend): Memory
  /** Create a memory store with an embedding model and a `ValkeyBackend`. */
  static withValkey(embedder: EmbeddingModel, backend: ValkeyBackend): Memory
  /**
   * Create a memory store in local-only mode (no embedding model) with an `InMemoryBackend`.
   *
   * Only `searchLocal()` is available; `search()` will throw.
   */
  static local(backend: InMemoryBackend): Memory
  /** Create a memory store in local-only mode with a `JsonlBackend`. */
  static localJsonl(backend: JsonlBackend): Memory
  /** Create a memory store in local-only mode with a `ValkeyBackend`. */
  static localValkey(backend: ValkeyBackend): Memory
  /**
   * Add a text entry to the memory store.
   *
   * @param id       - A unique identifier for this entry.
   * @param text     - The text content to store.
   * @param metadata - Optional arbitrary metadata (will be stored as JSON).
   * @returns The id of the stored entry.
   */
  add(id: string, text: string, metadata?: any | undefined | null): Promise<string>
  /**
   * Add multiple text entries to the memory store in a single batch.
   *
   * @param entries - An array of `{ id, text, metadata? }` objects.
   * @returns The ids of the stored entries.
   */
  addMany(entries: Array<JsAddEntry>): Promise<Array<string>>
  /**
   * Search using a query string with the configured embedding model.
   *
   * Returns up to `limit` results sorted by descending similarity.
   * Requires an embedding model (throws if created with `Memory.local()`).
   *
   * @param query - The search query text.
   * @param limit - Maximum number of results (default: 10).
   * @param `metadata_filter` - Optional JSON object to filter results. Only
   *   entries whose metadata is a superset of the filter are returned.
   */
  search(query: string, limit?: number | undefined | null, metadataFilter?: any | undefined | null): Promise<Array<JsMemoryResult>>
  /**
   * Search using only text-level `SimHash` (no embedding model required).
   *
   * This is a cheaper, lower-quality search that works in local-only mode.
   *
   * @param query - The search query text.
   * @param limit - Maximum number of results (default: 10).
   * @param `metadata_filter` - Optional JSON object to filter results. Only
   *   entries whose metadata is a superset of the filter are returned.
   */
  searchLocal(query: string, limit?: number | undefined | null, metadataFilter?: any | undefined | null): Promise<Array<JsMemoryResult>>
  /**
   * Retrieve a single entry by id.
   *
   * @param id - The entry identifier.
   * @returns The entry, or `null` if not found.
   */
  get(id: string): Promise<JsMemoryEntry | null>
  /**
   * Delete an entry by id.
   *
   * @param id - The entry identifier.
   * @returns `true` if the entry existed and was deleted.
   */
  delete(id: string): Promise<boolean>
  /** Return the number of entries in the store. */
  count(): Promise<number>
}
export type JsMemory = Memory

/**
 * Namespace for in-process-only workflow values.
 *
 * Values stored via `session.set` are kept in the
 * `ContextInner.objects` side-channel and are **excluded** from
 * snapshots. Use this for state that should not survive a
 * `pause()` / `resume()` round-trip (request IDs, rate-limit
 * counters, ephemeral caches, …).
 *
 * For `session.set` values, identity preservation of JS class
 * instances through this namespace is **not** supported on the Node
 * bindings (see the module-level note on napi-rs threading). Values
 * are serialised via `serde_json::Value`, so you will get a plain
 * object back on `session.get`.
 */
export declare class SessionNamespace {
  /**
   * Store a JSON-serializable value under the given key. The value
   * is excluded from snapshots.
   */
  set(key: string, value: unknown): Promise<void>
  /**
   * Retrieve a value previously stored under the given key. Returns
   * `null` if the key does not exist.
   */
  get(key: string): Promise<unknown>
  /** Check whether a value exists under the given key. */
  has(key: string): Promise<boolean>
  /** Remove the value stored under the given key. */
  remove(key: string): Promise<void>
}
export type JsSessionNamespace = SessionNamespace

/**
 * Namespace for persistable workflow state.
 *
 * Values stored via `state.set` / `state.setBytes` go into the
 * underlying `ContextInner.state` map and survive snapshots,
 * `pause()` / `resume()`, and checkpoint stores.
 */
export declare class StateNamespace {
  /** Store a JSON-serializable value under the given key. */
  set(key: string, value: Exclude<StateValue, Buffer>): Promise<void>
  /** Retrieve a value previously stored under the given key. */
  get(key: string): Promise<StateValue | null>
  /** Store raw binary data under the given key. */
  setBytes(key: string, data: Buffer): Promise<void>
  /** Retrieve raw binary data previously stored under the given key. */
  getBytes(key: string): Promise<Buffer | null>
}
export type JsStateNamespace = StateNamespace

/**
 * A Valkey/Redis-backed backend for the memory store.
 *
 * ```javascript
 * const backend = ValkeyBackend.create("redis://localhost:6379");
 * const memory = new Memory(embedder, backend);
 * ```
 */
export declare class ValkeyBackend {
  /**
   * Create a Valkey backend connected to the given Redis/Valkey URL.
   *
   * The URL should be in standard Redis format, e.g. `redis://localhost:6379`.
   */
  static create(url: string): ValkeyBackend
}
export type JsValkeyBackend = ValkeyBackend

/**
 * A workflow builder and runner.
 *
 * Create a workflow, add steps with async handler functions, then run it.
 *
 * ```javascript
 * const workflow = new Workflow("my-workflow");
 *
 * workflow.addStep("analyze", ["blazen::StartEvent"], async (event, ctx) => {
 *   const text = event.message;
 *   return { type: "blazen::StopEvent", result: { analyzed: text } };
 * });
 *
 * const result = await workflow.run({ message: "hello" });
 * ```
 */
export declare class Workflow {
  /** Create a new workflow with the given name. */
  constructor(name: string)
  /**
   * Add a step to the workflow.
   *
   * - `name`: Human-readable step name.
   * - `eventTypes`: Array of event type strings this step handles.
   * - `handler`: Async function `(event, ctx) => Event` that processes
   *   events and returns the next event.
   */
  addStep(name: string, eventTypes: Array<string>, handler: StepHandlerTsfn): void
  /**
   * Set the workflow timeout in seconds.
   *
   * Set to 0 or negative to disable the timeout.
   */
  setTimeout(seconds: number): void
  /**
   * Run the workflow with the given input data.
   *
   * The input is wrapped in a `StartEvent` automatically.
   * Returns the final result when the workflow completes via a `StopEvent`.
   */
  run(input: any): Promise<JsWorkflowResult>
  /**
   * Run the workflow with streaming.
   *
   * The `onEvent` callback receives intermediate events published via
   * `ctx.writeEventToStream()` from within step handlers.
   *
   * Returns the final result when the workflow completes.
   */
  runStreaming(input: any, onEvent: StreamCallbackTsfn): Promise<JsWorkflowResult>
  /**
   * Run the workflow and return a handler object.
   *
   * Unlike `run()` which awaits the result internally, this method
   * returns a `WorkflowHandler` that gives you control over the
   * running workflow:
   *
   * - Call `handler.result()` to await the final result.
   * - Call `handler.pause()` to pause and get a snapshot JSON string.
   * - Call `handler.streamEvents(cb)` to subscribe to intermediate events.
   *
   * ```javascript
   * const handler = await workflow.runWithHandler({ message: "hello" });
   * // ... later ...
   * const snapshot = await handler.pause();
   * ```
   */
  runWithHandler(input: any): Promise<WorkflowHandler>
  /**
   * Resume a previously paused workflow from a snapshot.
   *
   * The snapshot JSON string should have been obtained from a prior
   * call to `handler.pause()`. The workflow will resume with the same
   * steps that were registered on this `Workflow` instance.
   *
   * Returns a new `WorkflowHandler` for the resumed workflow.
   *
   * ```javascript
   * const snapshot = fs.readFileSync("snapshot.json", "utf-8");
   * const handler = await workflow.resume(snapshot);
   * const result = await handler.result();
   * ```
   */
  resume(snapshotJson: string): Promise<WorkflowHandler>
}
export type JsWorkflow = Workflow

/**
 * A handle to a running workflow.
 *
 * Returned by `Workflow.runWithHandler()`. Provides methods to:
 *
 * - **`result()`** -- await the final workflow result.
 * - **`pause()`** -- pause the workflow and get a snapshot JSON string.
 * - **`streamEvents(callback)`** -- subscribe to intermediate events
 *   published via `ctx.writeEventToStream()`.
 *
 * **Important:** `result()` and `pause()` each consume the handler
 * internally. You can only call one of them, and only once.
 *
 * ```javascript
 * const handler = await workflow.runWithHandler({ message: "hello" });
 *
 * // Option A: just get the result
 * const result = await handler.result();
 *
 * // Option B: pause and get a snapshot
 * const snapshot = await handler.pause();
 * fs.writeFileSync("snapshot.json", snapshot);
 *
 * // Option C: stream events, then get the result
 * handler.streamEvents((event) => console.log(event));
 * const result = await handler.result();
 * ```
 */
export declare class WorkflowHandler {
  /**
   * Await the final workflow result.
   *
   * Returns the result when the workflow completes via a `StopEvent`.
   *
   * This method consumes the handler internally -- it can only be called
   * once, and cannot be called after `pause()`.
   */
  result(): Promise<JsWorkflowResult>
  /**
   * Pause the running workflow and return a snapshot as a JSON string.
   *
   * The snapshot contains all workflow state and can be saved to a file
   * or database. Use `Workflow.resume(snapshotJson)` to resume later.
   *
   * This method consumes the handler internally -- it can only be called
   * once, and cannot be called after `result()`.
   */
  pause(): Promise<string>
  /**
   * Subscribe to intermediate events published by steps via
   * `ctx.writeEventToStream()`.
   *
   * The `onEvent` callback receives each event as a plain object.
   * This must be called **before** `result()` or `pause()`.
   *
   * Events published before this call are not replayed.
   */
  streamEvents(onEvent: StreamCallbackTsfn): Promise<void>
}
export type JsWorkflowHandler = WorkflowHandler

/** Options for creating a `ChatMessage`. */
export interface ChatMessageOptions {
  /** Role: "system", "user", "assistant", or "tool". Defaults to "user". */
  role?: string
  /** Text content. */
  content?: string
  /** Multimodal content parts (alternative to content). */
  parts?: Array<JsContentPart>
}

/**
 * Estimate the total token count for an array of chat messages.
 *
 * Includes per-message overhead (role markers, separators) and assistant
 * priming tokens, matching the overhead model used by `OpenAI`.
 *
 * `contextSize` defaults to 128 000 if not provided.
 *
 * ```javascript
 * const tokens = countMessageTokens([
 *   ChatMessage.system("You are helpful."),
 *   ChatMessage.user("Hi"),
 * ]);
 * ```
 */
export declare function countMessageTokens(messages: Array<ChatMessage>, contextSize?: number | undefined | null): number

/**
 * Estimate the number of tokens in a text string.
 *
 * Uses a heuristic (3.5 characters per token) that works everywhere without
 * external data files.  Good enough for budget checks when exact counts are
 * not critical.
 *
 * `contextSize` defaults to 128 000 if not provided.
 *
 * ```javascript
 * const tokens = estimateTokens("Hello world");
 * ```
 */
export declare function estimateTokens(text: string, contextSize?: number | undefined | null): number

/**
 * The fal.ai LLM endpoint family.
 *
 * Selects which fal LLM URL/body schema to use. Defaults to `OpenAiChat`
 * (the OpenAI-compatible chat-completions surface on fal).
 */
export declare const enum FalLlmEndpoint {
  /** OpenAI-compatible chat-completions endpoint (default). */
  OpenAiChat = 'openai_chat',
  /** OpenAI-compatible Responses endpoint. */
  OpenAiResponses = 'openai_responses',
  /** OpenAI-compatible embeddings endpoint. */
  OpenAiEmbeddings = 'openai_embeddings',
  /** `OpenRouter` proxy via fal. */
  OpenRouter = 'openrouter',
  /** `OpenRouter` proxy via fal (enterprise/SOC2 tier). */
  OpenRouterEnterprise = 'openrouter_enterprise',
  /** fal-ai/any-llm proxy. */
  AnyLlm = 'any_llm',
  /** fal-ai/any-llm proxy (enterprise/SOC2 tier). */
  AnyLlmEnterprise = 'any_llm_enterprise'
}

/** An entry to add to the memory store (used by `addMany`). */
export interface JsAddEntry {
  /** Unique identifier. If empty, one will be generated. */
  id: string
  /** The text content to store. */
  text: string
  /** Optional arbitrary metadata. */
  metadata?: any
}

/** The result of an agent run. */
export interface JsAgentResult {
  /** The final completion response from the model. */
  response: JsCompletionResponse
  /** Full message history including all tool calls and results. */
  messages: Array<any>
  /** Number of tool-calling iterations that occurred. */
  iterations: number
  /** Aggregated cost across all iterations, if available. */
  totalCost?: number
}

/** Options for configuring an agent run. */
export interface JsAgentRunOptions {
  /**
   * Maximum number of tool-calling iterations before forcing a final answer.
   * Defaults to 10.
   */
  maxIterations?: number
  /** Optional system prompt prepended to the conversation. */
  systemPrompt?: string
  /** Sampling temperature (0.0 - 2.0). */
  temperature?: number
  /** Maximum tokens per completion call. */
  maxTokens?: number
  /**
   * Whether to add a built-in "finish" tool that the model can call to
   * signal it has a final answer.
   */
  addFinishTool?: boolean
}

/**
 * A typed artifact extracted from or returned by a model.
 *
 * SVG / code blocks / markdown / mermaid / html / latex / json / custom payloads
 * can be returned inline as text by an LLM. Use the `kind` field to discriminate,
 * then read the variant-specific fields. Fields not relevant to the variant are
 * `null`.
 *
 * ## Example
 * ```ts
 * for (const art of response.artifacts) {
 *   if (art.kind === "svg") {
 *     renderSvg(art.content as string);
 *   } else if (art.kind === "code_block") {
 *     console.log(`${art.language}: ${art.content}`);
 *   }
 * }
 * ```
 */
export interface JsArtifact {
  /**
   * Discriminator. One of: `"svg"`, `"code_block"`, `"markdown"`, `"mermaid"`,
   * `"html"`, `"latex"`, `"json"`, `"custom"`.
   */
  kind: string
  /**
   * The artifact's primary payload. Typically a string; for the `json`
   * variant it is a parsed JSON value (object/array/scalar).
   */
  content: any
  /** Optional title for `svg` artifacts. */
  title?: string
  /** Language hint for `code_block` artifacts. */
  language?: string
  /** Filename hint for `code_block` artifacts. */
  filename?: string
  /** Provider-specific metadata for `custom` artifacts. */
  metadata?: any
  /**
   * Inner `kind` tag for `custom` artifacts. Distinct from the top-level
   * `kind` field (which equals `"custom"` for this variant).
   */
  customKind?: string
}

/** Audio content for multimodal messages. */
export interface JsAudioContent {
  source: JsImageSource
  mediaType?: string
  durationSeconds?: number
}

/** Result of an audio generation or TTS operation. */
export interface JsAudioResult {
  /** The generated audio clips. */
  audio: Array<JsGeneratedAudio>
  /** Request timing breakdown. */
  timing?: JsComputeTiming
  /** Cost in USD, if reported by the provider. */
  cost?: number
  /** Arbitrary provider-specific metadata. */
  metadata: any
}

/** Configuration for the `withCache` decorator. */
export interface JsCacheConfig {
  /** How long a cached response remains valid, in seconds. */
  ttlSeconds?: number
  /** Maximum number of entries to keep in the cache. */
  maxEntries?: number
}

/**
 * A web/document citation backing a model statement.
 *
 * Populated by Perplexity (`citations` array), Gemini (`groundingMetadata`),
 * and any provider that returns retrieval-augmented citations.
 */
export interface JsCitation {
  /** The cited URL. */
  url: string
  /** Document or web-page title, if available. */
  title?: string
  /** Excerpt/snippet from the source. */
  snippet?: string
  /** Byte offset in the response text where this citation starts. */
  start?: number
  /** Byte offset in the response text where this citation ends. */
  end?: number
  /** Optional document id (for retrieval-augmented citations). */
  documentId?: string
  /** Provider-specific extra fields preserved as JSON. */
  metadata: any
}

/** Options for a chat completion request. */
export interface JsCompletionOptions {
  temperature?: number
  maxTokens?: number
  topP?: number
  model?: string
  tools?: Array<JsToolDefinition>
  /** JSON Schema for structured output / response format. */
  responseFormat?: any
}

/** The result of a chat completion. */
export interface JsCompletionResponse {
  content?: string
  toolCalls: Array<JsToolCall>
  usage?: JsTokenUsage
  model: string
  finishReason?: string
  cost?: number
  timing?: JsRequestTiming
  images: Array<any>
  audio: Array<any>
  videos: Array<any>
  reasoning?: JsReasoningTrace
  citations: Array<JsCitation>
  artifacts: Array<JsArtifact>
  metadata: any
}

/** Input for a generic compute job. */
export interface JsComputeRequest {
  /** The model/endpoint to run (e.g., "fal-ai/flux/dev"). */
  model: string
  /** Input parameters as JSON (model-specific). */
  input: any
  /** Optional webhook URL for async completion notification. */
  webhook?: string
}

/** Result of a completed compute job. */
export interface JsComputeResult {
  /** The job handle that produced this result, if available. */
  job?: JsJobHandle
  /** Output data (model-specific JSON). */
  output: any
  /** Request timing breakdown. */
  timing?: JsComputeTiming
  /** Cost in USD, if reported by the provider. */
  cost?: number
  /** Raw provider-specific metadata. */
  metadata: any
}

/** Timing breakdown for a compute request. */
export interface JsComputeTiming {
  /** Time spent waiting in queue, in milliseconds. */
  queueMs?: number
  /** Time spent executing, in milliseconds. */
  executionMs?: number
  /** Total wall-clock time, in milliseconds. */
  totalMs?: number
}

/**
 * A single part in a multi-part message.
 *
 * `partType` is one of `"text"`, `"image"`, `"audio"`, `"video"`. Set the
 * matching field (`text`, `image`, `audio`, `video`) accordingly.
 */
export interface JsContentPart {
  partType: string
  text?: string
  image?: JsImageContent
  audio?: JsAudioContent
  video?: JsVideoContent
}

/** The result of an embedding operation. */
export interface JsEmbeddingResponse {
  /** The embedding vectors (one per input text). */
  embeddings: Array<Array<number>>
  /** The model that produced these embeddings. */
  model: string
  /** Token usage statistics, if available. */
  usage?: JsTokenUsage
  /** Estimated cost in USD, if available. */
  cost?: number
  /** Request timing breakdown, if available. */
  timing?: JsRequestTiming
  /** Provider-specific metadata. */
  metadata: any
}

/**
 * Configuration options for [`JsFalProvider`].
 *
 * ```typescript
 * const fal = FalProvider.create("fal-key-...", {
 *   model: "anthropic/claude-sonnet-4.5",
 *   endpoint: "openai_chat",
 *   enterprise: false,
 *   autoRouteModality: true,
 * });
 * ```
 */
export interface JsFalOptions {
  /** Underlying LLM model name (e.g. `"anthropic/claude-sonnet-4.5"`). */
  model?: string
  /** The fal endpoint family to target. Defaults to `OpenAiChat`. */
  endpoint?: FalLlmEndpoint
  /** Promote the endpoint to its enterprise / SOC2-eligible variant. */
  enterprise?: boolean
  /**
   * Auto-route the request to the matching vision/audio/video variant
   * when the message content contains media. Defaults to `true`.
   */
  autoRouteModality?: boolean
}

/**
 * Normalized finish reason across providers.
 *
 * Maps provider-specific finish-reason strings (`"stop"`, `"end_turn"`,
 * `"STOP"`, `"length"`, `"tool_calls"`, `"max_tokens"`, etc.) into a canonical
 * set. Unknown values fall through to `kind == "other"`.
 *
 * Use `kind` for the canonical category and `value` for the original
 * provider string.
 */
export interface JsFinishReason {
  /**
   * Canonical category. One of: `"stop"`, `"length"`, `"tool_calls"`,
   * `"content_filter"`, `"safety"`, `"end_turn"`, `"stop_sequence"`,
   * `"max_tokens"`, `"error"`, or `"other"`.
   */
  kind: string
  /**
   * Raw provider string. Equals `kind` for canonical variants; for `Other(s)`
   * it preserves the original string.
   */
  value: string
}

/** A single generated 3D model with optional mesh metadata. */
export interface JsGenerated3DModel {
  /** The 3D model media output. */
  media: JsMediaOutput
  /** Total vertex count, if known. */
  vertexCount?: number
  /** Total face/triangle count, if known. */
  faceCount?: number
  /** Whether the model includes texture data. */
  hasTextures: boolean
  /** Whether the model includes animation data. */
  hasAnimations: boolean
}

/** A single generated audio clip with optional metadata. */
export interface JsGeneratedAudio {
  /** The audio media output. */
  media: JsMediaOutput
  /** Duration in seconds, if known. */
  durationSeconds?: number
  /** Sample rate in Hz, if known. */
  sampleRate?: number
  /** Number of audio channels, if known. */
  channels?: number
}

/** A single generated image with optional dimension metadata. */
export interface JsGeneratedImage {
  /** The image media output. */
  media: JsMediaOutput
  /** Image width in pixels, if known. */
  width?: number
  /** Image height in pixels, if known. */
  height?: number
}

/** A single generated video with optional metadata. */
export interface JsGeneratedVideo {
  /** The video media output. */
  media: JsMediaOutput
  /** Video width in pixels, if known. */
  width?: number
  /** Video height in pixels, if known. */
  height?: number
  /** Duration in seconds, if known. */
  durationSeconds?: number
  /** Frames per second, if known. */
  fps?: number
}

/** Image content for multimodal messages. */
export interface JsImageContent {
  source: JsImageSource
  mediaType?: string
}

/** Request to generate images from a text prompt. */
export interface JsImageRequest {
  /** The text prompt describing the desired image. */
  prompt: string
  /** Negative prompt (things to avoid in the image). */
  negativePrompt?: string
  /** Desired image width in pixels. */
  width?: number
  /** Desired image height in pixels. */
  height?: number
  /** Number of images to generate. */
  numImages?: number
  /** Model override (provider-specific model identifier). */
  model?: string
  /** Additional provider-specific parameters. */
  parameters?: any
}

/** Result of an image generation or upscale operation. */
export interface JsImageResult {
  /** The generated or upscaled images. */
  images: Array<JsGeneratedImage>
  /** Request timing breakdown. */
  timing?: JsComputeTiming
  /** Cost in USD, if reported by the provider. */
  cost?: number
  /** Arbitrary provider-specific metadata. */
  metadata: any
}

/** How an image is provided (URL or base64). */
export interface JsImageSource {
  sourceType: string
  url?: string
  data?: string
}

/** A handle to a submitted compute job. */
export interface JsJobHandle {
  /** Provider-assigned job/request identifier. */
  id: string
  /** Provider name (e.g., "fal", "replicate", "runpod"). */
  provider: string
  /** The model/endpoint that was invoked. */
  model: string
  /** When the job was submitted (ISO 8601). */
  submittedAt: string
}

/** Status of a compute job. */
export declare const enum JsJobStatus {
  /** Job is waiting in the provider's queue. */
  Queued = 'queued',
  /** Job is currently executing. */
  Running = 'running',
  /** Job completed successfully. */
  Completed = 'completed',
  /** Job failed with an error. */
  Failed = 'failed',
  /** Job was cancelled. */
  Cancelled = 'cancelled'
}

/** A single piece of generated media content. */
export interface JsMediaOutput {
  /** URL where the media can be downloaded. */
  url?: string
  /** Base64-encoded media data. */
  base64?: string
  /** Raw text content for text-based formats (SVG, OBJ, GLTF JSON). */
  rawContent?: string
  /** The MIME type of the media (e.g. "image/png", "video/mp4"). */
  mediaType: string
  /** File size in bytes, if known. */
  fileSize?: number
  /** Arbitrary provider-specific metadata. */
  metadata: any
}

/** Map of friendly format names to their MIME type strings. */
export interface JsMediaTypeMap {
  png: string
  jpeg: string
  webp: string
  gif: string
  svg: string
  bmp: string
  tiff: string
  avif: string
  ico: string
  mp4: string
  webm: string
  mov: string
  avi: string
  mkv: string
  mp3: string
  wav: string
  ogg: string
  flac: string
  aac: string
  m4A: string
  glb: string
  gltf: string
  obj: string
  fbx: string
  usdz: string
  stl: string
  ply: string
  pdf: string
}

/** A stored entry retrieved from the memory store. */
export interface JsMemoryEntry {
  /** The entry id. */
  id: string
  /** The original text content. */
  text: string
  /** Arbitrary user metadata. */
  metadata: any
}

/** A search result from the memory store. */
export interface JsMemoryResult {
  /** The entry id. */
  id: string
  /** The original text content. */
  text: string
  /** Similarity score in 0.0..=1.0 (higher = more similar). */
  score: number
  /** Arbitrary user metadata. */
  metadata: any
}

/** Request to generate music or sound effects. */
export interface JsMusicRequest {
  /** Text prompt describing the desired audio. */
  prompt: string
  /** Desired duration in seconds. */
  durationSeconds?: number
  /** Model override. */
  model?: string
  /** Additional provider-specific parameters. */
  parameters?: any
}

/**
 * Chain-of-thought / extended-thinking trace from a model that exposes one.
 *
 * Populated by Anthropic extended thinking, `DeepSeek` R1 `reasoning_content`,
 * `OpenAI` o-series, xAI Grok reasoning, and Gemini thoughts.
 */
export interface JsReasoningTrace {
  /** Plain-text rendering of the reasoning content. */
  text: string
  /** Provider-specific signature/redaction handle, if any (Anthropic). */
  signature?: string
  /** Whether the trace was redacted by the provider. */
  redacted: boolean
  /**
   * Reasoning effort level if the provider exposes one
   * (e.g. `"low"`, `"medium"`, `"high"`).
   */
  effort?: string
}

/** Timing metadata for a completion request. */
export interface JsRequestTiming {
  queueMs?: number
  executionMs?: number
  totalMs?: number
}

/**
 * Typed response-format hint for structured output.
 *
 * Use one of the variants by setting `kind` to `"text"`, `"json_object"`, or
 * `"json_schema"`. For `"json_schema"`, populate `schemaName`, `schema`, and
 * optionally `strict`.
 */
export interface JsResponseFormat {
  /** Discriminator. One of `"text"`, `"json_object"`, `"json_schema"`. */
  kind: string
  /** Schema name for `json_schema` variants. */
  schemaName?: string
  /** Schema body for `json_schema` variants. */
  schema?: any
  /** Whether the schema is strict (`json_schema` variants only). */
  strict?: boolean
}

/** Configuration for the `withRetry` decorator. */
export interface JsRetryConfig {
  /** Maximum number of retry attempts (total calls = `maxRetries + 1`). */
  maxRetries?: number
  /** Delay before the first retry, in milliseconds. */
  initialDelayMs?: number
  /** Upper bound on the computed backoff delay, in milliseconds. */
  maxDelayMs?: number
}

/** The role of a participant in a chat conversation. */
export declare const enum JsRole {
  System = 'system',
  User = 'user',
  Assistant = 'assistant',
  Tool = 'tool'
}

/** Request to generate speech from text (TTS). */
export interface JsSpeechRequest {
  /** The text to synthesize into speech. */
  text: string
  /** Voice identifier (provider-specific). */
  voice?: string
  /** URL to a reference voice sample for voice cloning. */
  voiceUrl?: string
  /** Language code (e.g. "en", "fr", "ja"). */
  language?: string
  /** Speech speed multiplier (1.0 = normal). */
  speed?: number
  /** Model override. */
  model?: string
  /** Additional provider-specific parameters. */
  parameters?: any
}

/**
 * A single chunk from a streaming completion response.
 *
 * Passed to the `onChunk` callback during streaming operations.
 *
 * ```javascript
 * await model.stream(
 *   [ChatMessage.user("Tell me a story")],
 *   (chunk) => {
 *     if (chunk.delta) process.stdout.write(chunk.delta);
 *     if (chunk.finishReason) console.log("done:", chunk.finishReason);
 *   }
 * );
 * ```
 */
export interface JsStreamChunk {
  /** Incremental text content, if any. */
  delta?: string
  /**
   * The reason the model stopped generating (`"stop"`, `"tool_use"`, etc.).
   * Present only in the final chunk.
   */
  finishReason?: string
  /** Tool invocations completed in this chunk. */
  toolCalls: Array<JsToolCall>
  /**
   * Reasoning text delta from models that stream a chain-of-thought trace
   * (Anthropic extended thinking, `DeepSeek` R1, `OpenAI` o-series).
   */
  reasoningDelta?: string
  /** Citations completed in this chunk. */
  citations: Array<JsCitation>
  /** Artifacts completed in this chunk. */
  artifacts: Array<JsArtifact>
}

/** Request to generate a 3D model. */
export interface JsThreeDRequest {
  /** Text prompt describing the desired 3D model. */
  prompt?: string
  /** Source image URL for image-to-3D generation. */
  imageUrl?: string
  /** Desired output format (e.g. "glb", "obj", "usdz"). */
  format?: string
  /** Model override. */
  model?: string
  /** Additional provider-specific parameters. */
  parameters?: any
}

/** Result of a 3D model generation operation. */
export interface JsThreeDResult {
  /** The generated 3D models. */
  models: Array<JsGenerated3DModel>
  /** Request timing breakdown. */
  timing?: JsComputeTiming
  /** Cost in USD, if reported by the provider. */
  cost?: number
  /** Arbitrary provider-specific metadata. */
  metadata: any
}

/** Token usage statistics for a completion request. */
export interface JsTokenUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
}

/** A tool invocation requested by the model. */
export interface JsToolCall {
  id: string
  name: string
  arguments: any
}

/** Describes a tool that the agent may invoke during its execution loop. */
export interface JsToolDef {
  /** The unique name of the tool. */
  name: string
  /** A human-readable description of what the tool does. */
  description: string
  /** JSON Schema describing the tool's parameters. */
  parameters: any
}

/** Describes a tool that the model may invoke during a conversation. */
export interface JsToolDefinition {
  name: string
  description: string
  parameters: any
}

/** Request to transcribe audio to text. */
export interface JsTranscriptionRequest {
  /** URL of the audio file to transcribe. */
  audioUrl: string
  /** Language hint (e.g. "en", "fr"). */
  language?: string
  /** Whether to perform speaker diarization. */
  diarize?: boolean
  /** Model override. */
  model?: string
  /** Additional provider-specific parameters. */
  parameters?: any
}

/** Result of a transcription operation. */
export interface JsTranscriptionResult {
  /** The full transcribed text. */
  text: string
  /** Time-aligned segments, if available. */
  segments: Array<JsTranscriptionSegment>
  /** Detected or specified language code (e.g. "en", "fr"). */
  language?: string
  /** Request timing breakdown. */
  timing?: JsComputeTiming
  /** Cost in USD, if reported by the provider. */
  cost?: number
  /** Arbitrary provider-specific metadata. */
  metadata: any
}

/** A single segment within a transcription. */
export interface JsTranscriptionSegment {
  /** The transcribed text for this segment. */
  text: string
  /** Start time in seconds. */
  start: number
  /** End time in seconds. */
  end: number
  /** Speaker label, if diarization was enabled. */
  speaker?: string
}

/** Request to upscale an image. */
export interface JsUpscaleRequest {
  /** URL of the image to upscale. */
  imageUrl: string
  /** Scale factor (e.g., 2.0 for 2x, 4.0 for 4x). */
  scale: number
  /** Model override. */
  model?: string
  /** Additional provider-specific parameters. */
  parameters?: any
}

/** Video content for multimodal messages. */
export interface JsVideoContent {
  source: JsImageSource
  mediaType?: string
  durationSeconds?: number
}

/** Request to generate a video. */
export interface JsVideoRequest {
  /** Text prompt describing the desired video. */
  prompt: string
  /** Source image URL for image-to-video generation. */
  imageUrl?: string
  /** Desired duration in seconds. */
  durationSeconds?: number
  /** Negative prompt (things to avoid). */
  negativePrompt?: string
  /** Desired video width in pixels. */
  width?: number
  /** Desired video height in pixels. */
  height?: number
  /** Model override. */
  model?: string
  /** Additional provider-specific parameters. */
  parameters?: any
}

/** Result of a video generation operation. */
export interface JsVideoResult {
  /** The generated videos. */
  videos: Array<JsGeneratedVideo>
  /** Request timing breakdown. */
  timing?: JsComputeTiming
  /** Cost in USD, if reported by the provider. */
  cost?: number
  /** Arbitrary provider-specific metadata. */
  metadata: any
}

/** The result of a workflow run. */
export interface JsWorkflowResult {
  /** The event type of the final result (typically "`blazen::StopEvent`"). */
  type: string
  /** The result data as a JSON object. */
  data: any
}

/**
 * Returns an object mapping friendly names to MIME type strings.
 *
 * ```typescript
 * import { mediaTypes } from 'blazen';
 *
 * const types = mediaTypes();
 * console.log(types.png);  // "image/png"
 * console.log(types.mp4);  // "video/mp4"
 * ```
 */
export declare function mediaTypes(): JsMediaTypeMap

/**
 * Run an agentic tool execution loop.
 *
 * The agent repeatedly calls the model, executes any tool calls via the
 * `toolHandler` callback, feeds results back, and repeats until the model
 * stops calling tools or `maxIterations` is reached.
 *
 * The `toolHandler` callback receives `(toolName: string, arguments: object)`
 * and must return the tool result as a JSON-serializable value (or a Promise
 * that resolves to one).
 *
 * ```typescript
 * import { CompletionModel, ChatMessage, runAgent } from 'blazen';
 *
 * const model = CompletionModel.openai("sk-...");
 *
 * const result = await runAgent(
 *   model,
 *   [ChatMessage.user("What is the weather in NYC?")],
 *   [{ name: "getWeather", description: "Get weather", parameters: { type: "object", properties: { city: { type: "string" } }, required: ["city"] } }],
 *   async (toolName, args) => {
 *     if (toolName === "getWeather") return { temp: 72, condition: "sunny" };
 *     throw new Error(`Unknown tool: ${toolName}`);
 *   },
 *   { maxIterations: 5 }
 * );
 * ```
 */
export declare function runAgent(model: JsCompletionModel, messages: Array<JsChatMessage>, tools: Array<JsToolDef>, toolHandler: ToolHandlerTsfn, options?: JsAgentRunOptions | undefined | null): Promise<JsAgentResult>

/** Returns the version of the blazen library. */
export declare function version(): string
