/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A single message in a chat conversation. */
export declare class ChatMessage {
  /**
   * Create a new chat message from an options object.
   *
   * `role` defaults to `"user"` if not provided.
   * Supply either `content` (text) or `parts` (multimodal).
   */
  constructor(options: ChatMessageOptions)
  /** Create a system message. */
  static system(content: string): ChatMessage
  /** Create a user message. */
  static user(content: string): ChatMessage
  /** Create an assistant message. */
  static assistant(content: string): ChatMessage
  /** Create a tool result message. */
  static tool(content: string): ChatMessage
  /** Create a user message containing text and an image from a URL. */
  static userImageUrl(text: string, url: string, mediaType?: string | undefined | null): ChatMessage
  /** Create a user message containing text and a base64-encoded image. */
  static userImageBase64(text: string, data: string, mediaType: string): ChatMessage
  /** Create a user message containing text and an audio clip from a URL. */
  static userAudio(text: string, url: string): ChatMessage
  /** Create a user message containing text and base64-encoded audio data. */
  static userAudioBase64(text: string, data: string, mediaType: string): ChatMessage
  /** Create a user message containing text and a video clip from a URL. */
  static userVideo(text: string, url: string): ChatMessage
  /** Create a user message containing text and base64-encoded video data. */
  static userVideoBase64(text: string, data: string, mediaType: string): ChatMessage
  /** Create a user message from an explicit list of content parts. */
  static userParts(parts: Array<JsContentPart>): ChatMessage
  /** The role of the message author. */
  get role(): string
  /** The text content of the message, if any. */
  get content(): string | null
}
export type JsChatMessage = ChatMessage

/**
 * A token-windowed conversation memory.
 *
 * Holds a sequence of `ChatMessage` objects and automatically evicts the
 * oldest messages (preserving system messages) when the token count exceeds
 * the configured budget.
 *
 * ```javascript
 * const window = new ChatWindow(4096);
 * window.add(ChatMessage.system("You are helpful."));
 * window.add(ChatMessage.user("Hello!"));
 * console.log(window.tokenCount());
 * console.log(window.remainingTokens());
 * ```
 */
export declare class ChatWindow {
  /**
   * Create a new chat window with the given token budget.
   *
   * @param maxTokens - The maximum number of tokens to allow in the window.
   */
  constructor(maxTokens: number)
  /**
   * Append a message to the window.
   *
   * If the token count exceeds the budget after adding the message,
   * the oldest non-system messages are evicted until within budget.
   * System messages are never evicted.
   *
   * @param message - A `ChatMessage` to add.
   */
  add(message: JsChatMessage): void
  /**
   * Get the current messages in the window.
   *
   * @returns An array of `ChatMessage` objects.
   */
  messages(): Array<JsChatMessage>
  /** Remove all messages from the window. */
  clear(): void
  /**
   * Estimate the total token count of all messages in the window.
   *
   * @returns The estimated number of tokens.
   */
  tokenCount(): number
  /**
   * Return the number of tokens remaining before the budget is reached.
   *
   * @returns The number of tokens remaining (0 if already at or over budget).
   */
  remainingTokens(): number
  /** Return the number of messages in the window. */
  get length(): number
}
export type JsChatWindow = ChatWindow

/**
 * A chat completion model.
 *
 * Use the static factory methods to create an instance for your provider:
 *
 * ```javascript
 * const model = CompletionModel.openai("sk-...");
 * const response = await model.complete([
 *   ChatMessage.user("What is 2 + 2?")
 * ]);
 * ```
 */
export declare class CompletionModel {
  /** Create an `OpenAI` completion model. */
  static openai(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create an Anthropic completion model. */
  static anthropic(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a Google Gemini completion model. */
  static gemini(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create an Azure `OpenAI` completion model. */
  static azure(options: JsAzureOptions): CompletionModel
  /**
   * Create a fal.ai completion model.
   *
   * `options` optionally configures the LLM model, endpoint family,
   * enterprise tier, and modality auto-routing. Defaults to the
   * OpenAI-compatible chat-completions endpoint.
   */
  static fal(options?: JsFalOptions | undefined | null): CompletionModel
  /** Create an `OpenRouter` completion model. */
  static openrouter(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a Groq completion model. */
  static groq(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a Together AI completion model. */
  static together(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a Mistral AI completion model. */
  static mistral(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a `DeepSeek` completion model. */
  static deepseek(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a Fireworks AI completion model. */
  static fireworks(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a Perplexity completion model. */
  static perplexity(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create an xAI (Grok) completion model. */
  static xai(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create a Cohere completion model. */
  static cohere(options?: JsProviderOptions | undefined | null): CompletionModel
  /** Create an AWS Bedrock completion model. */
  static bedrock(options: JsBedrockOptions): CompletionModel
  /** Get the model ID. */
  get modelId(): string
  /**
   * Wrap this model with automatic retry on transient failures.
   *
   * ```javascript
   * const model = CompletionModel.openrouter(key);
   * const withRetry = model.withRetry({ maxRetries: 3, initialDelayMs: 1000 });
   * ```
   */
  withRetry(config?: JsRetryConfig | undefined | null): CompletionModel
  /**
   * Wrap this model with an in-memory response cache.
   *
   * Streaming requests are never cached and always delegate directly to the
   * underlying model.
   *
   * ```javascript
   * const cached = model.withCache({ ttlSeconds: 300, maxEntries: 1000 });
   * ```
   */
  withCache(config?: JsCacheConfig | undefined | null): CompletionModel
  /**
   * Create a fallback model that tries multiple providers in order.
   *
   * When the primary provider fails with a transient error (rate limit,
   * timeout, server error) the request is automatically forwarded to the
   * next provider. Non-retryable errors short-circuit immediately.
   *
   * ```javascript
   * const model = CompletionModel.withFallback([modelA, modelB]);
   * ```
   */
  static withFallback(models: Array<CompletionModel>): CompletionModel
  /**
   * Perform a chat completion.
   *
   * Messages should be an array of `ChatMessage` instances.
   *
   * Returns a typed response with `content`, `toolCalls`, `usage`, `model`,
   * and `finishReason` fields.
   */
  complete(messages: Array<JsChatMessage>): Promise<JsCompletionResponse>
  /**
   * Perform a chat completion with additional options.
   *
   * Options object may include:
   * - `temperature` (number): Sampling temperature (0.0 - 2.0)
   * - `maxTokens` (number): Maximum tokens to generate
   * - `topP` (number): Nucleus sampling parameter
   * - `model` (string): Override the default model
   * - `tools` (array): Tool definitions for function calling
   */
  completeWithOptions(messages: Array<JsChatMessage>, options: JsCompletionOptions): Promise<JsCompletionResponse>
  /**
   * Stream a chat completion.
   *
   * The `onChunk` callback receives each chunk as a typed `StreamChunk` with
   * `delta`, `finishReason`, and `toolCalls` fields.
   *
   * ```javascript
   * await model.stream(
   *   [ChatMessage.user("Tell me a story")],
   *   (chunk) => { if (chunk.delta) process.stdout.write(chunk.delta); }
   * );
   * ```
   */
  stream(messages: Array<JsChatMessage>, onChunk: StreamChunkCallbackTsfn): Promise<void>
  /**
   * Stream a chat completion with additional options.
   *
   * Options object may include:
   * - `temperature` (number): Sampling temperature (0.0 - 2.0)
   * - `maxTokens` (number): Maximum tokens to generate
   * - `topP` (number): Nucleus sampling parameter
   * - `model` (string): Override the default model
   * - `tools` (array): Tool definitions for function calling
   */
  streamWithOptions(messages: Array<JsChatMessage>, onChunk: StreamChunkCallbackTsfn, options: JsCompletionOptions): Promise<void>
}
export type JsCompletionModel = CompletionModel

/**
 * Shared workflow context accessible by all steps.
 *
 * Provides typed key/value storage, event emission, and stream publishing.
 * Use `set()` for JSON-serializable values, `setBytes()` for binary data.
 * `get()` returns the correct type for any stored value.
 */
export declare class Context {
  /**
   * Store a JSON-serializable value under the given key.
   *
   * For binary data (Buffer/Uint8Array), use `setBytes()` instead.
   */
  set(key: string, value: Exclude<StateValue, Buffer>): Promise<void>
  /**
   * Retrieve a value previously stored under the given key.
   *
   * Returns `Buffer` for binary data, the original JS value for JSON data,
   * or `null` if the key does not exist.
   */
  get(key: string): Promise<StateValue | null>
  /**
   * Emit an event into the internal routing queue.
   *
   * The event will be routed to any step whose `eventTypes` list includes
   * its event type. The event object must have a `type` field.
   */
  sendEvent(event: any): Promise<void>
  /**
   * Publish an event to the external broadcast stream.
   *
   * Consumers that subscribed via streaming will receive this event.
   * Unlike `sendEvent`, this does NOT route the event through the
   * internal step registry.
   */
  writeEventToStream(event: any): Promise<void>
  /**
   * Store raw binary data under the given key.
   *
   * Use this for Buffer/Uint8Array data that should be stored as binary
   * and returned as Buffer from `getBytes()`.
   */
  setBytes(key: string, data: Buffer): Promise<void>
  /**
   * Retrieve raw binary data previously stored under the given key.
   *
   * Returns `null` if the key does not exist or the stored value is
   * not binary data.
   */
  getBytes(key: string): Promise<Buffer | null>
  /** Get the workflow run ID. */
  runId(): Promise<string>
  /**
   * Persistable workflow state. Survives `pause()` / `resume()`,
   * checkpoints, and durable storage.
   *
   * ```javascript
   * await ctx.state.set("counter", 5);
   * const count = await ctx.state.get("counter");
   * ```
   */
  get state(): JsStateNamespace
  /**
   * In-process-only values. Excluded from snapshots — use this for
   * things that should not survive `pause()` / `resume()`.
   *
   * ```javascript
   * await ctx.session.set("reqId", 42);
   * const n = await ctx.session.get("reqId");
   * ```
   */
  get session(): JsSessionNamespace
}
export type JsContext = Context

/**
 * An embedding model that produces vector representations of text.
 *
 * Use the static factory methods to create an instance for your provider:
 *
 * ```javascript
 * const model = EmbeddingModel.openai("sk-...");
 * const response = await model.embed(["Hello", "World"]);
 * console.log(response.embeddings); // [[0.1, ...], [0.3, ...]]
 * ```
 */
export declare class EmbeddingModel {
  /**
   * Create an `OpenAI` embedding model.
   *
   * Defaults to `text-embedding-3-small` (1536 dimensions).
   */
  static openai(apiKey: string): EmbeddingModel
  /**
   * Create a Together AI embedding model.
   *
   * Defaults to `togethercomputer/m2-bert-80M-8k-retrieval` (768 dimensions).
   */
  static together(apiKey: string): EmbeddingModel
  /**
   * Create a Cohere embedding model.
   *
   * Defaults to `embed-v4.0` (1024 dimensions).
   */
  static cohere(apiKey: string): EmbeddingModel
  /**
   * Create a Fireworks AI embedding model.
   *
   * Defaults to `nomic-ai/nomic-embed-text-v1.5` (768 dimensions).
   */
  static fireworks(apiKey: string): EmbeddingModel
  /** The model identifier. */
  get modelId(): string
  /** The dimensionality of the embedding vectors produced by this model. */
  get dimensions(): number
  /** Embed one or more texts, returning one vector per input text. */
  embed(texts: Array<string>): Promise<JsEmbeddingResponse>
}
export type JsEmbeddingModel = EmbeddingModel

/**
 * A fal.ai embedding model.
 *
 * Wraps [`FalEmbeddingModel`] and exposes the
 * [`EmbeddingModel`](blazen_llm::EmbeddingModel) interface to JavaScript.
 * Constructed via [`JsFalProvider::embedding_model`].
 *
 * ```typescript
 * const fal = FalProvider.create();
 * const em = fal.embeddingModel();
 * const vectors = await em.embed(["hello", "world"]);
 * console.log(vectors.length); // 2
 * ```
 */
export declare class FalEmbeddingModel {
  /** Get the underlying embedding model id. */
  get modelId(): string
  /** Get the dimensionality of the produced embedding vectors. */
  get dimensions(): number
  /**
   * Embed one or more texts.
   *
   * Returns a list of embedding vectors (one per input text).
   */
  embed(texts: Array<string>): Promise<Array<Array<number>>>
}
export type JsFalEmbeddingModel = FalEmbeddingModel

/**
 * A fal.ai compute platform provider with image, video, audio, transcription,
 * and LLM capabilities.
 *
 * ```typescript
 * const fal = FalProvider.create();
 * const result = await fal.generateImage({ prompt: "a sunset" });
 * const response = await fal.complete([ChatMessage.user("Hi")]);
 * ```
 */
export declare class FalProvider {
  /**
   * Create a new fal.ai provider.
   *
   * `options` optionally configures the LLM model, endpoint family,
   * enterprise tier, and modality auto-routing. Defaults to the
   * OpenAI-compatible chat-completions endpoint (`OpenAiChat`).
   */
  static create(options?: JsFalOptions | undefined | null): FalProvider
  /** Get the model ID. */
  get modelId(): string
  /** Generate images from a text prompt. */
  generateImage(request: JsImageRequest): Promise<JsImageResult>
  /** Upscale an image. */
  upscaleImage(request: JsUpscaleRequest): Promise<JsImageResult>
  /** Upscale an image via the aura-sr model. */
  upscaleImageAura(request: JsUpscaleRequest): Promise<JsImageResult>
  /** Upscale an image via the clarity-upscaler model. */
  upscaleImageClarity(request: JsUpscaleRequest): Promise<JsImageResult>
  /** Upscale an image via the creative-upscaler model. */
  upscaleImageCreative(request: JsUpscaleRequest): Promise<JsImageResult>
  /** Remove the background from an image. */
  removeBackground(request: JsBackgroundRemovalRequest): Promise<JsImageResult>
  /** Generate a 3D model from a text prompt or source image. */
  generate3d(request: JsThreeDRequest): Promise<JsThreeDResult>
  /**
   * Build a [`JsFalEmbeddingModel`] sharing this provider's HTTP client
   * and API key.
   */
  embeddingModel(): JsFalEmbeddingModel
  /** Generate a video from a text prompt. */
  textToVideo(request: JsVideoRequest): Promise<JsVideoResult>
  /** Generate a video from a source image and prompt. */
  imageToVideo(request: JsVideoRequest): Promise<JsVideoResult>
  /** Synthesize speech from text. */
  textToSpeech(request: JsSpeechRequest): Promise<JsAudioResult>
  /** Generate music from a prompt. */
  generateMusic(request: JsMusicRequest): Promise<JsAudioResult>
  /** Generate sound effects from a prompt. */
  generateSfx(request: JsMusicRequest): Promise<JsAudioResult>
  /** Transcribe audio to text. */
  transcribe(request: JsTranscriptionRequest): Promise<JsTranscriptionResult>
  /** Run a model synchronously (submit + wait for result). */
  run(request: JsComputeRequest): Promise<JsComputeResult>
  /** Submit a job to the queue and return a job handle. */
  submit(request: JsComputeRequest): Promise<JsJobHandle>
  /** Get the status of a submitted job. */
  status(handle: JsJobHandle): Promise<JsJobStatus>
  /** Cancel a submitted job. */
  cancel(handle: JsJobHandle): Promise<void>
  /** Perform a chat completion via fal.ai's `any-llm` proxy. */
  complete(messages: Array<JsChatMessage>): Promise<JsCompletionResponse>
}
export type JsFalProvider = FalProvider

/**
 * An in-memory backend for the memory store.
 *
 * Data lives only as long as the process; nothing is persisted.
 *
 * ```javascript
 * const backend = new InMemoryBackend();
 * const memory = new Memory(embedder, backend);
 * ```
 */
export declare class InMemoryBackend {
  /** Create a new, empty in-memory backend. */
  constructor()
}
export type JsInMemoryBackend = InMemoryBackend

/**
 * A JSONL file-backed backend for the memory store.
 *
 * Loads entries from the file on creation, appends new entries, and rewrites
 * on updates/deletes.
 *
 * ```javascript
 * const backend = await JsonlBackend.create("./memory.jsonl");
 * const memory = new Memory(embedder, backend);
 * ```
 */
export declare class JsonlBackend {
  /**
   * Create a JSONL backend at the given file path.
   *
   * If the file exists, its contents are loaded. Otherwise an empty store
   * is created and the file is written on the first insert.
   */
  static create(path: string): Promise<JsonlBackend>
}
export type JsJsonlBackend = JsonlBackend

/**
 * A memory store that uses ELID for vector indexing and similarity search.
 *
 * Supports two modes:
 * - **Full mode** (`new Memory(embedder, backend)`): embedding-based search
 * - **Local mode** (`Memory.local(backend)`): text `SimHash` only, no embedder
 *
 * ```javascript
 * import { Memory, EmbeddingModel, InMemoryBackend } from 'blazen';
 *
 * const embedder = EmbeddingModel.openai(key);
 * const memory = new Memory(embedder, new InMemoryBackend());
 *
 * await memory.add("doc1", "Paris is the capital of France");
 * const results = await memory.search("What is France's capital?", 5);
 * console.log(results[0].text);
 * ```
 */
export declare class Memory {
  /**
   * Create a memory store with an embedding model for full ELID-based search.
   *
   * @param embedder - The embedding model to use for vectorisation.
   * @param backend  - An `InMemoryBackend` instance.
   */
  constructor(embedder: EmbeddingModel, backend: InMemoryBackend)
  /** Create a memory store with an embedding model and a `JsonlBackend`. */
  static withJsonl(embedder: EmbeddingModel, backend: JsonlBackend): Memory
  /** Create a memory store with an embedding model and a `ValkeyBackend`. */
  static withValkey(embedder: EmbeddingModel, backend: ValkeyBackend): Memory
  /**
   * Create a memory store in local-only mode (no embedding model) with an `InMemoryBackend`.
   *
   * Only `searchLocal()` is available; `search()` will throw.
   */
  static local(backend: InMemoryBackend): Memory
  /** Create a memory store in local-only mode with a `JsonlBackend`. */
  static localJsonl(backend: JsonlBackend): Memory
  /** Create a memory store in local-only mode with a `ValkeyBackend`. */
  static localValkey(backend: ValkeyBackend): Memory
  /**
   * Add a text entry to the memory store.
   *
   * @param id       - A unique identifier for this entry.
   * @param text     - The text content to store.
   * @param metadata - Optional arbitrary metadata (will be stored as JSON).
   * @returns The id of the stored entry.
   */
  add(id: string, text: string, metadata?: any | undefined | null): Promise<string>
  /**
   * Add multiple text entries to the memory store in a single batch.
   *
   * @param entries - An array of `{ id, text, metadata? }` objects.
   * @returns The ids of the stored entries.
   */
  addMany(entries: Array<JsAddEntry>): Promise<Array<string>>
  /**
   * Search using a query string with the configured embedding model.
   *
   * Returns up to `limit` results sorted by descending similarity.
   * Requires an embedding model (throws if created with `Memory.local()`).
   *
   * @param query - The search query text.
   * @param limit - Maximum number of results (default: 10).
   * @param `metadata_filter` - Optional JSON object to filter results. Only
   *   entries whose metadata is a superset of the filter are returned.
   */
  search(query: string, limit?: number | undefined | null, metadataFilter?: any | undefined | null): Promise<Array<JsMemoryResult>>
  /**
   * Search using only text-level `SimHash` (no embedding model required).
   *
   * This is a cheaper, lower-quality search that works in local-only mode.
   *
   * @param query - The search query text.
   * @param limit - Maximum number of results (default: 10).
   * @param `metadata_filter` - Optional JSON object to filter results. Only
   *   entries whose metadata is a superset of the filter are returned.
   */
  searchLocal(query: string, limit?: number | undefined | null, metadataFilter?: any | undefined | null): Promise<Array<JsMemoryResult>>
  /**
   * Retrieve a single entry by id.
   *
   * @param id - The entry identifier.
   * @returns The entry, or `null` if not found.
   */
  get(id: string): Promise<JsMemoryEntry | null>
  /**
   * Delete an entry by id.
   *
   * @param id - The entry identifier.
   * @returns `true` if the entry existed and was deleted.
   */
  delete(id: string): Promise<boolean>
  /** Return the number of entries in the store. */
  count(): Promise<number>
}
export type JsMemory = Memory

/**
 * A versioned registry for prompt templates.
 *
 * Organises templates by name and version, with convenient lookup,
 * rendering, and file I/O.
 *
 * ```javascript
 * const registry = new PromptRegistry();
 * registry.register("greet", new PromptTemplate("Hello {{name}}!"));
 * const msg = registry.render("greet", { name: "Alice" });
 * console.log(msg.content);
 * ```
 */
export declare class PromptRegistry {
  /** Create a new empty prompt registry. */
  constructor()
  /**
   * Register a template under the given name.
   *
   * The template's internal name is updated to match the provided name.
   * If a template with the same name and version already exists, it is
   * replaced.
   *
   * @param name     - The name to register the template under.
   * @param template - The `PromptTemplate` to register.
   */
  register(name: string, template: PromptTemplate): void
  /**
   * Get the latest version of a template by name.
   *
   * @param name - The template name.
   * @returns The `PromptTemplate` or `null` if not found.
   */
  get(name: string): PromptTemplate | null
  /**
   * Render the latest version of the named template with the given variables.
   *
   * @param name      - The template name.
   * @param variables - A map of variable name to value.
   * @returns A `ChatMessage` with the rendered content.
   */
  render(name: string, variables: Record<string, string>): ChatMessage
  /**
   * List all registered template names (sorted).
   *
   * @returns An array of template name strings.
   */
  list(): Array<string>
  /**
   * Load a registry from a YAML or JSON file.
   *
   * The file format is detected by extension (`.yaml`/`.yml` for YAML,
   * `.json` for JSON).
   *
   * @param path - Path to the prompt file.
   * @returns A new `PromptRegistry` with the loaded templates.
   */
  static fromFile(path: string): PromptRegistry
  /**
   * Load all prompt files from a directory.
   *
   * Reads all `.yaml`, `.yml`, and `.json` files in the directory.
   *
   * @param path - Path to the directory.
   * @returns A new `PromptRegistry` with the loaded templates.
   */
  static fromDir(path: string): PromptRegistry
}
export type JsPromptRegistry = PromptRegistry

/**
 * A reusable prompt template with `{{variable}}` placeholders.
 *
 * Templates are rendered by replacing `{{var}}` placeholders with the
 * provided variables map.
 *
 * ```javascript
 * const t = new PromptTemplate("Hello {{name}}!", { role: "user" });
 * const msg = t.render({ name: "Alice" });
 * console.log(msg.content); // "Hello Alice!"
 * ```
 */
export declare class PromptTemplate {
  /**
   * Create a new prompt template.
   *
   * @param template - The template string with `{{variable}}` placeholders.
   * @param options  - Optional configuration (role, name, description, version).
   */
  constructor(template: string, options?: PromptTemplateOptions | undefined | null)
  /** The raw template string. */
  get template(): string
  /** The chat role ("system", "user", or "assistant"). */
  get role(): string
  /** The template name. */
  get name(): string
  /** The optional description. */
  get description(): string | null
  /** The version string. */
  get version(): string
  /** The sorted list of variable names in this template. */
  get variables(): Array<string>
  /**
   * Render the template with the given variables.
   *
   * @param variables - A map of variable name to value.
   * @returns A `ChatMessage` with the rendered content and template's role.
   */
  render(variables: Record<string, string>): ChatMessage
}
export type JsPromptTemplate = PromptTemplate

/**
 * Namespace for in-process-only workflow values.
 *
 * Values stored via `session.set` are kept in the
 * `ContextInner.objects` side-channel and are **excluded** from
 * snapshots. Use this for state that should not survive a
 * `pause()` / `resume()` round-trip (request IDs, rate-limit
 * counters, ephemeral caches, …).
 *
 * For `session.set` values, identity preservation of JS class
 * instances through this namespace is **not** supported on the Node
 * bindings (see the module-level note on napi-rs threading). Values
 * are serialised via `serde_json::Value`, so you will get a plain
 * object back on `session.get`.
 */
export declare class SessionNamespace {
  /**
   * Store a JSON-serializable value under the given key. The value
   * is excluded from snapshots.
   */
  set(key: string, value: unknown): Promise<void>
  /**
   * Retrieve a value previously stored under the given key. Returns
   * `null` if the key does not exist.
   */
  get(key: string): Promise<unknown>
  /** Check whether a value exists under the given key. */
  has(key: string): Promise<boolean>
  /** Remove the value stored under the given key. */
  remove(key: string): Promise<void>
}
export type JsSessionNamespace = SessionNamespace

/**
 * Namespace for persistable workflow state.
 *
 * Values stored via `state.set` / `state.setBytes` go into the
 * underlying `ContextInner.state` map and survive snapshots,
 * `pause()` / `resume()`, and checkpoint stores.
 */
export declare class StateNamespace {
  /** Store a JSON-serializable value under the given key. */
  set(key: string, value: Exclude<StateValue, Buffer>): Promise<void>
  /** Retrieve a value previously stored under the given key. */
  get(key: string): Promise<StateValue | null>
  /** Store raw binary data under the given key. */
  setBytes(key: string, data: Buffer): Promise<void>
  /** Retrieve raw binary data previously stored under the given key. */
  getBytes(key: string): Promise<Buffer | null>
}
export type JsStateNamespace = StateNamespace

/**
 * A Valkey/Redis-backed backend for the memory store.
 *
 * ```javascript
 * const backend = ValkeyBackend.create("redis://localhost:6379");
 * const memory = new Memory(embedder, backend);
 * ```
 */
export declare class ValkeyBackend {
  /**
   * Create a Valkey backend connected to the given Redis/Valkey URL.
   *
   * The URL should be in standard Redis format, e.g. `redis://localhost:6379`.
   */
  static create(url: string): ValkeyBackend
}
export type JsValkeyBackend = ValkeyBackend

/**
 * A workflow builder and runner.
 *
 * Create a workflow, add steps with async handler functions, then run it.
 *
 * ```javascript
 * const workflow = new Workflow("my-workflow");
 *
 * workflow.addStep("analyze", ["blazen::StartEvent"], async (event, ctx) => {
 *   const text = event.message;
 *   return { type: "blazen::StopEvent", result: { analyzed: text } };
 * });
 *
 * const result = await workflow.run({ message: "hello" });
 * ```
 */
export declare class Workflow {
  /** Create a new workflow with the given name. */
  constructor(name: string)
  /**
   * Add a step to the workflow.
   *
   * - `name`: Human-readable step name.
   * - `eventTypes`: Array of event type strings this step handles.
   * - `handler`: Async function `(event, ctx) => Event` that processes
   *   events and returns the next event.
   */
  addStep(name: string, eventTypes: Array<string>, handler: StepHandlerTsfn): void
  /**
   * Set the workflow timeout in seconds.
   *
   * Set to 0 or negative to disable the timeout.
   */
  setTimeout(seconds: number): void
  /**
   * Run the workflow with the given input data.
   *
   * The input is wrapped in a `StartEvent` automatically.
   * Returns the final result when the workflow completes via a `StopEvent`.
   */
  run(input: any): Promise<JsWorkflowResult>
  /**
   * Run the workflow with streaming.
   *
   * The `onEvent` callback receives intermediate events published via
   * `ctx.writeEventToStream()` from within step handlers.
   *
   * Returns the final result when the workflow completes.
   */
  runStreaming(input: any, onEvent: StreamCallbackTsfn): Promise<JsWorkflowResult>
  /**
   * Run the workflow and return a handler object.
   *
   * Unlike `run()` which awaits the result internally, this method
   * returns a `WorkflowHandler` that gives you control over the
   * running workflow:
   *
   * - Call `handler.result()` to await the final result.
   * - Call `handler.pause()` to pause and get a snapshot JSON string.
   * - Call `handler.streamEvents(cb)` to subscribe to intermediate events.
   *
   * ```javascript
   * const handler = await workflow.runWithHandler({ message: "hello" });
   * // ... later ...
   * const snapshot = await handler.pause();
   * ```
   */
  runWithHandler(input: any): Promise<WorkflowHandler>
  /**
   * Resume a previously paused workflow from a snapshot.
   *
   * The snapshot JSON string should have been obtained from a prior
   * call to `handler.pause()`. The workflow will resume with the same
   * steps that were registered on this `Workflow` instance.
   *
   * Returns a new `WorkflowHandler` for the resumed workflow.
   *
   * ```javascript
   * const snapshot = fs.readFileSync("snapshot.json", "utf-8");
   * const handler = await workflow.resume(snapshot);
   * const result = await handler.result();
   * ```
   */
  resume(snapshotJson: string): Promise<WorkflowHandler>
}
export type JsWorkflow = Workflow

/**
 * A handle to a running workflow.
 *
 * Returned by `Workflow.runWithHandler()`. Provides methods to:
 *
 * - **`result()`** -- await the final workflow result (consumes the handler).
 * - **`pause()`** -- signal the workflow to pause.
 * - **`snapshot()`** -- get a serializable snapshot as a JSON string.
 * - **`resumeInPlace()`** -- resume a paused workflow without creating a new one.
 * - **`respondToInput(requestId, response)`** -- respond to an input request.
 * - **`abort()`** -- abort the running workflow.
 * - **`streamEvents(callback)`** -- subscribe to intermediate events
 *   published via `ctx.writeEventToStream()`.
 *
 * **Important:** `result()` consumes the handler internally. You can only
 * call it once. The other control methods (`pause`, `resumeInPlace`,
 * `abort`, `respondToInput`, `snapshot`) borrow the handler and can be
 * called multiple times.
 *
 * ```javascript
 * const handler = await workflow.runWithHandler({ message: "hello" });
 *
 * // Option A: just get the result
 * const result = await handler.result();
 *
 * // Option B: pause, snapshot, then resume
 * await handler.pause();
 * const snap = await handler.snapshot();
 * fs.writeFileSync("snapshot.json", snap);
 * await handler.resumeInPlace();
 * const result = await handler.result();
 *
 * // Option C: stream events, then get the result
 * handler.streamEvents((event) => console.log(event));
 * const result = await handler.result();
 * ```
 */
export declare class WorkflowHandler {
  /**
   * Await the final workflow result.
   *
   * Returns the result when the workflow completes via a `StopEvent`.
   *
   * This method consumes the handler internally -- it can only be called
   * once.
   */
  result(): Promise<JsWorkflowResult>
  /**
   * Signal the running workflow to pause.
   *
   * After pausing, use `snapshot()` to get a serializable snapshot, or
   * `resumeInPlace()` to continue execution.
   */
  pause(): Promise<void>
  /** Resume a paused workflow in place without creating a new handler. */
  resumeInPlace(): Promise<void>
  /**
   * Get a serializable snapshot of the workflow as a JSON string.
   *
   * The snapshot contains all workflow state and can be saved to a file
   * or database. Use `Workflow.resume(snapshotJson)` to resume later.
   */
  snapshot(): Promise<string>
  /**
   * Respond to an input request from a paused workflow.
   *
   * The `request_id` must match the `InputRequestEvent.request_id` that
   * was published by the workflow step.
   */
  respondToInput(requestId: string, response: any): Promise<void>
  /** Abort the running workflow. */
  abort(): Promise<void>
  /**
   * Subscribe to intermediate events published by steps via
   * `ctx.writeEventToStream()`.
   *
   * The `onEvent` callback receives each event as a plain object.
   * This must be called **before** `result()` or `pause()`.
   *
   * Events published before this call are not replayed.
   */
  streamEvents(onEvent: StreamCallbackTsfn): Promise<void>
}
export type JsWorkflowHandler = WorkflowHandler

/** Options for creating a `ChatMessage`. */
export interface ChatMessageOptions {
  /** Role: "system", "user", "assistant", or "tool". Defaults to "user". */
  role?: string
  /** Text content. */
  content?: string
  /** Multimodal content parts (alternative to content). */
  parts?: Array<JsContentPart>
}

/**
 * Estimate the total token count for an array of chat messages.
 *
 * Includes per-message overhead (role markers, separators) and assistant
 * priming tokens, matching the overhead model used by `OpenAI`.
 *
 * `contextSize` defaults to 128 000 if not provided.
 *
 * ```javascript
 * const tokens = countMessageTokens([
 *   ChatMessage.system("You are helpful."),
 *   ChatMessage.user("Hi"),
 * ]);
 * ```
 */
export declare function countMessageTokens(messages: Array<ChatMessage>, contextSize?: number | undefined | null): number

/**
 * Estimate the number of tokens in a text string.
 *
 * Uses a heuristic (3.5 characters per token) that works everywhere without
 * external data files.  Good enough for budget checks when exact counts are
 * not critical.
 *
 * `contextSize` defaults to 128 000 if not provided.
 *
 * ```javascript
 * const tokens = estimateTokens("Hello world");
 * ```
 */
export declare function estimateTokens(text: string, contextSize?: number | undefined | null): number

/** An entry to add to the memory store (used by `addMany`). */
export interface JsAddEntry {
  /** Unique identifier. If empty, one will be generated. */
  id: string
  /** The text content to store. */
  text: string
  /** Optional arbitrary metadata. */
  metadata?: any
}

/** The result of an agent run. */
export interface JsAgentResult {
  /** The final completion response from the model. */
  response: JsCompletionResponse
  /** Full message history including all tool calls and results. */
  messages: Array<any>
  /** Number of tool-calling iterations that occurred. */
  iterations: number
  /** Aggregated cost across all iterations, if available. */
  totalCost?: number
}

/** Options for configuring an agent run. */
export interface JsAgentRunOptions {
  /**
   * Maximum number of tool-calling iterations before forcing a final answer.
   * Defaults to 10.
   */
  maxIterations?: number
  /** Optional system prompt prepended to the conversation. */
  systemPrompt?: string
  /** Sampling temperature (0.0 - 2.0). */
  temperature?: number
  /** Maximum tokens per completion call. */
  maxTokens?: number
  /**
   * Whether to add a built-in "finish" tool that the model can call to
   * signal it has a final answer.
   */
  addFinishTool?: boolean
}

/**
 * A typed artifact extracted from or returned by a model.
 *
 * SVG / code blocks / markdown / mermaid / html / latex / json / custom payloads
 * can be returned inline as text by an LLM. Use the `kind` field to discriminate,
 * then read the variant-specific fields. Fields not relevant to the variant are
 * `null`.
 *
 * ## Example
 * ```ts
 * for (const art of response.artifacts) {
 *   if (art.kind === "svg") {
 *     renderSvg(art.content as string);
 *   } else if (art.kind === "code_block") {
 *     console.log(`${art.language}: ${art.content}`);
 *   }
 * }
 * ```
 */
export interface JsArtifact {
  /**
   * Discriminator. One of: `"svg"`, `"code_block"`, `"markdown"`, `"mermaid"`,
   * `"html"`, `"latex"`, `"json"`, `"custom"`.
   */
  kind: string
  /**
   * The artifact's primary payload. Typically a string; for the `json`
   * variant it is a parsed JSON value (object/array/scalar).
   */
  content: any
  /** Optional title for `svg` artifacts. */
  title?: string
  /** Language hint for `code_block` artifacts. */
  language?: string
  /** Filename hint for `code_block` artifacts. */
  filename?: string
  /** Provider-specific metadata for `custom` artifacts. */
  metadata?: any
  /**
   * Inner `kind` tag for `custom` artifacts. Distinct from the top-level
   * `kind` field (which equals `"custom"` for this variant).
   */
  customKind?: string
}

/** Audio content for multimodal messages. */
export interface JsAudioContent {
  source: JsImageSource
  mediaType?: string
  durationSeconds?: number
}

export interface JsAudioResult {
  audio: Array<JsGeneratedAudio>
  timing: JsRequestTiming
  cost?: number
  metadata: any
}

export interface JsAzureOptions {
  apiKey?: string
  model?: string
  baseUrl?: string
  resourceName: string
  deploymentName: string
  apiVersion?: string
}

export interface JsBackgroundRemovalRequest {
  imageUrl: string
  model?: string
  parameters?: any
}

export interface JsBedrockOptions {
  apiKey?: string
  model?: string
  baseUrl?: string
  region: string
}

export interface JsCacheConfig {
  strategy?: JsCacheStrategy
  ttlSeconds?: number
  maxEntries?: number
}

export declare const enum JsCacheStrategy {
  None = 'none',
  ContentHash = 'content_hash',
  AnthropicEphemeral = 'anthropic_ephemeral',
  Auto = 'auto'
}

/**
 * A web/document citation backing a model statement.
 *
 * Populated by Perplexity (`citations` array), Gemini (`groundingMetadata`),
 * and any provider that returns retrieval-augmented citations.
 */
export interface JsCitation {
  /** The cited URL. */
  url: string
  /** Document or web-page title, if available. */
  title?: string
  /** Excerpt/snippet from the source. */
  snippet?: string
  /** Byte offset in the response text where this citation starts. */
  start?: number
  /** Byte offset in the response text where this citation ends. */
  end?: number
  /** Optional document id (for retrieval-augmented citations). */
  documentId?: string
  /** Provider-specific extra fields preserved as JSON. */
  metadata: any
}

/** Options for a chat completion request. */
export interface JsCompletionOptions {
  temperature?: number
  maxTokens?: number
  topP?: number
  model?: string
  tools?: Array<JsToolDefinition>
  /** JSON Schema for structured output / response format. */
  responseFormat?: any
}

/** The result of a chat completion. */
export interface JsCompletionResponse {
  content?: string
  toolCalls: Array<JsToolCall>
  usage?: JsTokenUsage
  model: string
  finishReason?: string
  cost?: number
  timing?: JsRequestTiming
  images: Array<JsGeneratedImage>
  audio: Array<JsGeneratedAudio>
  videos: Array<JsGeneratedVideo>
  reasoning?: JsReasoningTrace
  citations: Array<JsCitation>
  artifacts: Array<JsArtifact>
  metadata: any
}

export interface JsComputeRequest {
  model: string
  input: any
  webhook?: string
}

export interface JsComputeResult {
  job?: JsJobHandle
  output: any
  timing: JsRequestTiming
  cost?: number
  metadata: any
}

/**
 * A single part in a multi-part message.
 *
 * `partType` is one of `"text"`, `"image"`, `"audio"`, `"video"`. Set the
 * matching field (`text`, `image`, `audio`, `video`) accordingly.
 */
export interface JsContentPart {
  partType: string
  text?: string
  image?: JsImageContent
  audio?: JsAudioContent
  video?: JsVideoContent
}

/** The result of an embedding operation. */
export interface JsEmbeddingResponse {
  /** The embedding vectors (one per input text). */
  embeddings: Array<Array<number>>
  /** The model that produced these embeddings. */
  model: string
  /** Token usage statistics, if available. */
  usage?: JsTokenUsage
  /** Estimated cost in USD, if available. */
  cost?: number
  /** Request timing breakdown, if available. */
  timing?: JsRequestTiming
  /** Provider-specific metadata. */
  metadata: any
}

export declare const enum JsFalLlmEndpointKind {
  OpenAiChat = 'open_ai_chat',
  OpenAiResponses = 'open_ai_responses',
  OpenAiEmbeddings = 'open_ai_embeddings',
  OpenRouter = 'open_router',
  AnyLlm = 'any_llm'
}

export interface JsFalOptions {
  apiKey?: string
  model?: string
  baseUrl?: string
  endpoint?: JsFalLlmEndpointKind
  enterprise?: boolean
  autoRouteModality?: boolean
}

/**
 * Normalized finish reason across providers.
 *
 * Maps provider-specific finish-reason strings (`"stop"`, `"end_turn"`,
 * `"STOP"`, `"length"`, `"tool_calls"`, `"max_tokens"`, etc.) into a canonical
 * set. Unknown values fall through to `kind == "other"`.
 *
 * Use `kind` for the canonical category and `value` for the original
 * provider string.
 */
export interface JsFinishReason {
  /**
   * Canonical category. One of: `"stop"`, `"length"`, `"tool_calls"`,
   * `"content_filter"`, `"safety"`, `"end_turn"`, `"stop_sequence"`,
   * `"max_tokens"`, `"error"`, or `"other"`.
   */
  kind: string
  /**
   * Raw provider string. Equals `kind` for canonical variants; for `Other(s)`
   * it preserves the original string.
   */
  value: string
}

export interface JsGenerated3DModel {
  media: JsMediaOutput
  vertexCount?: number
  faceCount?: number
  hasTextures: boolean
  hasAnimations: boolean
}

export interface JsGeneratedAudio {
  media: JsMediaOutput
  durationSeconds?: number
  sampleRate?: number
  channels?: number
}

export interface JsGeneratedImage {
  media: JsMediaOutput
  width?: number
  height?: number
}

export interface JsGeneratedVideo {
  media: JsMediaOutput
  width?: number
  height?: number
  durationSeconds?: number
  fps?: number
}

/** Image content for multimodal messages. */
export interface JsImageContent {
  source: JsImageSource
  mediaType?: string
}

export interface JsImageRequest {
  prompt: string
  negativePrompt?: string
  width?: number
  height?: number
  numImages?: number
  model?: string
  parameters?: any
}

export interface JsImageResult {
  images: Array<JsGeneratedImage>
  timing: JsRequestTiming
  cost?: number
  metadata: any
}

/** How an image is provided (URL or base64). */
export interface JsImageSource {
  sourceType: string
  url?: string
  data?: string
}

export interface JsJobHandle {
  id: string
  provider: string
  model: string
  submittedAt: string
}

/** Status of a compute job. */
export declare const enum JsJobStatus {
  /** Job is waiting in the provider's queue. */
  Queued = 'queued',
  /** Job is currently executing. */
  Running = 'running',
  /** Job completed successfully. */
  Completed = 'completed',
  /** Job failed with an error. */
  Failed = 'failed',
  /** Job was cancelled. */
  Cancelled = 'cancelled'
}

export interface JsMediaOutput {
  url?: string
  base64?: string
  rawContent?: string
  mediaType: string
  fileSize?: number
  metadata: any
}

/** A stored entry retrieved from the memory store. */
export interface JsMemoryEntry {
  /** The entry id. */
  id: string
  /** The original text content. */
  text: string
  /** Arbitrary user metadata. */
  metadata: any
}

/** A search result from the memory store. */
export interface JsMemoryResult {
  /** The entry id. */
  id: string
  /** The original text content. */
  text: string
  /** Similarity score in 0.0..=1.0 (higher = more similar). */
  score: number
  /** Arbitrary user metadata. */
  metadata: any
}

export interface JsMusicRequest {
  prompt: string
  durationSeconds?: number
  model?: string
  parameters?: any
}

export interface JsProviderOptions {
  apiKey?: string
  model?: string
  baseUrl?: string
}

/**
 * Chain-of-thought / extended-thinking trace from a model that exposes one.
 *
 * Populated by Anthropic extended thinking, `DeepSeek` R1 `reasoning_content`,
 * `OpenAI` o-series, xAI Grok reasoning, and Gemini thoughts.
 */
export interface JsReasoningTrace {
  /** Plain-text rendering of the reasoning content. */
  text: string
  /** Provider-specific signature/redaction handle, if any (Anthropic). */
  signature?: string
  /** Whether the trace was redacted by the provider. */
  redacted: boolean
  /**
   * Reasoning effort level if the provider exposes one
   * (e.g. `"low"`, `"medium"`, `"high"`).
   */
  effort?: string
}

export interface JsRequestTiming {
  queueMs?: number
  executionMs?: number
  totalMs?: number
}

/**
 * Typed response-format hint for structured output.
 *
 * Use one of the variants by setting `kind` to `"text"`, `"json_object"`, or
 * `"json_schema"`. For `"json_schema"`, populate `schemaName`, `schema`, and
 * optionally `strict`.
 */
export interface JsResponseFormat {
  /** Discriminator. One of `"text"`, `"json_object"`, `"json_schema"`. */
  kind: string
  /** Schema name for `json_schema` variants. */
  schemaName?: string
  /** Schema body for `json_schema` variants. */
  schema?: any
  /** Whether the schema is strict (`json_schema` variants only). */
  strict?: boolean
}

export interface JsRetryConfig {
  maxRetries?: number
  initialDelayMs?: number
  maxDelayMs?: number
  honorRetryAfter?: boolean
  jitter?: boolean
}

/** The role of a participant in a chat conversation. */
export declare const enum JsRole {
  System = 'system',
  User = 'user',
  Assistant = 'assistant',
  Tool = 'tool'
}

export interface JsSpeechRequest {
  text: string
  voice?: string
  voiceUrl?: string
  language?: string
  speed?: number
  model?: string
  parameters?: any
}

/**
 * A single chunk from a streaming completion response.
 *
 * Passed to the `onChunk` callback during streaming operations.
 *
 * ```javascript
 * await model.stream(
 *   [ChatMessage.user("Tell me a story")],
 *   (chunk) => {
 *     if (chunk.delta) process.stdout.write(chunk.delta);
 *     if (chunk.finishReason) console.log("done:", chunk.finishReason);
 *   }
 * );
 * ```
 */
export interface JsStreamChunk {
  /** Incremental text content, if any. */
  delta?: string
  /**
   * The reason the model stopped generating (`"stop"`, `"tool_use"`, etc.).
   * Present only in the final chunk.
   */
  finishReason?: string
  /** Tool invocations completed in this chunk. */
  toolCalls: Array<JsToolCall>
  /**
   * Reasoning text delta from models that stream a chain-of-thought trace
   * (Anthropic extended thinking, `DeepSeek` R1, `OpenAI` o-series).
   */
  reasoningDelta?: string
  /** Citations completed in this chunk. */
  citations: Array<JsCitation>
  /** Artifacts completed in this chunk. */
  artifacts: Array<JsArtifact>
}

export interface JsThreeDRequest {
  prompt?: string
  imageUrl?: string
  format?: string
  model?: string
  parameters?: any
}

export interface JsThreeDResult {
  models: Array<JsGenerated3DModel>
  timing: JsRequestTiming
  cost?: number
  metadata: any
}

export interface JsTokenUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
  reasoningTokens?: number
  cachedInputTokens?: number
  audioInputTokens?: number
  audioOutputTokens?: number
}

export interface JsToolCall {
  id: string
  name: string
  arguments: any
}

/** Describes a tool that the agent may invoke during its execution loop. */
export interface JsToolDef {
  /** The unique name of the tool. */
  name: string
  /** A human-readable description of what the tool does. */
  description: string
  /** JSON Schema describing the tool's parameters. */
  parameters: any
}

export interface JsToolDefinition {
  name: string
  description: string
  parameters: any
}

export interface JsTranscriptionRequest {
  audioUrl: string
  language?: string
  diarize?: boolean
  model?: string
  parameters?: any
}

export interface JsTranscriptionResult {
  text: string
  segments: Array<JsTranscriptionSegment>
  language?: string
  timing: JsRequestTiming
  cost?: number
  metadata: any
}

export interface JsTranscriptionSegment {
  text: string
  start: number
  end: number
  speaker?: string
}

export interface JsUpscaleRequest {
  imageUrl: string
  scale: number
  model?: string
  parameters?: any
}

/** Video content for multimodal messages. */
export interface JsVideoContent {
  source: JsImageSource
  mediaType?: string
  durationSeconds?: number
}

export interface JsVideoRequest {
  prompt: string
  imageUrl?: string
  durationSeconds?: number
  negativePrompt?: string
  width?: number
  height?: number
  model?: string
  parameters?: any
}

export interface JsVideoResult {
  videos: Array<JsGeneratedVideo>
  timing: JsRequestTiming
  cost?: number
  metadata: any
}

/** The result of a workflow run. */
export interface JsWorkflowResult {
  /** The event type of the final result (typically "`blazen::StopEvent`"). */
  type: string
  /** The result data as a JSON object. */
  data: any
}

/** Options for creating a `PromptTemplate`. */
export interface PromptTemplateOptions {
  /** The chat role: "system", "user", or "assistant". Defaults to "user". */
  role?: string
  /** A unique name for this template. Defaults to "unnamed". */
  name?: string
  /** An optional description of this template. */
  description?: string
  /** The version string. Defaults to "1.0". */
  version?: string
}

/**
 * Run an agentic tool execution loop.
 *
 * The agent repeatedly calls the model, executes any tool calls via the
 * `toolHandler` callback, feeds results back, and repeats until the model
 * stops calling tools or `maxIterations` is reached.
 *
 * The `toolHandler` callback receives `(toolName: string, arguments: object)`
 * and must return the tool result as a JSON-serializable value (or a Promise
 * that resolves to one).
 *
 * ```typescript
 * import { CompletionModel, ChatMessage, runAgent } from 'blazen';
 *
 * const model = CompletionModel.openai("sk-...");
 *
 * const result = await runAgent(
 *   model,
 *   [ChatMessage.user("What is the weather in NYC?")],
 *   [{ name: "getWeather", description: "Get weather", parameters: { type: "object", properties: { city: { type: "string" } }, required: ["city"] } }],
 *   async (toolName, args) => {
 *     if (toolName === "getWeather") return { temp: 72, condition: "sunny" };
 *     throw new Error(`Unknown tool: ${toolName}`);
 *   },
 *   { maxIterations: 5 }
 * );
 * ```
 */
export declare function runAgent(model: JsCompletionModel, messages: Array<JsChatMessage>, tools: Array<JsToolDef>, toolHandler: ToolHandlerTsfn, options?: JsAgentRunOptions | undefined | null): Promise<JsAgentResult>

/** Returns the version of the blazen library. */
export declare function version(): string
