/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A chat completion model.
 *
 * Use the static factory methods to create an instance for your provider:
 *
 * ```javascript
 * const model = CompletionModel.openai("sk-...");
 * const response = await model.complete([
 *   { role: "user", content: "What is 2 + 2?" }
 * ]);
 * ```
 */
export declare class CompletionModel {
  /** Create an `OpenAI` completion model. */
  static openai(apiKey: string): CompletionModel
  /** Create an Anthropic completion model. */
  static anthropic(apiKey: string): CompletionModel
  /** Create a Google Gemini completion model. */
  static gemini(apiKey: string): CompletionModel
  /** Create an Azure `OpenAI` completion model. */
  static azure(apiKey: string, resourceName: string, deploymentName: string): CompletionModel
  /** Create a fal.ai completion model. */
  static fal(apiKey: string): CompletionModel
  /** Create an `OpenRouter` completion model. */
  static openrouter(apiKey: string): CompletionModel
  /** Create a Groq completion model. */
  static groq(apiKey: string): CompletionModel
  /** Create a Together AI completion model. */
  static together(apiKey: string): CompletionModel
  /** Create a Mistral AI completion model. */
  static mistral(apiKey: string): CompletionModel
  /** Create a `DeepSeek` completion model. */
  static deepseek(apiKey: string): CompletionModel
  /** Create a Fireworks AI completion model. */
  static fireworks(apiKey: string): CompletionModel
  /** Create a Perplexity completion model. */
  static perplexity(apiKey: string): CompletionModel
  /** Create an xAI (Grok) completion model. */
  static xai(apiKey: string): CompletionModel
  /** Create a Cohere completion model. */
  static cohere(apiKey: string): CompletionModel
  /** Create an AWS Bedrock completion model. */
  static bedrock(apiKey: string, region: string): CompletionModel
  /** Get the model ID. */
  get modelId(): string
  /**
   * Perform a chat completion.
   *
   * Messages should be an array of `{ role: string, content: string }` objects.
   *
   * Returns the response as a JSON object with `content`, `toolCalls`,
   * `usage`, `model`, and `finishReason` fields.
   */
  complete(messages: Array<any>): Promise<any>
  /**
   * Perform a chat completion with additional options.
   *
   * Options object may include:
   * - `temperature` (number): Sampling temperature (0.0 - 2.0)
   * - `maxTokens` (number): Maximum tokens to generate
   * - `topP` (number): Nucleus sampling parameter
   * - `model` (string): Override the default model
   * - `tools` (array): Tool definitions for function calling
   */
  completeWithOptions(messages: Array<any>, options: any): Promise<any>
}
export type JsCompletionModel = CompletionModel

/**
 * Shared workflow context accessible by all steps.
 *
 * Provides typed key/value storage, event emission, and stream publishing.
 * All values are stored as JSON internally.
 */
export declare class Context {
  /**
   * Store a value under the given key.
   *
   * The value is stored as JSON internally.
   */
  set(key: string, value: any): Promise<void>
  /**
   * Retrieve a value previously stored under the given key.
   *
   * Returns `null` if the key does not exist.
   */
  get(key: string): Promise<any>
  /**
   * Emit an event into the internal routing queue.
   *
   * The event will be routed to any step whose `eventTypes` list includes
   * its event type. The event object must have a `type` field.
   */
  sendEvent(event: any): Promise<void>
  /**
   * Publish an event to the external broadcast stream.
   *
   * Consumers that subscribed via streaming will receive this event.
   * Unlike `sendEvent`, this does NOT route the event through the
   * internal step registry.
   */
  writeEventToStream(event: any): Promise<void>
  /** Get the workflow run ID. */
  runId(): Promise<string>
}
export type JsContext = Context

/**
 * A workflow builder and runner.
 *
 * Create a workflow, add steps with async handler functions, then run it.
 *
 * ```javascript
 * const workflow = new Workflow("my-workflow");
 *
 * workflow.addStep("analyze", ["blazen::StartEvent"], async (event, ctx) => {
 *   const text = event.message;
 *   return { type: "blazen::StopEvent", result: { analyzed: text } };
 * });
 *
 * const result = await workflow.run({ message: "hello" });
 * ```
 */
export declare class Workflow {
  /** Create a new workflow with the given name. */
  constructor(name: string)
  /**
   * Add a step to the workflow.
   *
   * - `name`: Human-readable step name.
   * - `eventTypes`: Array of event type strings this step handles.
   * - `handler`: Async function `(event, ctx) => Event` that processes
   *   events and returns the next event.
   */
  addStep(name: string, eventTypes: Array<string>, handler: StepHandlerTsfn): void
  /**
   * Set the workflow timeout in seconds.
   *
   * Set to 0 or negative to disable the timeout.
   */
  setTimeout(seconds: number): void
  /**
   * Run the workflow with the given input data.
   *
   * The input is wrapped in a `StartEvent` automatically.
   * Returns the final result when the workflow completes via a `StopEvent`.
   */
  run(input: any): Promise<JsWorkflowResult>
  /**
   * Run the workflow with streaming.
   *
   * The `onEvent` callback receives intermediate events published via
   * `ctx.writeEventToStream()` from within step handlers.
   *
   * Returns the final result when the workflow completes.
   */
  runStreaming(input: any, onEvent: StreamCallbackTsfn): Promise<JsWorkflowResult>
  /**
   * Run the workflow and return a handler object.
   *
   * Unlike `run()` which awaits the result internally, this method
   * returns a `WorkflowHandler` that gives you control over the
   * running workflow:
   *
   * - Call `handler.result()` to await the final result.
   * - Call `handler.pause()` to pause and get a snapshot JSON string.
   * - Call `handler.streamEvents(cb)` to subscribe to intermediate events.
   *
   * ```javascript
   * const handler = await workflow.runWithHandler({ message: "hello" });
   * // ... later ...
   * const snapshot = await handler.pause();
   * ```
   */
  runWithHandler(input: any): Promise<WorkflowHandler>
  /**
   * Resume a previously paused workflow from a snapshot.
   *
   * The snapshot JSON string should have been obtained from a prior
   * call to `handler.pause()`. The workflow will resume with the same
   * steps that were registered on this `Workflow` instance.
   *
   * Returns a new `WorkflowHandler` for the resumed workflow.
   *
   * ```javascript
   * const snapshot = fs.readFileSync("snapshot.json", "utf-8");
   * const handler = await workflow.resume(snapshot);
   * const result = await handler.result();
   * ```
   */
  resume(snapshotJson: string): Promise<WorkflowHandler>
}
export type JsWorkflow = Workflow

/**
 * A handle to a running workflow.
 *
 * Returned by `Workflow.runWithHandler()`. Provides methods to:
 *
 * - **`result()`** -- await the final workflow result.
 * - **`pause()`** -- pause the workflow and get a snapshot JSON string.
 * - **`streamEvents(callback)`** -- subscribe to intermediate events
 *   published via `ctx.writeEventToStream()`.
 *
 * **Important:** `result()` and `pause()` each consume the handler
 * internally. You can only call one of them, and only once.
 *
 * ```javascript
 * const handler = await workflow.runWithHandler({ message: "hello" });
 *
 * // Option A: just get the result
 * const result = await handler.result();
 *
 * // Option B: pause and get a snapshot
 * const snapshot = await handler.pause();
 * fs.writeFileSync("snapshot.json", snapshot);
 *
 * // Option C: stream events, then get the result
 * handler.streamEvents((event) => console.log(event));
 * const result = await handler.result();
 * ```
 */
export declare class WorkflowHandler {
  /**
   * Await the final workflow result.
   *
   * Returns the result when the workflow completes via a `StopEvent`.
   *
   * This method consumes the handler internally -- it can only be called
   * once, and cannot be called after `pause()`.
   */
  result(): Promise<JsWorkflowResult>
  /**
   * Pause the running workflow and return a snapshot as a JSON string.
   *
   * The snapshot contains all workflow state and can be saved to a file
   * or database. Use `Workflow.resume(snapshotJson)` to resume later.
   *
   * This method consumes the handler internally -- it can only be called
   * once, and cannot be called after `result()`.
   */
  pause(): Promise<string>
  /**
   * Subscribe to intermediate events published by steps via
   * `ctx.writeEventToStream()`.
   *
   * The `onEvent` callback receives each event as a plain object.
   * This must be called **before** `result()` or `pause()`.
   *
   * Events published before this call are not replayed.
   */
  streamEvents(onEvent: StreamCallbackTsfn): Promise<void>
}
export type JsWorkflowHandler = WorkflowHandler

/** The result of a workflow run. */
export interface JsWorkflowResult {
  /** The event type of the final result (typically "`blazen::StopEvent`"). */
  type: string
  /** The result data as a JSON object. */
  data: any
}

/** Returns the version of the blazen library. */
export declare function version(): string
