//! Auto-generated napi mirror types.
//!
//! These `Js*` structs and their `From` impls are generated by `build.rs`
//! from the core types in `blazen-llm`. Do not edit manually.

#![allow(
    clippy::redundant_closure,
    clippy::redundant_closure_for_method_calls,
    clippy::use_self,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_precision_loss,
    clippy::needless_pass_by_value,
    clippy::module_name_repetitions,
    clippy::map_identity,
    clippy::unnecessary_wraps,
    clippy::trivially_copy_pass_by_ref,
    dead_code,
    unused_imports
)]

include!(concat!(env!("OUT_DIR"), "/napi_mirrors.rs"));
