//! Low-level compute job types: request, handle, status, result, timing.
//!
//! In addition to [`JsJobStatus`] (a string enum), this module exposes
//! [`JsJobHandleClass`] (JS name `JobHandle`) — a class wrapper around the
//! plain-object [`JsJobHandle`](crate::generated::JsJobHandle) generated by
//! `build.rs`. Lifecycle methods (`status`, `cancel`, `awaitCompletion`)
//! live on the provider class because they require a provider reference;
//! this class carries the identifier metadata and converts back to/from the
//! plain handle that the provider methods accept.

use napi_derive::napi;

use blazen_llm::compute::JobHandle;

use crate::generated::JsJobHandle;

/// Status of a compute job.
#[napi(string_enum)]
pub enum JsJobStatus {
    /// Job is waiting in the provider's queue.
    #[napi(value = "queued")]
    Queued,
    /// Job is currently executing.
    #[napi(value = "running")]
    Running,
    /// Job completed successfully.
    #[napi(value = "completed")]
    Completed,
    /// Job failed with an error.
    #[napi(value = "failed")]
    Failed,
    /// Job was cancelled.
    #[napi(value = "cancelled")]
    Cancelled,
}

// ---------------------------------------------------------------------------
// JsJobHandleClass — class wrapper exposed to JS as `JobHandle`
// ---------------------------------------------------------------------------

/// Options for constructing a [`JsJobHandleClass`] from JavaScript.
#[napi(object)]
pub struct JobHandleOptions {
    /// Provider-assigned job/request identifier.
    pub id: String,
    /// Provider name (e.g., "fal", "replicate", "runpod").
    pub provider: String,
    /// The model/endpoint that was invoked.
    pub model: String,
    /// When the job was submitted (RFC 3339 string).
    #[napi(js_name = "submittedAt")]
    pub submitted_at: String,
}

/// Class wrapper around a compute [`JobHandle`].
///
/// Use [`toObject`](Self::to_object) to convert this to the plain-object
/// form accepted by provider lifecycle methods (`status`, `cancel`,
/// `awaitCompletion`). The reverse — building a class from a plain
/// object — is available via [`fromObject`](Self::from_object).
///
/// ```typescript
/// import { JobHandle, FalProvider, ComputeRequest } from 'blazen';
///
/// const fal = FalProvider.create();
/// const plain = await fal.submit({ model: "fal-ai/flux/dev", input: { prompt: "..." } });
/// const handle = JobHandle.fromObject(plain);
/// console.log(handle.id, handle.provider);
///
/// const result = await fal.awaitCompletion(handle.toObject());
/// ```
#[napi(js_name = "JobHandle")]
pub struct JsJobHandleClass {
    pub(crate) inner: JobHandle,
}

#[napi]
#[allow(
    clippy::must_use_candidate,
    clippy::missing_errors_doc,
    clippy::needless_pass_by_value
)]
impl JsJobHandleClass {
    /// Construct a job handle from explicit field values.
    #[napi(constructor)]
    pub fn new(options: JobHandleOptions) -> napi::Result<Self> {
        let submitted_at = chrono::DateTime::parse_from_rfc3339(&options.submitted_at)
            .map_err(|e| {
                napi::Error::from_reason(format!(
                    "JobHandle.submittedAt is not a valid RFC 3339 timestamp: {e}"
                ))
            })?
            .with_timezone(&chrono::Utc);
        Ok(Self {
            inner: JobHandle {
                id: options.id,
                provider: options.provider,
                model: options.model,
                submitted_at,
            },
        })
    }

    /// Wrap a plain `JsJobHandle` object (e.g. one returned by
    /// `provider.submit()`) in a `JobHandle` class instance.
    #[napi(factory, js_name = "fromObject")]
    pub fn from_object(handle: JsJobHandle) -> Self {
        Self {
            inner: handle.into(),
        }
    }

    /// Convert this handle back to a plain object suitable for passing to
    /// provider lifecycle methods (`status`, `cancel`, `awaitCompletion`,
    /// `result`).
    #[napi(js_name = "toObject")]
    pub fn to_object(&self) -> JsJobHandle {
        JsJobHandle::from(self.inner.clone())
    }

    /// Provider-assigned job/request identifier.
    #[napi(getter)]
    pub fn id(&self) -> String {
        self.inner.id.clone()
    }

    /// Provider name (e.g. "fal", "replicate", "runpod").
    #[napi(getter)]
    pub fn provider(&self) -> String {
        self.inner.provider.clone()
    }

    /// The model/endpoint that was invoked.
    #[napi(getter)]
    pub fn model(&self) -> String {
        self.inner.model.clone()
    }

    /// When the job was submitted (RFC 3339 string).
    #[napi(getter, js_name = "submittedAt")]
    pub fn submitted_at(&self) -> String {
        self.inner.submitted_at.to_rfc3339()
    }
}

impl From<JobHandle> for JsJobHandleClass {
    fn from(inner: JobHandle) -> Self {
        Self { inner }
    }
}
