//! Usage types — re-exports plus class wrappers.
//!
//! The `JsTokenUsage` and `JsRequestTiming` plain-object mirrors are
//! auto-generated by `build.rs`. This module additionally exposes class
//! wrappers ([`JsTokenUsageClass`] and [`JsRequestTimingClass`], JS names
//! `TokenUsage` and `RequestTiming`) with getters and constructors for
//! callers that prefer working with class instances.

pub use blazen_llm::types::{RequestTiming, TokenUsage};

use napi_derive::napi;

// ---------------------------------------------------------------------------
// JsTokenUsageClass — class wrapper exposed to JS as `TokenUsage`
// ---------------------------------------------------------------------------

/// Options for constructing a [`JsTokenUsageClass`] from JavaScript.
#[napi(object)]
pub struct TokenUsageOptions {
    #[napi(js_name = "promptTokens")]
    pub prompt_tokens: u32,
    #[napi(js_name = "completionTokens")]
    pub completion_tokens: u32,
    #[napi(js_name = "totalTokens")]
    pub total_tokens: u32,
    #[napi(js_name = "reasoningTokens")]
    pub reasoning_tokens: Option<u32>,
    #[napi(js_name = "cachedInputTokens")]
    pub cached_input_tokens: Option<u32>,
    #[napi(js_name = "audioInputTokens")]
    pub audio_input_tokens: Option<u32>,
    #[napi(js_name = "audioOutputTokens")]
    pub audio_output_tokens: Option<u32>,
}

/// Class wrapper around [`TokenUsage`].
///
/// ```typescript
/// import { TokenUsage } from 'blazen';
///
/// const u = new TokenUsage({ promptTokens: 10, completionTokens: 5, totalTokens: 15 });
/// console.log(u.promptTokens, u.totalTokens);
/// ```
#[napi(js_name = "TokenUsage")]
pub struct JsTokenUsageClass {
    pub(crate) inner: TokenUsage,
}

#[napi]
#[allow(clippy::must_use_candidate, clippy::needless_pass_by_value)]
impl JsTokenUsageClass {
    /// Construct a token-usage instance.
    #[napi(constructor)]
    pub fn new(options: TokenUsageOptions) -> Self {
        Self {
            inner: TokenUsage {
                prompt_tokens: options.prompt_tokens,
                completion_tokens: options.completion_tokens,
                total_tokens: options.total_tokens,
                reasoning_tokens: options.reasoning_tokens.unwrap_or(0),
                cached_input_tokens: options.cached_input_tokens.unwrap_or(0),
                audio_input_tokens: options.audio_input_tokens.unwrap_or(0),
                audio_output_tokens: options.audio_output_tokens.unwrap_or(0),
            },
        }
    }

    /// Tokens in the prompt / input.
    #[napi(getter, js_name = "promptTokens")]
    pub fn prompt_tokens(&self) -> u32 {
        self.inner.prompt_tokens
    }

    /// Tokens in the completion / output.
    #[napi(getter, js_name = "completionTokens")]
    pub fn completion_tokens(&self) -> u32 {
        self.inner.completion_tokens
    }

    /// Total tokens consumed (prompt + completion).
    #[napi(getter, js_name = "totalTokens")]
    pub fn total_tokens(&self) -> u32 {
        self.inner.total_tokens
    }

    /// Tokens spent on hidden reasoning (o-series, R1, Anthropic thinking).
    #[napi(getter, js_name = "reasoningTokens")]
    pub fn reasoning_tokens(&self) -> u32 {
        self.inner.reasoning_tokens
    }

    /// Tokens served from a prompt cache, if the provider reports them.
    #[napi(getter, js_name = "cachedInputTokens")]
    pub fn cached_input_tokens(&self) -> u32 {
        self.inner.cached_input_tokens
    }

    /// Tokens consumed by audio input.
    #[napi(getter, js_name = "audioInputTokens")]
    pub fn audio_input_tokens(&self) -> u32 {
        self.inner.audio_input_tokens
    }

    /// Tokens consumed by audio output.
    #[napi(getter, js_name = "audioOutputTokens")]
    pub fn audio_output_tokens(&self) -> u32 {
        self.inner.audio_output_tokens
    }
}

impl From<TokenUsage> for JsTokenUsageClass {
    fn from(inner: TokenUsage) -> Self {
        Self { inner }
    }
}

impl From<&TokenUsage> for JsTokenUsageClass {
    fn from(inner: &TokenUsage) -> Self {
        Self {
            inner: inner.clone(),
        }
    }
}

// ---------------------------------------------------------------------------
// JsRequestTimingClass — class wrapper exposed to JS as `RequestTiming`
// ---------------------------------------------------------------------------

/// Options for constructing a [`JsRequestTimingClass`] from JavaScript.
#[napi(object)]
pub struct RequestTimingOptions {
    /// Time spent waiting in queue (ms), if applicable.
    #[napi(js_name = "queueMs")]
    pub queue_ms: Option<i64>,
    /// Time spent executing the request (ms).
    #[napi(js_name = "executionMs")]
    pub execution_ms: Option<i64>,
    /// Total wall-clock time from submit to response (ms).
    #[napi(js_name = "totalMs")]
    pub total_ms: Option<i64>,
}

/// Class wrapper around [`RequestTiming`].
#[napi(js_name = "RequestTiming")]
pub struct JsRequestTimingClass {
    pub(crate) inner: RequestTiming,
}

#[napi]
#[allow(
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap
)]
impl JsRequestTimingClass {
    /// Construct a request-timing instance.
    #[napi(constructor)]
    pub fn new(options: RequestTimingOptions) -> Self {
        Self {
            inner: RequestTiming {
                queue_ms: options.queue_ms.map(|v| v as u64),
                execution_ms: options.execution_ms.map(|v| v as u64),
                total_ms: options.total_ms.map(|v| v as u64),
            },
        }
    }

    #[napi(getter, js_name = "queueMs")]
    pub fn queue_ms(&self) -> Option<i64> {
        self.inner.queue_ms.map(|v| v as i64)
    }

    #[napi(getter, js_name = "executionMs")]
    pub fn execution_ms(&self) -> Option<i64> {
        self.inner.execution_ms.map(|v| v as i64)
    }

    #[napi(getter, js_name = "totalMs")]
    pub fn total_ms(&self) -> Option<i64> {
        self.inner.total_ms.map(|v| v as i64)
    }
}

impl From<RequestTiming> for JsRequestTimingClass {
    fn from(inner: RequestTiming) -> Self {
        Self { inner }
    }
}

impl From<&RequestTiming> for JsRequestTimingClass {
    fn from(inner: &RequestTiming) -> Self {
        Self {
            inner: inner.clone(),
        }
    }
}
