# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "AgentResult",
    "Artifact",
    "AudioResult",
    "AzureOptions",
    "BackgroundRemovalRequest",
    "BedrockOptions",
    "BlazenState",
    "CacheConfig",
    "CacheStrategy",
    "ChatMessage",
    "ChatWindow",
    "CompletionModel",
    "CompletionOptions",
    "CompletionResponse",
    "CompletionStream",
    "ComputeResult",
    "ContentPart",
    "Context",
    "EmbeddingModel",
    "Event",
    "FalEmbeddingModel",
    "FalLlmEndpointKind",
    "FalOptions",
    "FalProvider",
    "FinishReason",
    "Generated3DModel",
    "GeneratedAudio",
    "GeneratedImage",
    "GeneratedVideo",
    "ImageRequest",
    "ImageResult",
    "InMemoryBackend",
    "JsonlBackend",
    "MediaOutput",
    "MediaType",
    "Memory",
    "MemoryResult",
    "MusicRequest",
    "PromptRegistry",
    "PromptTemplate",
    "ProviderOptions",
    "ResponseFormat",
    "RetryConfig",
    "Role",
    "SessionNamespace",
    "SpeechRequest",
    "StartEvent",
    "StateNamespace",
    "StopEvent",
    "ThreeDRequest",
    "ThreeDResult",
    "ToolDef",
    "TranscriptionRequest",
    "TranscriptionResult",
    "TranscriptionSegment",
    "UpscaleRequest",
    "ValkeyBackend",
    "VideoRequest",
    "VideoResult",
    "Workflow",
    "WorkflowHandler",
]

@typing.final
class AgentResult:
    r"""
    Result of an agent run.
    
    Example:
        >>> result = await run_agent(model, messages, tools=[tool])
        >>> print(result.response.content)
        >>> print(result.iterations)
        >>> print(result.total_cost)
    """
    @property
    def response(self) -> CompletionResponse:
        r"""
        The final completion response from the model.
        """
    @property
    def messages(self) -> builtins.list[ChatMessage]:
        r"""
        Full message history including all tool calls and results.
        """
    @property
    def iterations(self) -> builtins.int:
        r"""
        Number of tool call rounds that occurred.
        """
    @property
    def total_cost(self) -> typing.Optional[builtins.float]:
        r"""
        Aggregated cost across all rounds, if available.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Artifact:
    r"""
    A typed artifact extracted from or returned by a model.
    
    SVG / code blocks / markdown / mermaid / html / latex / json / custom payloads
    can be returned inline as text by an LLM. The `Artifact` surface lifts them
    into typed values that callers can dispatch on without re-parsing the
    assistant content string.
    
    Use the ``kind`` getter to discriminate, then read the variant-specific
    fields. Fields not relevant to the variant return ``None``.
    
    Example:
        >>> for art in response.artifacts:
        ...     if art.kind == "svg":
        ...         render_svg(art.content)
        ...     elif art.kind == "code_block":
        ...         print(f"{art.language}: {art.content}")
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        Discriminator string. One of: ``"svg"``, ``"code_block"``, ``"markdown"``,
        ``"mermaid"``, ``"html"``, ``"latex"``, ``"json"``, ``"custom"``.
        """
    @property
    def content(self) -> typing.Any:
        r"""
        The artifact's primary payload.
        
        For ``svg``, ``code_block``, ``markdown``, ``mermaid``, ``html``, ``latex``,
        and ``custom`` this is a string. For ``json`` it is a parsed Python value
        (dict / list / scalar).
        """
    @property
    def title(self) -> typing.Optional[builtins.str]:
        r"""
        Optional title for ``svg`` artifacts.
        """
    @property
    def language(self) -> typing.Optional[builtins.str]:
        r"""
        Language hint for ``code_block`` artifacts.
        """
    @property
    def filename(self) -> typing.Optional[builtins.str]:
        r"""
        Filename hint for ``code_block`` artifacts.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Provider-specific metadata for ``custom`` artifacts. Empty for other variants.
        """
    @property
    def custom_kind(self) -> typing.Optional[builtins.str]:
        r"""
        Inner ``kind`` tag for ``custom`` artifacts. Distinct from the top-level
        ``kind`` getter (which returns ``"custom"`` for this variant).
        """
    @staticmethod
    def svg(content: builtins.str, title: typing.Optional[builtins.str] = None) -> Artifact:
        r"""
        Build an SVG artifact.
        """
    @staticmethod
    def code_block(content: builtins.str, language: typing.Optional[builtins.str] = None, filename: typing.Optional[builtins.str] = None) -> Artifact:
        r"""
        Build a code block artifact.
        """
    @staticmethod
    def markdown(content: builtins.str) -> Artifact:
        r"""
        Build a markdown artifact.
        """
    @staticmethod
    def mermaid(content: builtins.str) -> Artifact:
        r"""
        Build a mermaid diagram artifact.
        """
    @staticmethod
    def html(content: builtins.str) -> Artifact:
        r"""
        Build an HTML artifact.
        """
    @staticmethod
    def latex(content: builtins.str) -> Artifact:
        r"""
        Build a LaTeX artifact.
        """
    @staticmethod
    def json(content: typing.Any) -> Artifact:
        r"""
        Build a JSON artifact from a Python dict/list/value.
        """
    @staticmethod
    def custom(kind: builtins.str, content: builtins.str, metadata: typing.Optional[typing.Any] = None) -> Artifact:
        r"""
        Build a custom artifact with an inner kind tag.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class AudioResult:
    r"""
    Result of an audio generation or TTS operation.
    """
    @property
    def audio(self) -> typing.Any:
        r"""
        The generated audio clips (as a list of dicts).
        """
    @property
    def timing(self) -> typing.Any:
        r"""
        Request timing breakdown (as a dict).
        """
    @property
    def cost(self) -> typing.Optional[builtins.float]:
        r"""
        Cost in USD, if reported by the provider.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Arbitrary provider-specific metadata (as a dict).
        """

@typing.final
class AzureOptions:
    r"""
    Options specific to Azure OpenAI.
    """
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    @model.setter
    def model(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def base_url(self) -> typing.Optional[builtins.str]: ...
    @base_url.setter
    def base_url(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def resource_name(self) -> builtins.str: ...
    @resource_name.setter
    def resource_name(self, value: builtins.str) -> None: ...
    @property
    def deployment_name(self) -> builtins.str: ...
    @deployment_name.setter
    def deployment_name(self, value: builtins.str) -> None: ...
    @property
    def api_version(self) -> typing.Optional[builtins.str]: ...
    @api_version.setter
    def api_version(self, value: typing.Optional[builtins.str]) -> None: ...
    def __new__(cls, resource_name: builtins.str, deployment_name: builtins.str, *, model: typing.Optional[builtins.str] = None, base_url: typing.Optional[builtins.str] = None, api_version: typing.Optional[builtins.str] = None) -> AzureOptions:
        r"""
        Create a new AzureOptions.
        
        Args:
            resource_name: Azure resource name (required).
            deployment_name: Azure deployment name (required).
            model: Override the default model identifier.
            base_url: Override the provider's base URL.
            api_version: API version override (e.g. "2024-02-15-preview").
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BackgroundRemovalRequest:
    r"""
    Typed wrapper for a background removal request.
    """
    @property
    def image_url(self) -> builtins.str: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, image_url: builtins.str, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> BackgroundRemovalRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BedrockOptions:
    r"""
    Options specific to AWS Bedrock.
    """
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    @model.setter
    def model(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def base_url(self) -> typing.Optional[builtins.str]: ...
    @base_url.setter
    def base_url(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def region(self) -> builtins.str: ...
    @region.setter
    def region(self, value: builtins.str) -> None: ...
    def __new__(cls, region: builtins.str, *, model: typing.Optional[builtins.str] = None, base_url: typing.Optional[builtins.str] = None) -> BedrockOptions:
        r"""
        Create a new BedrockOptions.
        
        Args:
            region: AWS region (required, e.g. "us-east-1").
            model: Override the default model identifier.
            base_url: Override the provider's base URL.
        """
    def __repr__(self) -> builtins.str: ...

class BlazenState:
    r"""
    Base class for typed workflow state objects.
    
    Subclass with `@dataclass` to get typed, per-field context storage.
    Fields listed in `Meta.transient` are excluded from serialization
    and recreated via the `restore()` hook.
    
    ```python
    @dataclass
    class MyState(BlazenState):
        input_path: str = ""
        conn: sqlite3.Connection | None = None
    
        class Meta:
            transient = {"conn"}
            store_by = {}
    
        def restore(self):
            if self.input_path:
                self.conn = sqlite3.connect(self.input_path)
    ```
    """
    def __new__(cls, **_kwargs: typing.Any) -> BlazenState: ...

@typing.final
class CacheConfig:
    @property
    def strategy(self) -> CacheStrategy: ...
    @strategy.setter
    def strategy(self, value: CacheStrategy) -> None: ...
    @property
    def ttl_seconds(self) -> builtins.int: ...
    @ttl_seconds.setter
    def ttl_seconds(self, value: builtins.int) -> None: ...
    @property
    def max_entries(self) -> builtins.int: ...
    @max_entries.setter
    def max_entries(self, value: builtins.int) -> None: ...
    def __new__(cls, *, strategy: typing.Optional[CacheStrategy] = None, ttl_seconds: builtins.int = 300, max_entries: builtins.int = 1000) -> CacheConfig:
        r"""
        Create a new CacheConfig.
        
        Args:
            strategy: Caching strategy (default: CacheStrategy.ContentHash).
            ttl_seconds: How long a cached response remains valid (default: 300).
            max_entries: Maximum number of cache entries (default: 1000).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ChatMessage:
    r"""
    A single message in a chat conversation.
    
    Example:
        >>> msg = ChatMessage(content="Hello, world!")
        >>> msg = ChatMessage(role="system", content="You are a helpful assistant.")
        >>> msg = ChatMessage.user("What is 2+2?")
    """
    @property
    def role(self) -> builtins.str:
        r"""
        Get the role as a string.
        """
    @property
    def content(self) -> typing.Optional[builtins.str]:
        r"""
        Get the message content as a string.
        """
    def __new__(cls, role: builtins.str = 'user', content: typing.Optional[builtins.str] = None, parts: typing.Optional[typing.Sequence[ContentPart]] = None) -> ChatMessage:
        r"""
        Create a new chat message.
        
        Args:
            role: One of "system", "user", "assistant", "tool" (default: "user").
            content: The message text.
            parts: Optional list of ContentPart objects for multimodal messages.
        """
    @staticmethod
    def system(content: builtins.str) -> ChatMessage:
        r"""
        Create a system message.
        """
    @staticmethod
    def user(content: builtins.str) -> ChatMessage:
        r"""
        Create a user message.
        """
    @staticmethod
    def assistant(content: builtins.str) -> ChatMessage:
        r"""
        Create an assistant message.
        """
    @staticmethod
    def tool(content: builtins.str) -> ChatMessage:
        r"""
        Create a tool result message.
        """
    @staticmethod
    def user_image_url(*, text: builtins.str, url: builtins.str, media_type: typing.Optional[builtins.str] = None) -> ChatMessage:
        r"""
        Create a user message with text and an image URL.
        """
    @staticmethod
    def user_image_base64(*, text: builtins.str, data: builtins.str, media_type: builtins.str) -> ChatMessage:
        r"""
        Create a user message with text and a base64-encoded image.
        """
    @staticmethod
    def user_audio(*, text: builtins.str, url: builtins.str) -> ChatMessage:
        r"""
        Create a user message with text and an audio URL.
        """
    @staticmethod
    def user_audio_base64(*, text: builtins.str, data: builtins.str, media_type: builtins.str) -> ChatMessage:
        r"""
        Create a user message with text and base64-encoded audio.
        """
    @staticmethod
    def user_video(*, text: builtins.str, url: builtins.str) -> ChatMessage:
        r"""
        Create a user message with text and a video URL.
        """
    @staticmethod
    def user_video_base64(*, text: builtins.str, data: builtins.str, media_type: builtins.str) -> ChatMessage:
        r"""
        Create a user message with text and base64-encoded video.
        """
    @staticmethod
    def user_parts(*, parts: typing.Sequence[ContentPart]) -> ChatMessage:
        r"""
        Create a user message from a list of ContentPart objects.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ChatWindow:
    r"""
    A token-windowed conversation memory.
    
    Holds a sequence of ChatMessage objects and automatically evicts the
    oldest messages (preserving system messages) when the token count
    exceeds the configured budget.
    
    Example:
        >>> window = ChatWindow(max_tokens=4096)
        >>> window.add(ChatMessage.system("You are helpful."))
        >>> window.add(ChatMessage.user("Hello!"))
        >>> print(window.token_count())
        >>> print(window.remaining_tokens())
    """
    def __new__(cls, max_tokens: builtins.int) -> ChatWindow:
        r"""
        Create a new chat window with the given token budget.
        
        Args:
            max_tokens: The maximum number of tokens to allow in the window.
        """
    def add(self, message: ChatMessage) -> None:
        r"""
        Append a message to the window.
        
        If the token count exceeds the budget after adding the message,
        the oldest non-system messages are evicted until within budget.
        System messages are never evicted.
        
        Args:
            message: A ChatMessage to add.
        """
    def messages(self) -> builtins.list[ChatMessage]:
        r"""
        Get the current messages in the window.
        
        Returns:
            A list of ChatMessage objects.
        """
    def clear(self) -> None:
        r"""
        Remove all messages from the window.
        """
    def token_count(self) -> builtins.int:
        r"""
        Estimate the total token count of all messages in the window.
        
        Returns:
            The estimated number of tokens.
        """
    def remaining_tokens(self) -> builtins.int:
        r"""
        Return the number of tokens remaining before the budget is reached.
        
        Returns:
            The number of tokens remaining (0 if already at or over budget).
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of messages in the window.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CompletionModel:
    r"""
    A chat completion model.
    
    Use the static constructor methods to create a model for a specific
    provider, then call `complete()` to generate responses.
    
    Example:
        >>> model = CompletionModel.openai("sk-...")
        >>> model = CompletionModel.anthropic("sk-ant-...")
        >>> model = CompletionModel.openrouter("sk-or-...").with_model("meta-llama/llama-3-70b")
        >>>
        >>> response = await model.complete([
        ...     ChatMessage.user("What is 2+2?")
        ... ])
    """
    @property
    def model_id(self) -> builtins.str:
        r"""
        Get the model ID.
        
        Returns:
            The string identifier of the model.
        """
    @staticmethod
    def openai(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create an OpenAI provider.
        
        Args:
            api_key: Your OpenAI API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def anthropic(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create an Anthropic provider.
        
        Args:
            api_key: Your Anthropic API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def gemini(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a Google Gemini provider.
        
        Args:
            api_key: Your Google API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def azure(api_key: builtins.str, *, options: AzureOptions) -> CompletionModel:
        r"""
        Create an Azure OpenAI provider.
        
        Args:
            api_key: Your Azure API key.
            options: Typed ``AzureOptions`` object with required
                ``resource_name`` and ``deployment_name``, plus optional
                ``api_version``.
        """
    @staticmethod
    def openrouter(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create an OpenRouter provider.
        
        Args:
            api_key: Your OpenRouter API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def groq(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a Groq provider.
        
        Args:
            api_key: Your Groq API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def together(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a Together AI provider.
        
        Args:
            api_key: Your Together API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def mistral(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a Mistral provider.
        
        Args:
            api_key: Your Mistral API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def deepseek(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a DeepSeek provider.
        
        Args:
            api_key: Your DeepSeek API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def fireworks(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a Fireworks AI provider.
        
        Args:
            api_key: Your Fireworks API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def perplexity(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a Perplexity provider.
        
        Args:
            api_key: Your Perplexity API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def xai(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create an xAI (Grok) provider.
        
        Args:
            api_key: Your xAI API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def cohere(api_key: builtins.str, *, options: typing.Optional[ProviderOptions] = None) -> CompletionModel:
        r"""
        Create a Cohere provider.
        
        Args:
            api_key: Your Cohere API key.
            options: Optional typed ``ProviderOptions`` object.
        """
    @staticmethod
    def bedrock(api_key: builtins.str, *, options: BedrockOptions) -> CompletionModel:
        r"""
        Create an AWS Bedrock provider.
        
        Args:
            api_key: Your Bedrock API key.
            options: Typed ``BedrockOptions`` object with required ``region``
                and optional ``model``.
        """
    @staticmethod
    def fal(api_key: builtins.str, *, options: typing.Optional[FalOptions] = None) -> CompletionModel:
        r"""
        Create a fal.ai provider.
        
        Args:
            api_key: Your fal.ai API key.
            options: Optional typed ``FalOptions`` object for selecting the
                model, endpoint, enterprise tier, and auto-routing. Defaults to
                the OpenAI-chat endpoint
                (``openrouter/router/openai/v1/chat/completions``).
        """
    def with_retry(self, config: typing.Optional[RetryConfig] = None) -> CompletionModel:
        r"""
        Wrap this model with automatic retry on transient failures.
        
        Returns a new CompletionModel that retries on rate limits,
        timeouts, and server errors with exponential backoff.
        
        Args:
            config: Optional typed ``RetryConfig`` object. Defaults to
                ``RetryConfig()`` (3 retries, 1s initial, 30s max).
        
        Returns:
            A new CompletionModel with retry behaviour.
        
        Example:
            >>> model = CompletionModel.openai("sk-...").with_retry(RetryConfig(max_retries=5))
        """
    @staticmethod
    def with_fallback(models: typing.Sequence[CompletionModel]) -> CompletionModel:
        r"""
        Create a fallback model that tries multiple providers in order.
        
        When the first provider fails with a retryable error, the request
        is forwarded to the next provider. Non-retryable errors (auth,
        validation) short-circuit immediately.
        
        Args:
            models: A list of CompletionModel instances to try in order.
        
        Returns:
            A new CompletionModel that falls back through the providers.
        
        Example:
            >>> primary = CompletionModel.openai("sk-...")
            >>> backup = CompletionModel.anthropic("sk-ant-...")
            >>> model = CompletionModel.with_fallback([primary, backup])
        """
    def with_cache(self, config: typing.Optional[CacheConfig] = None) -> CompletionModel:
        r"""
        Wrap this model with response caching.
        
        Repeated identical requests are served from an in-memory cache
        without hitting the underlying provider. Streaming requests are
        never cached.
        
        Args:
            config: Optional typed ``CacheConfig`` object. Defaults to
                ``CacheConfig()`` (content-hash strategy, 300s TTL, 1000 entries).
        
        Returns:
            A new CompletionModel with caching enabled.
        
        Example:
            >>> model = CompletionModel.openai("sk-...").with_cache(CacheConfig(ttl_seconds=600))
        """
    def complete(self, messages: typing.Sequence[ChatMessage], options: typing.Optional[CompletionOptions] = None) -> typing.Any:
        r"""
        Perform a chat completion.
        
        Args:
            messages: A list of ChatMessage objects.
            temperature: Optional sampling temperature (0.0-2.0).
            max_tokens: Optional maximum tokens to generate.
            top_p: Optional nucleus sampling parameter (0.0-1.0).
            model: Optional model override for this request.
            tools: Optional list of dicts with ``name``, ``description``, and
                ``parameters`` keys for function calling.
            response_format: Optional JSON schema dict for structured output.
        
        Returns:
            A CompletionResponse with content, model, tool_calls, usage,
            and finish_reason attributes.
        
        Example:
            >>> response = await model.complete([
            ...     ChatMessage.system("You are helpful."),
            ...     ChatMessage.user("What is 2+2?"),
            ... ])
            >>> print(response.content)
        """
    def stream(self, messages: typing.Sequence[ChatMessage], on_chunk: typing.Optional[typing.Any] = None, options: typing.Optional[CompletionOptions] = None) -> typing.Any:
        r"""
        Stream a chat completion.
        
        Two usage modes are supported:
        
        1. **Async iterator** (``on_chunk`` omitted) -- returns a
           [`CompletionStream`] which can be consumed with ``async for``.
        2. **Callback** (``on_chunk`` provided) -- returns a coroutine that
           resolves once the stream is exhausted, invoking ``on_chunk`` once
           per [`StreamChunk`].
        
        Args:
            messages: A list of ChatMessage objects.
            on_chunk: Optional callback function receiving each chunk. If
                omitted, the method returns an async iterator.
            options: Optional [`CompletionOptions`] for sampling parameters,
                tools, and response format.
        
        Example (async iterator):
            >>> async for chunk in model.stream([ChatMessage.user("Hi!")]):
            ...     if chunk.delta:
            ...         print(chunk.delta, end="")
        
        Example (callback):
            >>> def handle_chunk(chunk):
            ...     if chunk.delta:
            ...         print(chunk.delta, end="")
            >>> await model.stream([ChatMessage.user("Hi!")], handle_chunk)
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CompletionOptions:
    r"""
    Options for a chat completion request.
    
    Example:
        >>> opts = CompletionOptions(temperature=0.7, max_tokens=1000)
        >>> response = await model.complete(messages, opts)
    """
    @property
    def temperature(self) -> typing.Optional[builtins.float]:
        r"""
        Sampling temperature (0.0-2.0).
        """
    @temperature.setter
    def temperature(self, value: typing.Optional[builtins.float]) -> None:
        r"""
        Sampling temperature (0.0-2.0).
        """
    @property
    def max_tokens(self) -> typing.Optional[builtins.int]:
        r"""
        Maximum tokens to generate.
        """
    @max_tokens.setter
    def max_tokens(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Maximum tokens to generate.
        """
    @property
    def top_p(self) -> typing.Optional[builtins.float]:
        r"""
        Nucleus sampling parameter (0.0-1.0).
        """
    @top_p.setter
    def top_p(self, value: typing.Optional[builtins.float]) -> None:
        r"""
        Nucleus sampling parameter (0.0-1.0).
        """
    @property
    def model(self) -> typing.Optional[builtins.str]:
        r"""
        Model override for this request.
        """
    @model.setter
    def model(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Model override for this request.
        """
    @property
    def tools(self) -> typing.Optional[typing.Any]:
        r"""
        Tool definitions for function calling. Each tool is a dict with
        ``name``, ``description``, and ``parameters`` keys.
        """
    @tools.setter
    def tools(self, value: typing.Optional[typing.Any]) -> None:
        r"""
        Tool definitions for function calling. Each tool is a dict with
        ``name``, ``description``, and ``parameters`` keys.
        """
    @property
    def response_format(self) -> typing.Optional[typing.Any]:
        r"""
        JSON schema dict for structured output.
        """
    @response_format.setter
    def response_format(self, value: typing.Optional[typing.Any]) -> None:
        r"""
        JSON schema dict for structured output.
        """
    def __new__(cls, temperature: typing.Optional[builtins.float] = None, max_tokens: typing.Optional[builtins.int] = None, top_p: typing.Optional[builtins.float] = None, model: typing.Optional[builtins.str] = None, tools: typing.Optional[typing.Any] = None, response_format: typing.Optional[typing.Any] = None) -> CompletionOptions: ...

@typing.final
class CompletionResponse:
    r"""
    The result of a chat completion.
    
    Supports both attribute access and dict-style access for backwards
    compatibility:
        >>> response.content        # attribute
        >>> response["content"]     # dict-style
    """
    @property
    def content(self) -> typing.Optional[builtins.str]: ...
    @property
    def model(self) -> builtins.str: ...
    @property
    def finish_reason(self) -> typing.Optional[builtins.str]: ...
    @property
    def tool_calls(self) -> typing.Any: ...
    @property
    def usage(self) -> typing.Optional[typing.Any]: ...
    @property
    def cost(self) -> typing.Optional[builtins.float]: ...
    @property
    def timing(self) -> typing.Optional[typing.Any]: ...
    @property
    def images(self) -> typing.Any: ...
    @property
    def audio(self) -> typing.Any: ...
    @property
    def videos(self) -> typing.Any: ...
    @property
    def metadata_extra(self) -> typing.Any: ...
    @property
    def reasoning(self) -> typing.Optional[typing.Any]:
        r"""
        Reasoning trace from models that expose one (Anthropic extended thinking,
        DeepSeek R1, OpenAI o-series, xAI Grok, Gemini thoughts).
        """
    @property
    def citations(self) -> typing.Any:
        r"""
        Web/document citations backing the model's statement (Perplexity,
        Gemini grounding, Anthropic web search).
        """
    @property
    def artifacts(self) -> typing.Any:
        r"""
        Typed inline artifacts extracted from the response (SVG, code blocks,
        markdown, mermaid, html, latex, json, custom).
        """
    def finish_reason_normalized(self) -> typing.Optional[FinishReason]:
        r"""
        Lazily map the raw provider finish-reason string into a normalized
        [`FinishReason`].
        """
    def __getitem__(self, key: builtins.str) -> typing.Any: ...
    def keys(self) -> builtins.list[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class CompletionStream:
    r"""
    Async iterator over streamed completion chunks.
    
    Implements the Python `__aiter__` / `__anext__` protocol so it can be used
    with `async for`. The underlying HTTP stream is lazily initialized on the
    first `__anext__` call, allowing the natural one-liner form:
    
        async for chunk in model.stream([ChatMessage.user("Hi!")]):
            ...
    """
    def __aiter__(self) -> CompletionStream: ...
    def __anext__(self) -> typing.Any: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ComputeResult:
    r"""
    Result of a completed compute job (generic, untyped output).
    """
    @property
    def job(self) -> typing.Any:
        r"""
        The job handle that produced this result, if available (as a dict).
        """
    @property
    def output(self) -> typing.Any:
        r"""
        Output data (model-specific JSON).
        """
    @property
    def timing(self) -> typing.Any:
        r"""
        Request timing breakdown (as a dict).
        """
    @property
    def cost(self) -> typing.Optional[builtins.float]:
        r"""
        Cost in USD, if reported by the provider.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Raw provider-specific metadata (as a dict).
        """

@typing.final
class ContentPart:
    @staticmethod
    def text(*, text: builtins.str) -> ContentPart:
        r"""
        Create a text content part.
        """
    @staticmethod
    def image_url(*, url: builtins.str, media_type: typing.Optional[builtins.str] = None) -> ContentPart:
        r"""
        Create an image content part from a URL.
        """
    @staticmethod
    def image_base64(*, data: builtins.str, media_type: builtins.str) -> ContentPart:
        r"""
        Create an image content part from base64 data.
        """
    @staticmethod
    def audio_url(*, url: builtins.str) -> ContentPart:
        r"""
        Create an audio content part from a URL.
        """
    @staticmethod
    def audio_base64(*, data: builtins.str, media_type: builtins.str) -> ContentPart:
        r"""
        Create an audio content part from base64-encoded data.
        """
    @staticmethod
    def video_url(*, url: builtins.str) -> ContentPart:
        r"""
        Create a video content part from a URL.
        """
    @staticmethod
    def video_base64(*, data: builtins.str, media_type: builtins.str) -> ContentPart:
        r"""
        Create a video content part from base64-encoded data.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Context:
    r"""
    Shared workflow context accessible by all steps.
    
    Provides typed key/value storage, event emission, and stream publishing.
    Accepts any Python value — JSON-serializable types, raw bytes, picklable
    objects, or live references for unpicklable objects (DB connections, etc.).
    
    Example:
        >>> def my_step(ctx: Context, ev: Event) -> Event:
        ...     ctx.set("counter", 42)
        ...     ctx.set("model", MyPydanticModel(name="foo"))
        ...     ctx.set("db", sqlite3.connect(":memory:"))
        ...     val = ctx.get("counter")  # returns 42
        ...     db = ctx.get("db")        # returns the same connection
    """
    @property
    def state(self) -> StateNamespace:
        r"""
        Persistable workflow state. Survives `pause()` / `resume()`,
        checkpoints, and durable storage.
        
        ```python
        ctx.state.set("counter", 5)
        count = ctx.state.get("counter")
        ```
        """
    @property
    def session(self) -> SessionNamespace:
        r"""
        Live in-process references. Identity is preserved within a
        single workflow run; subject to the workflow's
        `session_pause_policy` on snapshot.
        
        ```python
        ctx.session.set("conn", sqlite3.connect(":memory:"))
        conn = ctx.session.get("conn")  # same object as above
        ```
        """
    def set(self, key: builtins.str, value: typing.Any) -> None:
        r"""
        Store any value under the given key.
        
        Storage tiers (tried in order):
        1. `bytes`/`bytearray` → raw binary (survives snapshots)
        2. JSON-serializable (dict, list, str, int, float, bool, None) → JSON (survives snapshots)
        3. Picklable objects (Pydantic, dataclasses, etc.) → pickled bytes (survives snapshots)
        4. Unpicklable objects (DB connections, file handles) → live reference (same-process only)
        
        Args:
            key: The storage key.
            value: Any Python value.
        """
    def get(self, key: builtins.str) -> typing.Any:
        r"""
        Retrieve a value previously stored under the given key.
        
        Returns the original Python type: JSON values as their Python
        equivalents, binary data as `bytes`, pickled objects as their
        original type, live references as-is. Returns `None` if the key
        does not exist.
        
        Args:
            key: The storage key.
        
        Returns:
            The stored value in its original type, or None.
        """
    def send_event(self, event: Event) -> None:
        r"""
        Emit an event into the internal routing queue.
        
        The event will be routed to any step whose `accepts` list includes
        its event type.
        
        Args:
            event: The event to send.
        """
    def write_event_to_stream(self, event: Event) -> None:
        r"""
        Publish an event to the external broadcast stream.
        
        Consumers that subscribed via `WorkflowHandler.stream_events()` will
        receive this event. Unlike `send_event`, this does NOT route the
        event through the internal step registry.
        
        Args:
            event: The event to publish to the stream.
        """
    def get_bytes(self, key: builtins.str) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Retrieve raw binary data previously stored under the given key.
        
        Returns None if the key does not exist or the stored value is
        not binary data.
        
        Args:
            key: The storage key.
        
        Returns:
            The stored bytes, or None.
        """
    def run_id(self) -> builtins.str:
        r"""
        Get the workflow run ID.
        
        Returns:
            The UUID string for this workflow run.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class EmbeddingModel:
    r"""
    A text embedding model.
    
    Use the static constructor methods to create a model for a specific
    provider, then call `embed()` to generate embeddings.
    
    Example:
        >>> model = EmbeddingModel.openai("sk-...")
        >>> response = await model.embed(["Hello", "World"])
        >>> print(response.embeddings)
    """
    @property
    def model_id(self) -> builtins.str:
        r"""
        Get the model ID.
        
        Returns:
            The string identifier of the embedding model.
        """
    @property
    def dimensions(self) -> builtins.int:
        r"""
        Get the output dimensionality of the embedding model.
        
        Returns:
            The number of dimensions in the output vectors.
        """
    @staticmethod
    def openai(api_key: builtins.str, model: typing.Optional[builtins.str] = None, dimensions: typing.Optional[builtins.int] = None) -> EmbeddingModel:
        r"""
        Create an OpenAI embedding model.
        
        Args:
            api_key: Your OpenAI API key.
            model: Optional model name (default: "text-embedding-3-small").
            dimensions: Optional output dimensions (default: 1536).
        """
    @staticmethod
    def together(api_key: builtins.str) -> EmbeddingModel:
        r"""
        Create a Together AI embedding model.
        
        Args:
            api_key: Your Together API key.
        """
    @staticmethod
    def cohere(api_key: builtins.str) -> EmbeddingModel:
        r"""
        Create a Cohere embedding model.
        
        Args:
            api_key: Your Cohere API key.
        """
    @staticmethod
    def fireworks(api_key: builtins.str) -> EmbeddingModel:
        r"""
        Create a Fireworks AI embedding model.
        
        Args:
            api_key: Your Fireworks API key.
        """
    def embed(self, texts: typing.Sequence[builtins.str]) -> typing.Any:
        r"""
        Embed one or more texts.
        
        Args:
            texts: A list of strings to embed.
        
        Returns:
            An EmbeddingResponse with embeddings, model, usage, and cost.
        
        Example:
            >>> response = await model.embed(["Hello", "World"])
            >>> print(len(response.embeddings))  # 2
            >>> print(len(response.embeddings[0]))  # dimensionality
        """
    def __repr__(self) -> builtins.str: ...

class Event:
    r"""
    A dict-like event object exposed to Python.
    
    Python usage:
    ```python
    ev = Event("AnalyzeEvent", text="hello", score=0.9)
    print(ev.text)       # "hello"
    print(ev.to_dict())  # {"text": "hello", "score": 0.9}
    ```
    """
    @property
    def event_type(self) -> builtins.str:
        r"""
        The event type name (e.g. `"AnalyzeEvent"`).
        """
    @event_type.setter
    def event_type(self, value: builtins.str) -> None:
        r"""
        The event type name (e.g. `"AnalyzeEvent"`).
        """
    def __new__(cls, event_type: typing.Optional[builtins.str] = None, **kwargs: typing.Any) -> Event:
        r"""
        Create a new event.
        
        When called on the base `Event` class, `event_type` is required:
            `Event("MyEvent", key=value)`
        
        When called on a subclass, `event_type` is auto-inferred from the
        class name:
            `class MyEvent(Event): ...`
            `MyEvent(key=value)`  # event_type == "MyEvent"
        Create a new event.
        
        - Base `Event` class: `Event("MyEvent", key=value)`
        - Subclasses: `MyEvent(key=value)` — event_type auto-set by `__init__`
        """
    def __getattr__(self, name: builtins.str) -> typing.Any:
        r"""
        Attribute access delegates to the underlying JSON data.
        """
    def to_dict(self) -> typing.Any:
        r"""
        Convert the event data to a Python dict.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    @classmethod
    def __init_subclass__(cls, **_kwargs: typing.Any) -> None:
        r"""
        Called when a Python subclass of Event is defined.
        
        Auto-generates an `__init__` that sets `event_type` to the class name,
        enabling:
        ```python
        class GreetEvent(Event):
            name: str
            style: str
        
        ev = GreetEvent(name="Alice", style="formal")
        # ev.event_type == "GreetEvent"
        ```
        """

@typing.final
class FalEmbeddingModel:
    r"""
    A fal.ai embedding model.
    
    Wraps [`FalEmbeddingModel`] and exposes the
    [`EmbeddingModel`](blazen_llm::traits::EmbeddingModel) interface to
    Python. Constructed via [`FalProvider::embedding_model`].
    
    Example:
        >>> fal = FalProvider(api_key="fal-...")
        >>> em = fal.embedding_model()
        >>> resp = await em.embed(["hello", "world"])
        >>> print(len(resp.embeddings))  # 2
    """
    @property
    def model_id(self) -> builtins.str:
        r"""
        Get the underlying embedding model id.
        """
    @property
    def dimensions(self) -> builtins.int:
        r"""
        Get the dimensionality of the produced embedding vectors.
        """
    def embed(self, texts: typing.Sequence[builtins.str]) -> typing.Any:
        r"""
        Embed one or more texts.
        
        Args:
            texts: A list of strings to embed.
        
        Returns:
            An EmbeddingResponse with embeddings, model, usage, and cost.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FalOptions:
    r"""
    Options specific to the fal.ai provider.
    """
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    @model.setter
    def model(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def base_url(self) -> typing.Optional[builtins.str]: ...
    @base_url.setter
    def base_url(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def enterprise(self) -> builtins.bool: ...
    @enterprise.setter
    def enterprise(self, value: builtins.bool) -> None: ...
    @property
    def auto_route_modality(self) -> builtins.bool: ...
    @auto_route_modality.setter
    def auto_route_modality(self, value: builtins.bool) -> None: ...
    def __new__(cls, *, model: typing.Optional[builtins.str] = None, base_url: typing.Optional[builtins.str] = None, endpoint: typing.Optional[FalLlmEndpointKind] = None, enterprise: builtins.bool = False, auto_route_modality: builtins.bool = True) -> FalOptions:
        r"""
        Create a new FalOptions.
        
        Args:
            model: Override the default model identifier.
            base_url: Override the provider's base URL.
            endpoint: The fal endpoint family (defaults to OpenAiChat).
            enterprise: Promote the endpoint to its enterprise / SOC2-eligible variant.
            auto_route_modality: Auto-route to vision/audio/video variant when content has media.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FalProvider:
    r"""
    A fal.ai provider that supports LLM completions AND compute operations.
    
    This is the unified entry point for all fal.ai capabilities:
    - Image generation, upscaling, and background removal
    - Video generation (text-to-video, image-to-video)
    - Audio generation (TTS, music, sound effects)
    - Audio transcription
    - 3D model generation
    - Text embeddings (via the OpenAI-compatible router)
    - Raw compute job submission
    - LLM chat completions (default endpoint:
      ``openrouter/router/openai/v1/chat/completions`` -- ``OpenAiChat``)
    
    Example:
        >>> fal = FalProvider(api_key="fal-key-...")
        >>> result = await fal.generate_image(ImageRequest(prompt="a cat in space"))
        >>> response = await fal.complete([ChatMessage.user("Hello!")])
    """
    @property
    def model_id(self) -> builtins.str:
        r"""
        Get the model ID.
        """
    def __new__(cls, *, api_key: builtins.str, options: typing.Optional[FalOptions] = None) -> FalProvider:
        r"""
        Create a new fal.ai provider.
        
        Args:
            api_key: Your fal.ai API key.
            options: Optional [`FalOptions`] for model, endpoint, enterprise,
                and auto-routing configuration.
        """
    def generate_image(self, request: ImageRequest) -> typing.Any:
        r"""
        Generate images from a text prompt.
        
        Args:
            request: An [`ImageRequest`] with prompt, dimensions, etc.
        
        Returns:
            An [`ImageResult`] with images, timing, cost, and metadata.
        """
    def upscale_image(self, request: UpscaleRequest) -> typing.Any:
        r"""
        Upscale an image.
        
        Args:
            request: An [`UpscaleRequest`] with image_url and scale factor.
        
        Returns:
            An [`ImageResult`] with the upscaled image, timing, cost, and metadata.
        """
    def upscale_image_aura(self, request: UpscaleRequest) -> typing.Any:
        r"""
        Upscale an image via the aura-sr model.
        
        Args:
            request: An [`UpscaleRequest`] with image_url and scale factor.
        
        Returns:
            An [`ImageResult`] with the upscaled image, timing, cost, and metadata.
        """
    def upscale_image_clarity(self, request: UpscaleRequest) -> typing.Any:
        r"""
        Upscale an image via the clarity-upscaler model.
        
        Args:
            request: An [`UpscaleRequest`] with image_url and scale factor.
        
        Returns:
            An [`ImageResult`] with the upscaled image, timing, cost, and metadata.
        """
    def upscale_image_creative(self, request: UpscaleRequest) -> typing.Any:
        r"""
        Upscale an image via the creative-upscaler model.
        
        Args:
            request: An [`UpscaleRequest`] with image_url and scale factor.
        
        Returns:
            An [`ImageResult`] with the upscaled image, timing, cost, and metadata.
        """
    def remove_background(self, request: BackgroundRemovalRequest) -> typing.Any:
        r"""
        Remove the background from an image.
        
        Args:
            request: A [`BackgroundRemovalRequest`] with image_url and optional model.
        
        Returns:
            An [`ImageResult`] with the matted image, timing, cost, and metadata.
        """
    def generate_3d(self, request: ThreeDRequest) -> typing.Any:
        r"""
        Generate a 3D model from a text prompt or source image.
        
        Args:
            request: A [`ThreeDRequest`] with prompt and/or image_url.
        
        Returns:
            A [`ThreeDResult`] with the generated 3D model, timing, cost, and metadata.
        """
    def embedding_model(self) -> FalEmbeddingModel:
        r"""
        Build a [`FalEmbeddingModel`] sharing this provider's HTTP client and API key.
        
        Returns:
            A FalEmbeddingModel that can be used to embed text via fal's
            OpenAI-compatible router.
        """
    def text_to_video(self, request: VideoRequest) -> typing.Any:
        r"""
        Generate a video from a text prompt.
        
        Args:
            request: A [`VideoRequest`] with prompt and optional parameters.
        
        Returns:
            A [`VideoResult`] with videos, timing, cost, and metadata.
        """
    def image_to_video(self, request: VideoRequest) -> typing.Any:
        r"""
        Generate a video from a source image and prompt.
        
        Args:
            request: A [`VideoRequest`] with prompt and image_url.
        
        Returns:
            A [`VideoResult`] with videos, timing, cost, and metadata.
        """
    def text_to_speech(self, request: SpeechRequest) -> typing.Any:
        r"""
        Synthesize speech from text.
        
        Args:
            request: A [`SpeechRequest`] with text and optional voice/language.
        
        Returns:
            An [`AudioResult`] with audio clips, timing, cost, and metadata.
        """
    def generate_music(self, request: MusicRequest) -> typing.Any:
        r"""
        Generate music from a prompt.
        
        Args:
            request: A [`MusicRequest`] with prompt and optional duration.
        
        Returns:
            An [`AudioResult`] with audio clips, timing, cost, and metadata.
        """
    def generate_sfx(self, request: MusicRequest) -> typing.Any:
        r"""
        Generate sound effects from a prompt.
        
        Args:
            request: A [`MusicRequest`] with prompt and optional duration.
        
        Returns:
            An [`AudioResult`] with audio clips, timing, cost, and metadata.
        """
    def transcribe(self, request: TranscriptionRequest) -> typing.Any:
        r"""
        Transcribe audio to text.
        
        Args:
            request: A [`TranscriptionRequest`] with audio_url and options.
        
        Returns:
            A [`TranscriptionResult`] with text, segments, language, timing,
            cost, and metadata.
        """
    def complete(self, messages: typing.Sequence[ChatMessage], options: typing.Optional[CompletionOptions] = None) -> typing.Any:
        r"""
        Perform a chat completion via fal-ai/any-llm.
        
        Args:
            messages: A list of ChatMessage objects.
            options: Optional [`CompletionOptions`] for sampling parameters,
                tools, and response format.
        
        Returns:
            A CompletionResponse with content, model, tool_calls, usage, etc.
        """
    def stream(self, messages: typing.Sequence[ChatMessage], on_chunk: typing.Any, options: typing.Optional[CompletionOptions] = None) -> typing.Any:
        r"""
        Stream a chat completion, calling a callback for each chunk.
        
        Args:
            messages: A list of ChatMessage objects.
            on_chunk: Callback function receiving each chunk as a dict.
            options: Optional [`CompletionOptions`] for sampling parameters,
                tools, and response format.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FinishReason:
    r"""
    Normalized finish reason across providers.
    
    Maps provider-specific finish-reason strings (``"stop"``, ``"end_turn"``,
    ``"STOP"``, ``"length"``, ``"tool_calls"``, ``"max_tokens"``, etc.) into a
    canonical set. Unknown values fall through to ``kind == "other"``.
    
    Use ``kind`` for the canonical category and ``value`` for the original
    provider string.
    
    Example:
        >>> normalized = response.finish_reason_normalized()
        >>> if normalized is not None and normalized.kind == "tool_calls":
        ...     handle_tool_calls(response.tool_calls)
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        Canonical category.
        
        One of: ``"stop"``, ``"length"``, ``"tool_calls"``, ``"content_filter"``,
        ``"safety"``, ``"end_turn"``, ``"stop_sequence"``, ``"max_tokens"``,
        ``"error"``, or ``"other"``.
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The raw provider string.
        
        For canonical variants this equals ``kind``. For ``Other(s)`` it
        returns the original string the provider sent.
        """
    @staticmethod
    def from_provider_string(s: builtins.str) -> FinishReason:
        r"""
        Build a [`FinishReason`] from a raw provider string.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: FinishReason) -> builtins.bool: ...

@typing.final
class Generated3DModel:
    r"""
    A single generated 3D model with optional mesh metadata.
    """
    @property
    def media(self) -> MediaOutput:
        r"""
        The underlying media output.
        """
    @property
    def vertex_count(self) -> typing.Optional[builtins.int]:
        r"""
        Total vertex count, if known.
        """
    @property
    def face_count(self) -> typing.Optional[builtins.int]:
        r"""
        Total face/triangle count, if known.
        """
    @property
    def has_textures(self) -> builtins.bool:
        r"""
        Whether the model includes texture data.
        """
    @property
    def has_animations(self) -> builtins.bool:
        r"""
        Whether the model includes animation data.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GeneratedAudio:
    r"""
    A single generated audio clip with optional metadata.
    """
    @property
    def media(self) -> MediaOutput:
        r"""
        The underlying media output.
        """
    @property
    def duration_seconds(self) -> typing.Optional[builtins.float]:
        r"""
        Duration in seconds, if known.
        """
    @property
    def sample_rate(self) -> typing.Optional[builtins.int]:
        r"""
        Sample rate in Hz, if known.
        """
    @property
    def channels(self) -> typing.Optional[builtins.int]:
        r"""
        Number of audio channels, if known.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GeneratedImage:
    r"""
    A single generated image with optional dimension metadata.
    """
    @property
    def media(self) -> MediaOutput:
        r"""
        The underlying media output.
        """
    @property
    def width(self) -> typing.Optional[builtins.int]:
        r"""
        Image width in pixels, if known.
        """
    @property
    def height(self) -> typing.Optional[builtins.int]:
        r"""
        Image height in pixels, if known.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GeneratedVideo:
    r"""
    A single generated video with optional metadata.
    """
    @property
    def media(self) -> MediaOutput:
        r"""
        The underlying media output.
        """
    @property
    def width(self) -> typing.Optional[builtins.int]:
        r"""
        Video width in pixels, if known.
        """
    @property
    def height(self) -> typing.Optional[builtins.int]:
        r"""
        Video height in pixels, if known.
        """
    @property
    def duration_seconds(self) -> typing.Optional[builtins.float]:
        r"""
        Duration in seconds, if known.
        """
    @property
    def fps(self) -> typing.Optional[builtins.float]:
        r"""
        Frames per second, if known.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ImageRequest:
    r"""
    Typed wrapper for a text-to-image request.
    """
    @property
    def prompt(self) -> builtins.str: ...
    @property
    def negative_prompt(self) -> typing.Optional[builtins.str]: ...
    @property
    def width(self) -> typing.Optional[builtins.int]: ...
    @property
    def height(self) -> typing.Optional[builtins.int]: ...
    @property
    def num_images(self) -> typing.Optional[builtins.int]: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, prompt: builtins.str, negative_prompt: typing.Optional[builtins.str] = None, width: typing.Optional[builtins.int] = None, height: typing.Optional[builtins.int] = None, num_images: typing.Optional[builtins.int] = None, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> ImageRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ImageResult:
    r"""
    Result of an image generation or upscale operation.
    """
    @property
    def images(self) -> typing.Any:
        r"""
        The generated or upscaled images (as a list of dicts).
        """
    @property
    def timing(self) -> typing.Any:
        r"""
        Request timing breakdown (as a dict).
        """
    @property
    def cost(self) -> typing.Optional[builtins.float]:
        r"""
        Cost in USD, if reported by the provider.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Arbitrary provider-specific metadata (as a dict).
        """

@typing.final
class InMemoryBackend:
    r"""
    An in-memory storage backend for Memory.
    
    Data lives only as long as the process -- nothing is persisted to disk.
    Suitable for testing, prototyping, and short-lived processes.
    
    Example:
        >>> backend = InMemoryBackend()
        >>> memory = Memory(embedder, backend)
    """
    def __new__(cls) -> InMemoryBackend:
        r"""
        Create a new, empty in-memory backend.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class JsonlBackend:
    r"""
    A JSONL file-backed storage backend for Memory.
    
    Loads entries from the file on construction and appends new entries to
    the file. Deletions trigger a full rewrite.
    
    Example:
        >>> backend = await JsonlBackend.create("memories.jsonl")
        >>> memory = Memory(embedder, backend)
    """
    @staticmethod
    def create(path: builtins.str) -> typing.Any:
        r"""
        Create a new JSONL backend at the given file path.
        
        This is an async constructor because the file is loaded on creation.
        
        Args:
            path: Path to the JSONL file. Created if it does not exist.
        
        Returns:
            A new JsonlBackend instance.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MediaOutput:
    r"""
    A single piece of generated media content.
    
    At least one of `url`, `base64`, or `raw_content` will be populated.
    `raw_content` is used for text-based formats like SVG, OBJ, and GLTF JSON.
    """
    @property
    def url(self) -> typing.Optional[builtins.str]:
        r"""
        URL where the media can be downloaded.
        """
    @property
    def base64(self) -> typing.Optional[builtins.str]:
        r"""
        Base64-encoded media data.
        """
    @property
    def raw_content(self) -> typing.Optional[builtins.str]:
        r"""
        Raw text content for text-based formats (SVG, OBJ, GLTF JSON).
        """
    @property
    def media_type(self) -> builtins.str:
        r"""
        The media type as a MIME string (e.g. `"image/png"`).
        """
    @property
    def file_size(self) -> typing.Optional[builtins.int]:
        r"""
        File size in bytes, if known.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Arbitrary provider-specific metadata as a Python dict.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MediaType:
    r"""
    Media type constants for identifying file formats.
    
    Example:
        >>> MediaType.PNG   # "image/png"
        >>> MediaType.MP4   # "video/mp4"
        >>> MediaType.MP3   # "audio/mpeg"
    """
    PNG: builtins.str = 'image/png'
    JPEG: builtins.str = 'image/jpeg'
    WEBP: builtins.str = 'image/webp'
    GIF: builtins.str = 'image/gif'
    SVG: builtins.str = 'image/svg+xml'
    BMP: builtins.str = 'image/bmp'
    TIFF: builtins.str = 'image/tiff'
    AVIF: builtins.str = 'image/avif'
    MP4: builtins.str = 'video/mp4'
    WEBM: builtins.str = 'video/webm'
    MOV: builtins.str = 'video/quicktime'
    MP3: builtins.str = 'audio/mpeg'
    WAV: builtins.str = 'audio/wav'
    OGG: builtins.str = 'audio/ogg'
    FLAC: builtins.str = 'audio/flac'
    AAC: builtins.str = 'audio/aac'
    M4A: builtins.str = 'audio/mp4'
    GLB: builtins.str = 'model/gltf-binary'
    GLTF: builtins.str = 'model/gltf+json'
    OBJ: builtins.str = 'model/obj'
    USDZ: builtins.str = 'model/vnd.usdz+zip'
    FBX: builtins.str = 'application/octet-stream'
    STL: builtins.str = 'model/stl'
    PDF: builtins.str = 'application/pdf'

@typing.final
class Memory:
    r"""
    A memory store with optional embedding-based semantic search.
    
    When created with an EmbeddingModel (``Memory(embedder, backend)``),
    both ``search()`` (semantic) and ``search_local()`` (SimHash) are available.
    
    When created in local mode (``Memory.local(backend)``), only
    ``search_local()`` is available -- no embedding model is required.
    
    Example:
        >>> embedder = EmbeddingModel.openai(key)
        >>> memory = Memory(embedder, InMemoryBackend())
        >>> await memory.add("doc1", "Paris is the capital of France")
        >>> results = await memory.search("France capital", limit=5)
        >>> print(results[0].text)
    """
    def __new__(cls, embedder: EmbeddingModel, backend: typing.Any) -> Memory:
        r"""
        Create a Memory with an embedding model for full semantic search.
        
        Args:
            embedder: An EmbeddingModel instance.
            backend: A backend instance (InMemoryBackend, JsonlBackend, or ValkeyBackend).
        """
    @staticmethod
    def local(backend: typing.Any) -> Memory:
        r"""
        Create a Memory in local-only mode (no embedding model).
        
        Only ``search_local()`` is available; ``search()`` will raise an error.
        
        Args:
            backend: A backend instance (InMemoryBackend, JsonlBackend, or ValkeyBackend).
        """
    def add(self, id: builtins.str, text: builtins.str, metadata: typing.Optional[typing.Any] = None) -> typing.Any:
        r"""
        Add a document to the memory store.
        
        Args:
            id: A unique identifier for the document. If empty, a UUID is generated.
            text: The text content to store.
            metadata: Optional metadata dict to attach.
        
        Returns:
            The id of the stored document.
        """
    def add_many(self, entries: typing.Sequence[typing.Any]) -> typing.Any:
        r"""
        Add multiple documents to the memory store in a single batch.
        
        Args:
            entries: A list of dicts, each with "id" (optional), "text", and "metadata" (optional) keys.
        
        Returns:
            A list of ids for the stored documents.
        """
    def search(self, query: builtins.str, limit: builtins.int = 5, metadata_filter: typing.Optional[typing.Any] = None) -> typing.Any:
        r"""
        Semantic search using the configured embedding model.
        
        Requires an embedding model to be configured (i.e. not local-only mode).
        
        Args:
            query: The search query string.
            limit: Maximum number of results to return (default: 5).
            metadata_filter: Optional dict of key-value pairs to filter results.
                Only entries whose metadata is a superset of the filter are
                returned. For example, ``{"category": "news"}`` matches entries
                that have at least ``category: "news"`` in their metadata.
        
        Returns:
            A list of MemoryResult objects sorted by descending similarity.
        """
    def search_local(self, query: builtins.str, limit: builtins.int = 5, metadata_filter: typing.Optional[typing.Any] = None) -> typing.Any:
        r"""
        Local SimHash-based search (no embedding model required).
        
        Uses string-level SimHash for lightweight similarity search.
        Works in both full and local-only modes.
        
        Args:
            query: The search query string.
            limit: Maximum number of results to return (default: 5).
            metadata_filter: Optional dict of key-value pairs to filter results.
                Only entries whose metadata is a superset of the filter are
                returned. See ``search()`` for details.
        
        Returns:
            A list of MemoryResult objects sorted by descending similarity.
        """
    def get(self, id: builtins.str) -> typing.Any:
        r"""
        Retrieve a single entry by its id.
        
        Args:
            id: The document id.
        
        Returns:
            A dict with the entry data, or None if not found.
        """
    def delete(self, id: builtins.str) -> typing.Any:
        r"""
        Delete a document by its id.
        
        Args:
            id: The document id to delete.
        
        Returns:
            True if the document existed and was deleted, False otherwise.
        """
    def count(self) -> typing.Any:
        r"""
        Return the number of documents in the store.
        
        Returns:
            The document count.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MemoryResult:
    r"""
    A single search result from a Memory search.
    
    Example:
        >>> results = await memory.search("France capital", limit=5)
        >>> results[0].id
        'doc1'
        >>> results[0].text
        'Paris is the capital of France'
        >>> results[0].score
        0.85
    """
    @property
    def id(self) -> builtins.str:
        r"""
        The entry's unique identifier.
        """
    @property
    def text(self) -> builtins.str:
        r"""
        The original text content.
        """
    @property
    def score(self) -> builtins.float:
        r"""
        Similarity score in [0.0, 1.0], higher means more similar.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Arbitrary user metadata (returned as a Python dict/value).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MusicRequest:
    r"""
    Typed wrapper for a music/SFX generation request.
    """
    @property
    def prompt(self) -> builtins.str: ...
    @property
    def duration_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, prompt: builtins.str, duration_seconds: typing.Optional[builtins.float] = None, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> MusicRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PromptRegistry:
    r"""
    A versioned registry for prompt templates.
    
    Organises templates by name and version, with convenient lookup,
    rendering, and file I/O.
    
    Example::
    
        registry = PromptRegistry()
        registry.register("greet", PromptTemplate("Hello {{name}}!"))
        msg = registry.render("greet", name="Alice")
        print(msg.content)
    """
    def __new__(cls) -> PromptRegistry:
        r"""
        Create a new empty prompt registry.
        """
    def register(self, name: builtins.str, template: PromptTemplate) -> None:
        r"""
        Register a template under the given name.
        
        The template's internal name is updated to match the provided name.
        If a template with the same name and version already exists, it is
        replaced.
        
        Args:
            name: The name to register the template under.
            template: The ``PromptTemplate`` to register.
        """
    def get(self, name: builtins.str) -> typing.Optional[PromptTemplate]:
        r"""
        Get the latest version of a template by name.
        
        Args:
            name: The template name.
        
        Returns:
            The ``PromptTemplate`` or ``None`` if not found.
        """
    def render(self, name: builtins.str, **variables: typing.Any) -> ChatMessage:
        r"""
        Render the latest version of the named template.
        
        Args:
            name: The template name.
            **variables: Template variables as keyword arguments.
        
        Returns:
            A ``ChatMessage`` with the rendered content.
        
        Raises:
            KeyError: If no template with that name exists.
            ValueError: If a required variable is missing.
        """
    def list(self) -> builtins.list[builtins.str]:
        r"""
        List all registered template names (sorted).
        
        Returns:
            A list of template name strings.
        """
    @staticmethod
    def from_file(path: builtins.str) -> PromptRegistry:
        r"""
        Load a registry from a YAML or JSON file.
        
        The file format is detected by extension (``.yaml``/``.yml`` for YAML,
        ``.json`` for JSON).
        
        Args:
            path: Path to the prompt file.
        
        Returns:
            A new ``PromptRegistry`` with the loaded templates.
        
        Raises:
            IOError: If the file cannot be read.
            ValueError: If the file format is unsupported or parsing fails.
        """
    @staticmethod
    def from_dir(path: builtins.str) -> PromptRegistry:
        r"""
        Load all prompt files from a directory.
        
        Reads all ``.yaml``, ``.yml``, and ``.json`` files in the directory.
        
        Args:
            path: Path to the directory.
        
        Returns:
            A new ``PromptRegistry`` with the loaded templates.
        
        Raises:
            IOError: If the directory cannot be read.
            ValueError: If any file fails to parse.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PromptTemplate:
    r"""
    A reusable prompt template with ``{{variable}}`` placeholders.
    
    Templates are rendered by replacing ``{{var}}`` placeholders with the
    provided keyword arguments.
    
    Example::
    
        t = PromptTemplate("Hello {{name}}!", role="user")
        msg = t.render(name="Alice")
        print(msg.content)  # "Hello Alice!"
    """
    @property
    def template(self) -> builtins.str:
        r"""
        The raw template string.
        """
    @property
    def role(self) -> builtins.str:
        r"""
        The chat role ("system", "user", or "assistant").
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The template name.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        The optional description.
        """
    @property
    def version(self) -> builtins.str:
        r"""
        The version string.
        """
    @property
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        The sorted list of variable names in this template.
        """
    def __new__(cls, template: builtins.str, *, role: typing.Optional[builtins.str] = None, name: typing.Optional[builtins.str] = None, description: typing.Optional[builtins.str] = None, version: typing.Optional[builtins.str] = None) -> PromptTemplate:
        r"""
        Create a new prompt template.
        
        Args:
            template: The template string with ``{{variable}}`` placeholders.
            role: The chat role ("system", "user", or "assistant"). Defaults to "user".
            name: A unique name for this template (defaults to "unnamed").
            description: An optional description of this template.
            version: The version string (defaults to "1.0").
        """
    def render(self, **variables: typing.Any) -> ChatMessage:
        r"""
        Render the template with the given keyword arguments.
        
        Returns a ``ChatMessage`` with the rendered content and the
        template's role.
        
        Args:
            **variables: Template variables as keyword arguments.
        
        Raises:
            ValueError: If a required variable is missing.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ProviderOptions:
    r"""
    Base options shared by every provider.
    """
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    @model.setter
    def model(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def base_url(self) -> typing.Optional[builtins.str]: ...
    @base_url.setter
    def base_url(self, value: typing.Optional[builtins.str]) -> None: ...
    def __new__(cls, *, model: typing.Optional[builtins.str] = None, base_url: typing.Optional[builtins.str] = None) -> ProviderOptions:
        r"""
        Create a new ProviderOptions.
        
        Args:
            model: Override the default model identifier.
            base_url: Override the provider's base URL.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ResponseFormat:
    r"""
    Typed response-format hint for structured output.
    
    Use ``ResponseFormat.text()`` for free-form text, ``ResponseFormat.json_object()``
    for any JSON object, or ``ResponseFormat.json_schema(name, schema)`` for
    JSON-Schema-validated structured output.
    
    Example:
        >>> rf = ResponseFormat.json_schema("Person", {"type": "object", ...})
        >>> options = CompletionOptions(response_format=rf.to_dict())
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        Discriminator. One of ``"text"``, ``"json_object"``, ``"json_schema"``.
        """
    @property
    def schema_name(self) -> typing.Optional[builtins.str]:
        r"""
        Schema name for ``json_schema`` variants. ``None`` otherwise.
        """
    @property
    def schema(self) -> typing.Optional[typing.Any]:
        r"""
        Schema body for ``json_schema`` variants, returned as a Python dict.
        ``None`` otherwise.
        """
    @property
    def strict(self) -> builtins.bool:
        r"""
        Whether the schema is strict (``json_schema`` variants only). Defaults
        to ``False`` for non-schema variants.
        """
    def to_dict(self) -> typing.Any:
        r"""
        Serialize this response format to a JSON-compatible dict suitable for
        passing to ``CompletionOptions.response_format``.
        """
    @staticmethod
    def text() -> ResponseFormat:
        r"""
        Build a free-text response format.
        """
    @staticmethod
    def json_object() -> ResponseFormat:
        r"""
        Build a JSON-object response format (any valid JSON object).
        """
    @staticmethod
    def json_schema(name: builtins.str, schema: typing.Any, strict: builtins.bool = True) -> ResponseFormat:
        r"""
        Build a JSON-Schema response format.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RetryConfig:
    @property
    def max_retries(self) -> builtins.int: ...
    @max_retries.setter
    def max_retries(self, value: builtins.int) -> None: ...
    @property
    def initial_delay_ms(self) -> builtins.int: ...
    @initial_delay_ms.setter
    def initial_delay_ms(self, value: builtins.int) -> None: ...
    @property
    def max_delay_ms(self) -> builtins.int: ...
    @max_delay_ms.setter
    def max_delay_ms(self, value: builtins.int) -> None: ...
    @property
    def honor_retry_after(self) -> builtins.bool: ...
    @honor_retry_after.setter
    def honor_retry_after(self, value: builtins.bool) -> None: ...
    @property
    def jitter(self) -> builtins.bool: ...
    @jitter.setter
    def jitter(self, value: builtins.bool) -> None: ...
    def __new__(cls, *, max_retries: builtins.int = 3, initial_delay_ms: builtins.int = 1000, max_delay_ms: builtins.int = 30000, honor_retry_after: builtins.bool = True, jitter: builtins.bool = True) -> RetryConfig:
        r"""
        Create a new RetryConfig.
        
        Args:
            max_retries: Maximum retry attempts (default: 3).
            initial_delay_ms: Delay before first retry (default: 1000).
            max_delay_ms: Maximum backoff delay (default: 30000).
            honor_retry_after: Honor server retry_after (default: True).
            jitter: Add random jitter (default: True).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Role:
    r"""
    Role constants for chat messages.
    
    Example:
        >>> ChatMessage(role=Role.USER, content="Hello!")
        >>> ChatMessage(role=Role.SYSTEM, content="You are helpful.")
    """
    SYSTEM: builtins.str = 'system'
    USER: builtins.str = 'user'
    ASSISTANT: builtins.str = 'assistant'
    TOOL: builtins.str = 'tool'

@typing.final
class SessionNamespace:
    r"""
    Namespace for live in-process references.
    
    Values are stored as `Arc<Py<PyAny>>` in the underlying
    `ContextInner.objects` map. Identity is preserved within a single
    workflow run; the entries are *not* serialised into snapshots
    (subject to the workflow's `session_pause_policy` for what happens
    at pause time).
    """
    def set(self, key: builtins.str, value: typing.Any) -> None:
        r"""
        Store a live reference under the given key. The value is *not*
        serialised; identity is preserved within this run.
        """
    def get(self, key: builtins.str) -> typing.Optional[typing.Any]:
        r"""
        Retrieve a live reference previously stored under the given key.
        Returns `None` if the key does not exist.
        """
    def remove(self, key: builtins.str) -> None:
        r"""
        Remove a live reference stored under the given key.
        """
    def has(self, key: builtins.str) -> builtins.bool:
        r"""
        Check whether a live reference exists under the given key.
        """
    def __setitem__(self, key: builtins.str, value: typing.Any) -> None: ...
    def __getitem__(self, key: builtins.str) -> typing.Any: ...
    def __contains__(self, key: builtins.str) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpeechRequest:
    r"""
    Typed wrapper for a text-to-speech request.
    """
    @property
    def text(self) -> builtins.str: ...
    @property
    def voice(self) -> typing.Optional[builtins.str]: ...
    @property
    def voice_url(self) -> typing.Optional[builtins.str]: ...
    @property
    def language(self) -> typing.Optional[builtins.str]: ...
    @property
    def speed(self) -> typing.Optional[builtins.float]: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, text: builtins.str, voice: typing.Optional[builtins.str] = None, voice_url: typing.Optional[builtins.str] = None, language: typing.Optional[builtins.str] = None, speed: typing.Optional[builtins.float] = None, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> SpeechRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class StartEvent(Event):
    r"""
    A start event that kicks off a workflow.
    
    Python usage:
    ```python
    ev = StartEvent(text="hello", count=5)
    ```
    """
    ...

@typing.final
class StateNamespace:
    r"""
    Namespace for persistable workflow state.
    
    Routes through the same 4-tier dispatch as the legacy `ctx.set` /
    `ctx.get`: bytes/JSON/pickle/live-object. The first three tiers
    are durable across `pause()` / `resume()` and checkpoint stores;
    the live-object tier (used as a last resort for unpicklable values)
    is in-process only.
    """
    def set(self, key: builtins.str, value: typing.Any) -> None:
        r"""
        Store a value under the given key. See `Context.set` for the
        4-tier dispatch order.
        """
    def get(self, key: builtins.str) -> typing.Any:
        r"""
        Retrieve a value previously stored under the given key.
        """
    def get_bytes(self, key: builtins.str) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Retrieve raw binary data previously stored under the given key.
        """
    def __setitem__(self, key: builtins.str, value: typing.Any) -> None: ...
    def __getitem__(self, key: builtins.str) -> typing.Any: ...
    def __contains__(self, key: builtins.str) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class StopEvent(Event):
    r"""
    A stop event that terminates a workflow with a result.
    
    Python usage:
    ```python
    ev = StopEvent(result={"answer": 42})
    ```
    """
    ...

@typing.final
class ThreeDRequest:
    r"""
    Typed wrapper for a 3D model generation request.
    """
    @property
    def prompt(self) -> builtins.str: ...
    @property
    def image_url(self) -> typing.Optional[builtins.str]: ...
    @property
    def format(self) -> typing.Optional[builtins.str]: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, prompt: builtins.str = '', image_url: typing.Optional[builtins.str] = None, format: typing.Optional[builtins.str] = None, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> ThreeDRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ThreeDResult:
    r"""
    Result of a 3D model generation operation.
    """
    @property
    def models(self) -> typing.Any:
        r"""
        The generated 3D models (as a list of dicts).
        """
    @property
    def timing(self) -> typing.Any:
        r"""
        Request timing breakdown (as a dict).
        """
    @property
    def cost(self) -> typing.Optional[builtins.float]:
        r"""
        Cost in USD, if reported by the provider.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Arbitrary provider-specific metadata (as a dict).
        """

@typing.final
class ToolDef:
    r"""
    A tool definition for the agent.
    
    Example:
        >>> tool = ToolDef(
        ...     name="search",
        ...     description="Search the web",
        ...     parameters={"type": "object", "properties": {"query": {"type": "string"}}},
        ...     handler=lambda args: {"results": []}
        ... )
    """
    def __new__(cls, *, name: builtins.str, description: builtins.str, parameters: typing.Any, handler: typing.Any) -> ToolDef: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TranscriptionRequest:
    r"""
    Typed wrapper for an audio transcription request.
    """
    @property
    def audio_url(self) -> builtins.str: ...
    @property
    def language(self) -> typing.Optional[builtins.str]: ...
    @property
    def diarize(self) -> builtins.bool: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, audio_url: builtins.str, language: typing.Optional[builtins.str] = None, diarize: builtins.bool = False, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> TranscriptionRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TranscriptionResult:
    r"""
    Result of a transcription operation.
    """
    @property
    def text(self) -> builtins.str:
        r"""
        The full transcribed text.
        """
    @property
    def segments(self) -> builtins.list[TranscriptionSegment]:
        r"""
        Time-aligned segments, if available.
        """
    @property
    def language(self) -> typing.Optional[builtins.str]:
        r"""
        Detected or specified language code (e.g. "en", "fr").
        """
    @property
    def timing(self) -> typing.Any:
        r"""
        Request timing breakdown (as a dict).
        """
    @property
    def cost(self) -> typing.Optional[builtins.float]:
        r"""
        Cost in USD, if reported by the provider.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Arbitrary provider-specific metadata (as a dict).
        """

@typing.final
class TranscriptionSegment:
    r"""
    A single segment within a transcription.
    """
    @property
    def text(self) -> builtins.str:
        r"""
        The transcribed text for this segment.
        """
    @property
    def start(self) -> builtins.float:
        r"""
        Start time in seconds.
        """
    @property
    def end(self) -> builtins.float:
        r"""
        End time in seconds.
        """
    @property
    def speaker(self) -> typing.Optional[builtins.str]:
        r"""
        Speaker label, if diarization was enabled.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class UpscaleRequest:
    r"""
    Typed wrapper for an image upscale request.
    """
    @property
    def image_url(self) -> builtins.str: ...
    @property
    def scale(self) -> builtins.float: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, image_url: builtins.str, scale: builtins.float, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> UpscaleRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ValkeyBackend:
    r"""
    A Valkey/Redis-backed storage backend for Memory.
    
    Uses Redis-compatible commands for persistence and band-based search.
    
    Example:
        >>> backend = ValkeyBackend("redis://localhost:6379")
        >>> memory = Memory(embedder, backend)
    """
    def __new__(cls, url: builtins.str, prefix: typing.Optional[builtins.str] = None) -> ValkeyBackend:
        r"""
        Create a new Valkey backend connected to the given URL.
        
        Args:
            url: A Redis/Valkey connection URL, e.g. "redis://localhost:6379".
            prefix: Optional key prefix for namespacing (default: "blazen:memory:").
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class VideoRequest:
    r"""
    Typed wrapper for a video generation request.
    """
    @property
    def prompt(self) -> builtins.str: ...
    @property
    def image_url(self) -> typing.Optional[builtins.str]: ...
    @property
    def duration_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def negative_prompt(self) -> typing.Optional[builtins.str]: ...
    @property
    def width(self) -> typing.Optional[builtins.int]: ...
    @property
    def height(self) -> typing.Optional[builtins.int]: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, prompt: builtins.str, image_url: typing.Optional[builtins.str] = None, duration_seconds: typing.Optional[builtins.float] = None, negative_prompt: typing.Optional[builtins.str] = None, width: typing.Optional[builtins.int] = None, height: typing.Optional[builtins.int] = None, model: typing.Optional[builtins.str] = None, parameters: typing.Optional[typing.Any] = None) -> VideoRequest: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class VideoResult:
    r"""
    Result of a video generation operation.
    """
    @property
    def videos(self) -> typing.Any:
        r"""
        The generated videos (as a list of dicts).
        """
    @property
    def timing(self) -> typing.Any:
        r"""
        Request timing breakdown (as a dict).
        """
    @property
    def cost(self) -> typing.Optional[builtins.float]:
        r"""
        Cost in USD, if reported by the provider.
        """
    @property
    def metadata(self) -> typing.Any:
        r"""
        Arbitrary provider-specific metadata (as a dict).
        """

@typing.final
class Workflow:
    r"""
    A validated, ready-to-run workflow.
    
    Construct a `Workflow` by providing a name and a list of step wrappers
    (created with the `@step` decorator).
    
    Example:
        >>> @step
        ... async def echo(ctx, ev):
        ...     return StopEvent(result=ev.to_dict())
        >>>
        >>> wf = Workflow("echo-wf", [echo])
        >>> handler = await wf.run({"message": "hello"})
        >>> result = await handler.result()
    """
    def __new__(cls, name: builtins.str, steps: typing.Sequence[_StepWrapper], timeout: typing.Optional[builtins.float] = None) -> Workflow:
        r"""
        Create a new workflow.
        
        Args:
            name: A human-readable name for the workflow.
            steps: A list of `_StepWrapper` objects created by `@step`.
            timeout: Optional timeout in seconds (default: 300).
        """
    def run(self, **kwargs: typing.Any) -> typing.Any:
        r"""
        Execute the workflow with a JSON payload.
        
        The payload is wrapped in a `StartEvent` and dispatched to the
        workflow engine.
        
        Args:
            input: A dict of data to pass as the start event payload.
        
        Returns:
            A `WorkflowHandler` for awaiting results or streaming events.
        
        Example:
            >>> handler = await wf.run({"prompt": "Hello!"})
            >>> result = await handler.result()
        """
    @staticmethod
    def resume(snapshot_json: builtins.str, steps: typing.Sequence[_StepWrapper], timeout: typing.Optional[builtins.float] = None) -> typing.Any:
        r"""
        Resume a workflow from a previously captured snapshot.
        
        This is a static method -- call it as `Workflow.resume(...)`.
        
        The steps must be the same set (or a compatible superset) of steps
        that were registered when the workflow was originally created.
        
        Args:
            snapshot_json: A JSON string produced by `WorkflowHandler.pause()`.
            steps: A list of `_StepWrapper` objects created by `@step`.
            timeout: Optional timeout in seconds (default: 300).
        
        Returns:
            A new `WorkflowHandler` for the resumed workflow.
        
        Example:
            >>> handler = await Workflow.resume(snapshot_json, [step1, step2])
            >>> result = await handler.result()
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class WorkflowHandler:
    r"""
    Handle to a running workflow.
    
    Use `result()` to await the final result, or `stream_events()` to
    iterate over intermediate events published by steps.
    
    Example:
        >>> handler = await wf.run(prompt="Hello")
        >>> result = await handler.result()
        >>> print(result.to_dict())
    """
    def result(self) -> typing.Any:
        r"""
        Await the final workflow result.
        
        Consumes the handler. Returns the terminal event (typically a
        `StopEvent`). Raises `RuntimeError` if the handler was already
        consumed.
        
        Returns:
            The final Event produced by the workflow.
        """
    def stream_events(self) -> _EventStream:
        r"""
        Create an async iterator over intermediate events.
        
        Steps publish events to the stream via `ctx.write_event_to_stream()`.
        The stream is pre-subscribed at handler construction time so no events
        are lost between `wf.run()` and this call.
        
        The stream terminates when the workflow completes (a `blazen::StreamEnd`
        sentinel is sent by the event loop).
        
        Returns:
            An async iterator of Events.
        
        Example:
            >>> async for event in handler.stream_events():
            ...     print(event.event_type, event.to_dict())
        """
    def pause(self) -> typing.Any:
        r"""
        Pause the running workflow.
        
        Sends a pause signal to the workflow event loop. The workflow will
        park after the current step completes. Does **not** consume the
        handler -- you can later call `resume_in_place()`, `snapshot()`,
        or `abort()`.
        
        Raises `RuntimeError` if the handler was already consumed.
        """
    def resume_in_place(self) -> typing.Any:
        r"""
        Resume a paused workflow in place.
        
        Sends a resume signal so the workflow continues from where it was
        paused.
        
        Raises `RuntimeError` if the handler was already consumed.
        """
    def snapshot(self) -> typing.Any:
        r"""
        Capture a snapshot of the current workflow state.
        
        Returns a JSON string that can be passed to `Workflow.resume()` to
        continue execution later.
        
        Raises `RuntimeError` if the handler was already consumed.
        
        Returns:
            A JSON string representing the workflow snapshot.
        """
    def respond_to_input(self, request_id: builtins.str, response: typing.Any) -> typing.Any:
        r"""
        Respond to an input request from a workflow step.
        
        Args:
            request_id: The ID from the `InputRequestEvent`.
            response: A Python dict/value that will be converted to JSON and
                      delivered to the waiting step.
        
        Raises `RuntimeError` if the handler was already consumed.
        """
    def abort(self) -> typing.Any:
        r"""
        Abort the running workflow.
        
        Sends an abort signal. The workflow will terminate as soon as
        possible. Does **not** consume the handler.
        
        Raises `RuntimeError` if the handler was already consumed.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class _EventStream:
    r"""
    Async iterator over streamed workflow events.
    
    Implements the Python `__aiter__` / `__anext__` protocol so it can be
    used with `async for`.
    
    The stream terminates when it receives a `"blazen::StreamEnd"` sentinel
    event from the event loop, or when the underlying broadcast channel closes.
    """
    def __aiter__(self) -> _EventStream: ...
    def __anext__(self) -> typing.Any: ...

@typing.final
class _SessionRegistryHandle:
    r"""
    Opaque PyO3-visible holder for an `Arc<SessionRefRegistry>`. Stored
    inside the Python `ContextVar` so the user-side asyncio Task can
    carry the registry across `await` points without exposing the inner
    type to user code.
    """
    ...

@typing.final
class _StepWrapper:
    r"""
    Internal wrapper created by the `@step` decorator.
    
    Holds the Python async function and metadata for registration with
    the workflow engine.
    
    Example:
        >>> @step
        ... async def analyze(ctx: Context, ev: Event) -> Event:
        ...     return Event("ResultEvent", answer=42)
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The step name (derived from the function name).
        """
    @property
    def accepts(self) -> builtins.list[builtins.str]:
        r"""
        Event type identifiers this step accepts.
        """
    @accepts.setter
    def accepts(self, value: builtins.list[builtins.str]) -> None:
        r"""
        Event type identifiers this step accepts.
        """
    @property
    def emits(self) -> builtins.list[builtins.str]:
        r"""
        Event type identifiers this step may emit.
        """
    @emits.setter
    def emits(self, value: builtins.list[builtins.str]) -> None:
        r"""
        Event type identifiers this step may emit.
        """
    @property
    def max_concurrency(self) -> builtins.int:
        r"""
        Maximum concurrency (0 = unlimited).
        """
    @max_concurrency.setter
    def max_concurrency(self, value: builtins.int) -> None:
        r"""
        Maximum concurrency (0 = unlimited).
        """
    def __call__(self, ctx: typing.Any, event: typing.Any) -> typing.Any:
        r"""
        Call the underlying function (makes the wrapper callable like the
        original function for testing convenience).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CacheStrategy(enum.Enum):
    None = ...
    ContentHash = ...
    AnthropicEphemeral = ...
    Auto = ...

@typing.final
class FalLlmEndpointKind(enum.Enum):
    r"""
    Simplified fal.ai endpoint family.
    """
    OpenAiChat = ...
    OpenAiResponses = ...
    OpenAiEmbeddings = ...
    OpenRouter = ...
    AnyLlm = ...

