#!/usr/bin/env bash
# CI helper: regenerate all binding artefacts and fail if anything changed.
#
# Used by .forgejo/workflows/ci.yaml's `audit-bindings` job. Local equivalent
# of the audit pyo3-stub-gen / napi build / wasm-pack build drift checks for
# the existing Python/Node/WASM bindings.
#
# Covers two regen surfaces:
#   1. UniFFI bindings (Go/Swift/Kotlin) — generated by `scripts/regen-bindings.sh`
#      from blazen-uniffi's metadata. Drift target: bindings/<lang>/...
#   2. cbindgen C header (Ruby) — generated by `cargo build -p blazen-cabi`'s
#      build.rs invoking cbindgen. Drift target: bindings/ruby/ext/blazen/blazen.h
#
# Usage: ./scripts/audit-bindings-drift.sh
set -euo pipefail

cd "$(dirname "$0")/.."

# -----------------------------------------------------------------------------
# 1. UniFFI bindings (Go/Swift/Kotlin). Ruby no longer participates here —
#    the gem links against libblazen_cabi via the cbindgen C ABI, not against
#    UniFFI-generated Ruby scaffolding (the upstream uniffi-bindgen Ruby
#    template doesn't emit working with_foreign callback support).
# -----------------------------------------------------------------------------
./scripts/regen-bindings.sh

BINDING_DIRS=(
    bindings/go/internal/uniffi
    bindings/swift/Sources/UniFFIBlazen
    bindings/kotlin/src/commonMain/uniffi
)

if ! git diff --exit-code -- "${BINDING_DIRS[@]}"; then
    echo
    echo "ERROR: UniFFI-generated bindings are out of date." >&2
    echo "Run scripts/regen-bindings.sh locally and commit the diff." >&2
    exit 1
fi

echo "Go/Swift/Kotlin UniFFI bindings are in sync with blazen-uniffi."

# -----------------------------------------------------------------------------
# 2. cbindgen C header (Ruby). build.rs runs cbindgen and writes
#    bindings/ruby/ext/blazen/blazen.h on every `cargo build -p blazen-cabi`,
#    so a release build is enough to regenerate it.
# -----------------------------------------------------------------------------
echo
echo "Regenerating bindings/ruby/ext/blazen/blazen.h via cargo build -p blazen-cabi..."
cargo build -p blazen-cabi --release

CABI_HEADER=bindings/ruby/ext/blazen/blazen.h

if ! git diff --exit-code -- "${CABI_HEADER}"; then
    echo
    echo "ERROR: ${CABI_HEADER} is out of date." >&2
    echo "Run 'cargo build -p blazen-cabi --release' locally and commit the diff." >&2
    exit 1
fi

echo "${CABI_HEADER} is in sync with blazen-cabi."
echo
echo "All binding artefacts (Go/Swift/Kotlin UniFFI + Ruby cbindgen header) are in sync."
