#!/usr/bin/env bash
# Regenerate the foreign-language UniFFI bindings from blazen-uniffi.
#
# Drives:
#   uniffi-bindgen-go    → bindings/go/internal/uniffi/blazen/
#   uniffi-bindgen swift → bindings/swift/Sources/UniFFIBlazen/
#   uniffi-bindgen kotlin → bindings/kotlin/src/main/kotlin/dev/zorpx/blazen/uniffi/
#
# Ruby is NOT regenerated by this script. The Ruby gem links against
# `libblazen_cabi` (the hand-rolled cbindgen + C ABI cdylib in
# `crates/blazen-cabi/`) instead of UniFFI-generated Ruby scaffolding —
# the upstream uniffi-bindgen Ruby template does not emit working
# `with_foreign` callback support. To regenerate the Ruby C header, run:
#
#   cargo build -p blazen-cabi --release
#
# That invokes cbindgen via build.rs and writes bindings/ruby/ext/blazen/blazen.h.
#
# CI runs this followed by `git diff --exit-code` to catch unregenerated
# drift (see .forgejo/workflows/ci.yaml `audit-bindings` job).
#
# Usage:
#   ./scripts/regen-bindings.sh            # all three (go, swift, kotlin)
#   ./scripts/regen-bindings.sh go         # subset: go|swift|kotlin (space-separated)
#
# Prerequisites (install with the helper at the bottom of this file):
#   uniffi-bindgen-go (NordSecurity) — for Go
#   uniffi-bindgen (mozilla/uniffi-rs) — for Swift / Kotlin
#
# Both tools are pinned to uniffi-rs 0.31. Mismatched versions will produce
# scaffolding that doesn't match the runtime, with confusing link errors.
set -euo pipefail

cd "$(dirname "$0")/.."

UNIFFI_VERSION="0.31"

# Prefer the locally-built uniffi-bindgen CLI (target/release/uniffi-bindgen)
# over a globally-installed one. The local CLI is built from blazen-uniffi's
# bin/uniffi-bindgen.rs entrypoint, so its version is guaranteed to match the
# runtime scaffolding embedded in the cdylib. A mismatched globally-installed
# uniffi-bindgen would emit incompatible glue with cryptic link errors.
if [[ -x "target/release/uniffi-bindgen" ]]; then
    UNIFFI_BINDGEN="target/release/uniffi-bindgen"
elif command -v uniffi-bindgen >/dev/null 2>&1; then
    UNIFFI_BINDGEN="$(command -v uniffi-bindgen)"
else
    echo "ERROR: uniffi-bindgen not found. Build the local CLI first:"
    echo "  cargo build -p blazen-uniffi --release --bin uniffi-bindgen"
    exit 1
fi
echo "Using uniffi-bindgen: $UNIFFI_BINDGEN"

# ---- pick targets -----------------------------------------------------------
TARGETS=("$@")
if [[ ${#TARGETS[@]} -eq 0 ]]; then
    TARGETS=(go swift kotlin)
fi

# ---- ensure native lib is built (bindgens read metadata from it) -----------
# UniFFI's library-mode bindgen reads scaffolding metadata (UNIFFI_META_*
# symbols) directly from the compiled artefact. Empirically on this workspace,
# all three release artefacts retain the full set of metadata symbols:
#   target/release/libblazen_uniffi.so   (cdylib)    — 138 UNIFFI_META symbols
#   target/release/libblazen_uniffi.a    (staticlib) — 138 UNIFFI_META symbols
#   target/release/libblazen_uniffi.rlib (rlib)      — 138 UNIFFI_META symbols
#
# The metadata is what powers every #[uniffi::export] proc-macro; without
# --library, bindgen falls back to UDL (which only declares `version()` here)
# and silently emits a near-empty surface. Always pass --library.
#
# We prefer the per-build rlib in target/release/deps/ (matches upstream
# uniffi-rs examples), but fall back to the top-level rlib or the staticlib,
# all of which are equivalent for metadata purposes.
DEPS_DIR="target/release/deps"
# Glob expansion under set -u/-e/pipefail: use a shell array so a missing
# pattern doesn't trigger pipeline failures.
LIB_PATH=""
shopt -s nullglob
deps_rlibs=("$DEPS_DIR"/libblazen_uniffi-*.rlib)
shopt -u nullglob
if (( ${#deps_rlibs[@]} > 0 )); then
    LIB_PATH="${deps_rlibs[0]}"
elif [[ -f "target/release/libblazen_uniffi.rlib" ]]; then
    LIB_PATH="target/release/libblazen_uniffi.rlib"
elif [[ -f "target/release/libblazen_uniffi.a" ]]; then
    LIB_PATH="target/release/libblazen_uniffi.a"
fi

if [[ -z "$LIB_PATH" || ! -f "$LIB_PATH" ]]; then
    echo "Building blazen-uniffi (release) so bindgens can read scaffolding metadata..."
    cargo build -p blazen-uniffi --release
    shopt -s nullglob
    deps_rlibs=("$DEPS_DIR"/libblazen_uniffi-*.rlib)
    shopt -u nullglob
    if (( ${#deps_rlibs[@]} > 0 )); then
        LIB_PATH="${deps_rlibs[0]}"
    elif [[ -f "target/release/libblazen_uniffi.rlib" ]]; then
        LIB_PATH="target/release/libblazen_uniffi.rlib"
    else
        LIB_PATH="target/release/libblazen_uniffi.a"
    fi
fi

echo "Using artefact for metadata: $LIB_PATH"

UDL="crates/blazen-uniffi/src/blazen.udl"
CFG="crates/blazen-uniffi/uniffi.toml"

regen_go() {
    if ! command -v uniffi-bindgen-go >/dev/null 2>&1; then
        echo "ERROR: uniffi-bindgen-go not installed."
        echo "  Install with: cargo install uniffi-bindgen-go --tag v0.7.1+v$UNIFFI_VERSION.0 --git https://github.com/NordSecurity/uniffi-bindgen-go"
        return 1
    fi
    mkdir -p bindings/go/internal/uniffi
    uniffi-bindgen-go \
        --library "$LIB_PATH" \
        --config "$CFG" \
        --out-dir bindings/go/internal/uniffi
    # Patch a known uniffi-bindgen-go codegen bug: when a method takes a
    # parameter named `err` (e.g. CompletionStreamSink.on_error(err)), the
    # generated Go body declares `_, err := uniffiRustCallAsync(...)` which
    # collides with the parameter and fails `go vet` ("no new variables on
    # left side of :="). Rename the parameter so the local err declaration
    # is the only `err` in scope.
    if [[ -f bindings/go/internal/uniffi/blazen/blazen.go ]]; then
        python3 - <<'PY'
import re
from pathlib import Path
p = Path("bindings/go/internal/uniffi/blazen/blazen.go")
src = p.read_text()
pattern = re.compile(
    r'func \(_self \*CompletionStreamSinkImpl\) OnError\(err \*BlazenError\) error \{[\s\S]*?'
    r'FfiConverterBlazenErrorINSTANCE\.Lower\(err\)\)',
)
def fixup(match):
    block = match.group(0)
    block = block.replace("OnError(err *BlazenError)", "OnError(onErrorArg *BlazenError)", 1)
    block = block.replace("FfiConverterBlazenErrorINSTANCE.Lower(err))", "FfiConverterBlazenErrorINSTANCE.Lower(onErrorArg))", 1)
    return block
new_src, n = pattern.subn(fixup, src, count=1)
if n:
    p.write_text(new_src)
    print(f"  ↳ patched OnError parameter shadowing ({n} site)")
PY
    fi
    # Patch upstream uniffi-bindgen-go's misleading "TODO: this is bad" and
    # "TODO: Remove this" comments. The audit (2026-05-13) showed that the
    # incrementPointer / decrementPointer pair is safe: incrementPointer calls
    # the Rust cloneFunction which Arc::clones on the Rust side, so the handle
    # passed to C survives independently of the Go-side callCounter. The
    # LiftFromRustBuffer panic is a defensive guard against Rust↔Go bindgen
    # protocol desync and should stay. Replace the comments inline so future
    # reviewers see the reasoning without redoing the analysis.
    if [[ -f bindings/go/internal/uniffi/blazen/blazen.go ]]; then
        python3 - <<'PY'
import sys
from pathlib import Path
p = Path("bindings/go/internal/uniffi/blazen/blazen.go")
src = p.read_text()
old_a = (
    "\t// TODO: this is bad - all synchronization from ObjectRuntime.go is discarded here,\n"
    "\t// because the handle will be decremented immediately after this function returns,\n"
    "\t// and someone will be left holding onto a non-locked handle.\n"
)
new_a = (
    "\t// SAFETY (audited 2026-05-13): incrementPointer calls cloneFunction\n"
    "\t// which does Arc::clone on the Rust side, bumping the Rust refcount\n"
    "\t// independently of the Go-side callCounter. The defer below only\n"
    "\t// decrements the (redundant) Go counter; the returned handle survives\n"
    "\t// because the C caller owns its own Arc refcount via Arc::from_raw.\n"
)
old_b = (
    "\t\t// TODO: Remove this\n"
    "\t\tleftover, _ := io.ReadAll(reader)\n"
    "\t\tpanic(fmt.Errorf(\"Junk remaining in buffer after lifting: %s\", string(leftover)))\n"
)
new_b = (
    "\t\t// Defensive: protocol desync between Rust/Go bindgen would leave\n"
    "\t\t// bytes here. Panicking surfaces it immediately rather than silently\n"
    "\t\t// dropping data on the floor; keep this guard even though codegen\n"
    "\t\t// is expected to keep buffers balanced.\n"
    "\t\tleftover, _ := io.ReadAll(reader)\n"
    "\t\tpanic(fmt.Errorf(\"Junk remaining in buffer after lifting: %s\", string(leftover)))\n"
)
count_a = src.count(old_a)
count_b = src.count(old_b)
if count_a != 19:
    sys.exit(
        f"ERROR: expected 19 'TODO: this is bad' blocks in blazen.go, found {count_a}. "
        "Upstream uniffi-bindgen-go codegen likely changed — re-audit and update "
        "the patch in scripts/regen-bindings.sh."
    )
if count_b != 1:
    sys.exit(
        f"ERROR: expected 1 'TODO: Remove this' block in blazen.go, found {count_b}. "
        "Upstream uniffi-bindgen-go codegen likely changed — re-audit and update "
        "the patch in scripts/regen-bindings.sh."
    )
src = src.replace(old_a, new_a)
src = src.replace(old_b, new_b)
p.write_text(src)
print(f"  ↳ patched {count_a} TODO-is-bad blocks and {count_b} TODO-Remove-this blocks")
PY
    fi
    echo "  ✓ Go bindings → bindings/go/internal/uniffi/"
}

regen_swift() {
    mkdir -p bindings/swift/Sources/UniFFIBlazen
    # --no-format: skip swift-format post-processing. CI's audit-bindings job
    # doesn't install swift-format, so without this flag the committed
    # (formatted) file disagrees with CI's regen and `git diff --exit-code`
    # fails. Deterministic-everywhere unformatted output is preferable to
    # env-dependent formatted output.
    "$UNIFFI_BINDGEN" generate \
        --library "$LIB_PATH" \
        --language swift \
        --no-format \
        --config "$CFG" \
        --out-dir bindings/swift/Sources/UniFFIBlazen
    # uniffi-bindgen emits the FFI C header at
    # bindings/swift/Sources/UniFFIBlazen/BlazenFFI.h, but the SwiftPM
    # target that actually links against the cdylib lives at
    # bindings/swift/Sources/BlazenFFI/ and expects its header at
    # include/BlazenFFI.h. Without this sync step, the second location
    # silently goes stale and the Swift build fails with a missing-symbol
    # link error after any UniFFI surface change.
    mkdir -p bindings/swift/Sources/BlazenFFI/include
    cp bindings/swift/Sources/UniFFIBlazen/BlazenFFI.h \
       bindings/swift/Sources/BlazenFFI/include/BlazenFFI.h
    echo "  ✓ Swift bindings → bindings/swift/Sources/UniFFIBlazen/ (header synced to BlazenFFI/include/)"
}

regen_kotlin() {
    # Output to src/main/kotlin so the generated file's package
    # (`dev.zorpx.blazen.uniffi`, set in uniffi.toml) lands at the path
    # `src/main/kotlin/dev/zorpx/blazen/uniffi/blazen.kt` that the hand-
    # written wrappers in `src/main/kotlin/dev/zorpx/blazen/` import.
    mkdir -p bindings/kotlin/src/main/kotlin
    # ktlint must be on PATH so uniffi-bindgen's post-process formatter runs.
    # Without ktlint, the emitted file is unformatted and disagrees with the
    # committed (formatted) version, causing CI's `git diff --exit-code` to
    # fail. CI installs ktlint in the audit-bindings job to match local devs.
    "$UNIFFI_BINDGEN" generate \
        --library "$LIB_PATH" \
        --language kotlin \
        --config "$CFG" \
        --out-dir bindings/kotlin/src/main/kotlin
    # Patch a known uniffi-bindgen-kotlin codegen bug: each variant of the
    # sealed `BlazenException` class declares the constructor parameter as
    # plain `val message: kotlin.String` AND an override body
    # `override val message get() = "..."` — Kotlin rejects this as a
    # name collision ("Conflicting declarations" + "Overload resolution
    # ambiguity"). The fix is to promote the constructor parameter to
    # `override val message: kotlin.String` and drop the override body.
    # `Cancelled` has no constructor params and is left alone.
    local kt_file=bindings/kotlin/src/main/kotlin/dev/zorpx/blazen/uniffi/blazen.kt
    if [[ -f "$kt_file" ]]; then
        BLAZEN_KT_FILE="$kt_file" python3 - <<'PY'
import os
import re
from pathlib import Path
p = Path(os.environ["BLAZEN_KT_FILE"])
src = p.read_text()
pattern = re.compile(
    r'(class \w+\([^)]*?)(\n\s+)val `message`: kotlin\.String'
    r'([^)]*?\) : BlazenException\(\)) \{\s*'
    r'override val message\s*\n\s*get\(\) = "[^"]*"\s*\n\s*\}',
    re.MULTILINE,
)
def fixup(m):
    return f"{m.group(1)}{m.group(2)}override val `message`: kotlin.String{m.group(3)}"
new_src, n = pattern.subn(fixup, src)
if n:
    p.write_text(new_src)
    print(f"  ↳ patched BlazenException variant message collisions ({n} sites)")
PY
    fi
    echo "  ✓ Kotlin bindings → bindings/kotlin/src/main/kotlin/dev/zorpx/blazen/uniffi/"
}

# Silence unused-fn warnings — these are conditionally invoked below.
: "${UDL}"

echo "Regenerating bindings for: ${TARGETS[*]}"
for t in "${TARGETS[@]}"; do
    case "$t" in
        go) regen_go ;;
        swift) regen_swift ;;
        kotlin) regen_kotlin ;;
        ruby)
            echo "ERROR: Ruby is not regenerated by this script." >&2
            echo "  The Ruby gem uses cbindgen, not UniFFI. To regenerate the C header, run:" >&2
            echo "    cargo build -p blazen-cabi --release" >&2
            exit 1
            ;;
        *) echo "Unknown target: $t (use go|swift|kotlin)" >&2; exit 1 ;;
    esac
done

echo "Done."
